/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.Lie.Free
public import TauCeti.Algebra.Lie.Basic

/-!
# Presenting a Lie algebra by generators and relations

A Lie algebra presented by generators `X` and relations `S ⊆ FreeLieAlgebra R X` is the quotient of
`FreeLieAlgebra R X` by the Lie ideal generated by `S`. Mathlib builds both halves of that
construction — the free Lie algebra with its universal property, and the `LieRing`/`LieAlgebra`
structure on a quotient by a Lie ideal — but not the bridge between them, which is what a
presentation is used for: a homomorphism out of the presented algebra is the same thing as a family
of images satisfying the relations. The quotient universal property is provided by
`TauCeti/Algebra/Lie/Quotient.lean`; this file supplies the generation result needed to apply it,
and imports adjoint-action infrastructure from `TauCeti/Algebra/Lie/Basic.lean`.

Relations of a presentation are frequently written as the vanishing of `(ad x) ^ n y` — Serre's
relations for a Cartan matrix are the standard example — and such a relation says nothing about the
presented algebra until it is known to be carried along by the map that checks it. That transport
is `LieHom.map_ad_pow`, which lives in `TauCeti/Algebra/Lie/Basic.lean` and is imported here. The
imported companion is `TauCeti.ad_neg_pow_apply_eq_zero`, which carries
such a vanishing result from `x` to `-x`; equivalently, `x` and `-x` have the same Engel subalgebra
(`LieSubalgebra.engel_neg`), the elements on which their adjoint actions are locally nilpotent.

This file proves that a free Lie algebra is generated, as a Lie subalgebra, by its generators:
`TauCeti.FreeLieAlgebra.lieSpan_range_of_eq_top`. This is what makes the images of the generators
generate the presented algebra, rather than merely determine maps out of it.

## Main results

* `TauCeti.FreeLieAlgebra.lieSpan_range_of_eq_top`: the generators of a free Lie algebra generate it
  as a Lie subalgebra.

## Roadmap

These are the general steps behind the universal property of the Serre presentation in
`TauCeti/Algebra/Lie/Presentation/Serre.lean`, which names the generators of
`Matrix.ToLieAlgebra R CM` and maps out of it, as required by the Chevalley--Demazure construction
of Layer 9 of `TauCetiRoadmap/ReductiveGroups/README.md`.
-/

public section

namespace TauCeti

variable {R L : Type*} [CommRing R] [LieRing L] [LieAlgebra R L]

namespace FreeLieAlgebra

variable (R : Type*) [CommRing R] (X : Type*)

/-- The generators of a free Lie algebra generate it as a Lie subalgebra. -/
theorem lieSpan_range_of_eq_top :
    LieSubalgebra.lieSpan R (FreeLieAlgebra R X) (Set.range (FreeLieAlgebra.of R)) = ⊤ := by
  set K := LieSubalgebra.lieSpan R (FreeLieAlgebra R X) (Set.range (FreeLieAlgebra.of R))
  have hmem (x : X) : FreeLieAlgebra.of R x ∈ K :=
    LieSubalgebra.subset_lieSpan (Set.mem_range_self x)
  set g : FreeLieAlgebra R X →ₗ⁅R⁆ K := FreeLieAlgebra.lift R fun x => ⟨_, hmem x⟩ with hg
  have hid : K.incl.comp g = LieHom.id := by
    refine FreeLieAlgebra.hom_ext fun x => ?_
    simp [hg, LieHom.comp_apply, FreeLieAlgebra.lift_of_apply]
  refine eq_top_iff.2 fun y _ => ?_
  have hy : K.incl (g y) = y :=
    congrArg (fun F : FreeLieAlgebra R X →ₗ⁅R⁆ FreeLieAlgebra R X => F y) hid
  exact hy ▸ (g y).2

end FreeLieAlgebra

end TauCeti
