/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.Lie.SerreConstruction
public import TauCeti.Algebra.Lie.Presentation.Basic
import TauCeti.Algebra.Lie.Basic
public import TauCeti.Algebra.Lie.Quotient

/-!
# The Serre presentation: generators, relations, and the universal property

Mathlib's `Matrix.ToLieAlgebra R CM` is the Lie algebra presented by Serre's relations for a matrix
`CM` of integers: the quotient of the free Lie algebra on the generators `Hᵢ`, `Eᵢ`, `Fᵢ` by the
Lie ideal `CartanMatrix.Relations.toIdeal` generated by

`⁅Hᵢ, Hⱼ⁆`,  `⁅Eᵢ, Fᵢ⁆ - Hᵢ`,  `⁅Eᵢ, Fⱼ⁆ (i ≠ j)`,  `⁅Hᵢ, Eⱼ⁆ - CMᵢⱼ • Eⱼ`,  `⁅Hᵢ, Fⱼ⁆ + CMᵢⱼ • Fⱼ`,
`(ad Eᵢ) ^ (-CMᵢⱼ).toNat ⁅Eᵢ, Eⱼ⁆`,  `(ad Fᵢ) ^ (-CMᵢⱼ).toNat ⁅Fᵢ, Fⱼ⁆`.

That definition is all Mathlib records: the generators of the presented algebra are not named, the
relations are not known to hold in it, and nothing maps out of it. This file supplies those three
things, which is what makes the presentation usable.

The generators `TauCeti.serreH`, `TauCeti.serreE` and `TauCeti.serreF` are the images of the free
generators. The relations they satisfy are collected in the predicate `TauCeti.IsSerreSystem`, one
field per displayed relator, and `TauCeti.isSerreSystem_serre` proves that the generators of the
presented algebra form such a system — the "only if" direction of the presentation. The converse is
`TauCeti.serreLift`: any Serre system in any Lie algebra `L` is the image of the generators under a
homomorphism out of `Matrix.ToLieAlgebra R CM`, and by `TauCeti.serre_hom_ext` that homomorphism is
the only one with those values. The symmetries of Serre's relations are recorded as stability
properties of `TauCeti.IsSerreSystem` — under reindexing the families along an injective map of
index sets and under the signed exchange of the raising and lowering families — since they are
statements about an arbitrary Serre system rather than about the presented algebra. Finally
`TauCeti.lieSpan_serreGenerators_eq_top` records that the three families generate the presented
algebra as a Lie subalgebra.

Nothing here assumes that `CM` is a Cartan matrix, since none of it needs to: the presented algebra
is defined for an arbitrary matrix of integers, and the universal property is a statement about the
relators rather than about the geometry behind them. Accordingly no statement below mentions a root
system: `TauCeti.serreH`, `TauCeti.serreE` and `TauCeti.serreF` are named after the free generators
`Hᵢ`, `Eᵢ`, `Fᵢ` they are the images of, and reading them as a coroot and a pair of simple root
vectors of a split semisimple Lie algebra needs the identification of the presented algebra with
one, which is not proved here (see the Roadmap section below).

## Main definitions

* `TauCeti.serreMk`: the quotient map presenting `Matrix.ToLieAlgebra R CM`.
* `TauCeti.serreH`, `TauCeti.serreE`, `TauCeti.serreF`: the generators of the presented algebra.
* `TauCeti.IsSerreSystem`: three families of elements of a Lie algebra satisfying Serre's relations
  for `CM`.
* `TauCeti.serreLift`: the homomorphism out of `Matrix.ToLieAlgebra R CM` determined by a Serre
  system.

## Main results

* `TauCeti.isSerreSystem_serre`: the generators of `Matrix.ToLieAlgebra R CM` are a Serre system,
  with the individual relations available as `TauCeti.lie_serreH_serreH` and its companions.
* `TauCeti.serreLift_serreH`, `TauCeti.serreLift_serreE`, `TauCeti.serreLift_serreF` and
  `TauCeti.serre_hom_ext`: `TauCeti.serreLift` sends the generators to the given Serre system, and
  is the unique homomorphism doing so; `TauCeti.serre_equiv_ext` is the same extensionality
  principle for equivalences out of the presented algebra.
* `TauCeti.IsSerreSystem.changeScalars`: a Serre system over one base ring is one over any other
  base ring for which the same Lie ring has a Lie-algebra structure.
* `TauCeti.IsSerreSystem.map`, `TauCeti.IsSerreSystem.submatrix`, `TauCeti.IsSerreSystem.perm` and
  `TauCeti.IsSerreSystem.neg_swap`: Serre systems are preserved by Lie homomorphisms, reindexing,
  and the signed exchange of the raising and lowering families.
* `TauCeti.serreLift_eq_id`: lifting the generators along their own Serre system is the identity.
* `TauCeti.lieSpan_serreGenerators_eq_top`: the generators generate the presented algebra.
* `TauCeti.lieSpan_serreE_union_serreF_eq_top`: the raising and lowering generators alone generate
  the presented algebra.

## Roadmap

This is a prerequisite for the Chevalley--Demazure construction, Layer 9 of
`TauCetiRoadmap/ReductiveGroups/README.md`, which builds the split reductive group scheme over `ℤ`
of a pinned root datum from a Chevalley basis and the Kostant `ℤ`-form of the enveloping algebra of
the corresponding split semisimple Lie algebra. The Serre presentation of the pinned Cartan matrix
is the explicit carrier of that Lie algebra, and the generators named here are the ones a Chevalley
basis of it starts from. Consumed in turn by milestone L0 of
`TauCetiRoadmap/CFSGStatement/README.md`. The presentation theorem identifying the presented algebra
with a concrete split semisimple Lie algebra is a separate target, Layer 7 of
`TauCetiRoadmap/RepresentationTheory/LieHighestWeight/README.md`; it consumes `TauCeti.serreLift`
to build its comparison map, and is not begun here.

## References

* [N. Bourbaki, *Lie Groups and Lie Algebras, Chapters 4--6*][bourbaki1968]
* [J.P. Serre, *Complex Semisimple Lie Algebras*][serre1965], chapter VI, appendix
-/

public section

namespace TauCeti

open CartanMatrix CartanMatrix.Relations LieAlgebra

variable {B : Type*} [DecidableEq B] (R : Type*) [CommRing R] (CM : Matrix B B ℤ)

/-! ## The generators -/

/-- The quotient map presenting `Matrix.ToLieAlgebra R CM` as the free Lie algebra on the Serre
generators modulo the Lie ideal generated by Serre's relations. -/
noncomputable def serreMk :
    FreeLieAlgebra R (Generators B) →ₗ⁅R⁆ Matrix.ToLieAlgebra R CM :=
  LieIdeal.mkQ (Relations.toIdeal R CM)

/-- The kernel of the presentation map is the Lie ideal generated by Serre's relations. -/
@[simp]
theorem ker_serreMk : (serreMk R CM).ker = Relations.toIdeal R CM := LieIdeal.ker_mkQ _

/-- Every element of the presented algebra is the class of an element of the free Lie algebra. -/
theorem serreMk_surjective : Function.Surjective (serreMk R CM) :=
  (Relations.toIdeal R CM).mkQ_surjective

/-- A relator of Serre's presentation becomes zero in the presented algebra. -/
theorem serreMk_eq_zero_of_mem_toSet {x : FreeLieAlgebra R (Generators B)}
    (hx : x ∈ Relations.toSet R CM) : serreMk R CM x = 0 :=
  (LieIdeal.mkQ_apply _ x).trans
    (LieSubmodule.Quotient.mk_eq_zero'.mpr (LieSubmodule.subset_lieSpan hx))

/-- The generator `Hᵢ` of `Matrix.ToLieAlgebra R CM`, the image of the free generator `Hᵢ`. -/
noncomputable def serreH (i : B) : Matrix.ToLieAlgebra R CM :=
  serreMk R CM (FreeLieAlgebra.of R (Generators.H i))

/-- The generator `Eᵢ` of `Matrix.ToLieAlgebra R CM`, the image of the free generator `Eᵢ`. -/
noncomputable def serreE (i : B) : Matrix.ToLieAlgebra R CM :=
  serreMk R CM (FreeLieAlgebra.of R (Generators.E i))

/-- The generator `Fᵢ` of `Matrix.ToLieAlgebra R CM`, the image of the free generator `Fᵢ`. -/
noncomputable def serreF (i : B) : Matrix.ToLieAlgebra R CM :=
  serreMk R CM (FreeLieAlgebra.of R (Generators.F i))

/-- The quotient map sends the free generator `Hᵢ` to `TauCeti.serreH`. -/
@[simp]
theorem serreMk_of_H (i : B) :
    serreMk R CM (FreeLieAlgebra.of R (Generators.H i)) = serreH R CM i := (rfl)

/-- The quotient map sends the free generator `Eᵢ` to `TauCeti.serreE`. -/
@[simp]
theorem serreMk_of_E (i : B) :
    serreMk R CM (FreeLieAlgebra.of R (Generators.E i)) = serreE R CM i := (rfl)

/-- The quotient map sends the free generator `Fᵢ` to `TauCeti.serreF`. -/
@[simp]
theorem serreMk_of_F (i : B) :
    serreMk R CM (FreeLieAlgebra.of R (Generators.F i)) = serreF R CM i := (rfl)

/-! ## The relators lie in the defining ideal

Each of the six families of relators of `CartanMatrix.Relations.toSet` is a range, and membership
in the union is recorded once here so that the relations below read off from a single lemma. These
are proof-local plumbing: the relations themselves, below, are the public statement. -/

private theorem mem_toSet_HH (i j : B) : HH R (i, j) ∈ Relations.toSet R CM := by
  simp [Relations.toSet]

private theorem mem_toSet_EF (i j : B) : EF R (i, j) ∈ Relations.toSet R CM := by
  simp [Relations.toSet]

private theorem mem_toSet_HE (i j : B) : HE R CM (i, j) ∈ Relations.toSet R CM := by
  simp [Relations.toSet]

private theorem mem_toSet_HF (i j : B) : HF R CM (i, j) ∈ Relations.toSet R CM := by
  simp [Relations.toSet]

private theorem mem_toSet_adE (i j : B) : adE R CM (i, j) ∈ Relations.toSet R CM := by
  simp [Relations.toSet]

private theorem mem_toSet_adF (i j : B) : adF R CM (i, j) ∈ Relations.toSet R CM := by
  simp [Relations.toSet]

/-! ## Serre's relations in the presented algebra -/

/-- Serre's relation `⁅Hᵢ, Hⱼ⁆ = 0`: the generators `Hᵢ` commute. -/
@[simp]
theorem lie_serreH_serreH (i j : B) : ⁅serreH R CM i, serreH R CM j⁆ = 0 := by
  have h := serreMk_eq_zero_of_mem_toSet R CM (mem_toSet_HH R CM i j)
  simp only [Relations.HH, Function.uncurry, Function.comp_apply, LieHom.map_lie] at h
  exact h

/-- Serre's relation `⁅Eᵢ, Fᵢ⁆ = Hᵢ`. -/
@[simp]
theorem lie_serreE_serreF_self (i : B) : ⁅serreE R CM i, serreF R CM i⁆ = serreH R CM i := by
  have h := serreMk_eq_zero_of_mem_toSet R CM (mem_toSet_EF R CM i i)
  have key : EF R ((i, i) : B × B) =
      ⁅FreeLieAlgebra.of R (Generators.E i), FreeLieAlgebra.of R (Generators.F i)⁆ -
        FreeLieAlgebra.of R (Generators.H i) := by
    simp [Relations.EF]
  rw [key, map_sub, LieHom.map_lie, sub_eq_zero] at h
  exact h

/-- Serre's relation `⁅Eᵢ, Fⱼ⁆ = 0` for `i ≠ j`. -/
@[simp]
theorem lie_serreE_serreF_of_ne {i j : B} (hij : i ≠ j) : ⁅serreE R CM i, serreF R CM j⁆ = 0 := by
  have h := serreMk_eq_zero_of_mem_toSet R CM (mem_toSet_EF R CM i j)
  have key : EF R ((i, j) : B × B) =
      ⁅FreeLieAlgebra.of R (Generators.E i), FreeLieAlgebra.of R (Generators.F j)⁆ := by
    simp [Relations.EF, hij]
  rw [key, LieHom.map_lie] at h
  exact h

/-- Serre's relation `⁅Hᵢ, Eⱼ⁆ = CMᵢⱼ • Eⱼ`. -/
@[simp]
theorem lie_serreH_serreE (i j : B) : ⁅serreH R CM i, serreE R CM j⁆ = CM i j • serreE R CM j := by
  have h := serreMk_eq_zero_of_mem_toSet R CM (mem_toSet_HE R CM i j)
  simp only [Relations.HE, Function.uncurry, Function.comp_apply, map_sub, LieHom.map_lie,
    map_zsmul, sub_eq_zero] at h
  exact h

/-- Serre's relation `⁅Hᵢ, Fⱼ⁆ = -(CMᵢⱼ • Fⱼ)`. -/
@[simp]
theorem lie_serreH_serreF (i j : B) :
    ⁅serreH R CM i, serreF R CM j⁆ = -(CM i j • serreF R CM j) := by
  have h := serreMk_eq_zero_of_mem_toSet R CM (mem_toSet_HF R CM i j)
  simp only [Relations.HF, Function.uncurry, Function.comp_apply, map_add, LieHom.map_lie,
    map_zsmul, add_eq_zero_iff_eq_neg] at h
  exact h

/-- The higher Serre relation on the `E`'s: `(ad Eᵢ) ^ (-CMᵢⱼ).toNat ⁅Eᵢ, Eⱼ⁆ = 0`. -/
@[simp]
theorem ad_pow_lie_serreE_serreE (i j : B) :
    (ad R (Matrix.ToLieAlgebra R CM) (serreE R CM i) ^ (-CM i j).toNat)
      ⁅serreE R CM i, serreE R CM j⁆ = 0 := by
  have h := serreMk_eq_zero_of_mem_toSet R CM (mem_toSet_adE R CM i j)
  simp only [Relations.adE, Function.uncurry, Function.comp_apply] at h
  rwa [LieHom.map_ad_pow, LieHom.map_lie] at h

/-- The higher Serre relation on the `F`'s: `(ad Fᵢ) ^ (-CMᵢⱼ).toNat ⁅Fᵢ, Fⱼ⁆ = 0`. -/
@[simp]
theorem ad_pow_lie_serreF_serreF (i j : B) :
    (ad R (Matrix.ToLieAlgebra R CM) (serreF R CM i) ^ (-CM i j).toNat)
      ⁅serreF R CM i, serreF R CM j⁆ = 0 := by
  have h := serreMk_eq_zero_of_mem_toSet R CM (mem_toSet_adF R CM i j)
  simp only [Relations.adF, Function.uncurry, Function.comp_apply] at h
  rwa [LieHom.map_ad_pow, LieHom.map_lie] at h

/-! ## Serre systems and the universal property -/

variable {L : Type*} [LieRing L] [LieAlgebra R L]

/-- Three families `H`, `E`, `F` of elements of a Lie algebra form a *Serre system* for the matrix
`CM` when they satisfy Serre's relations for `CM`. The fields are in bijection with the six
families of relators generating `CartanMatrix.Relations.toIdeal`, the `⁅E, F⁆` family being split
into its diagonal and off-diagonal halves. -/
structure IsSerreSystem (H E F : B → L) : Prop where
  /-- The `Hᵢ` commute. -/
  lie_H_H : ∀ i j, ⁅H i, H j⁆ = 0
  /-- `⁅Eᵢ, Fᵢ⁆` is `Hᵢ`. -/
  lie_E_F_self : ∀ i, ⁅E i, F i⁆ = H i
  /-- `Eᵢ` and `Fⱼ` commute for `i ≠ j`. -/
  lie_E_F_of_ne : ∀ i j, i ≠ j → ⁅E i, F j⁆ = 0
  /-- `Eⱼ` is an eigenvector of `ad Hᵢ` of eigenvalue `CMᵢⱼ`. -/
  lie_H_E : ∀ i j, ⁅H i, E j⁆ = CM i j • E j
  /-- `Fⱼ` is an eigenvector of `ad Hᵢ` of eigenvalue `-CMᵢⱼ`. -/
  lie_H_F : ∀ i j, ⁅H i, F j⁆ = -(CM i j • F j)
  /-- The higher Serre relation on the `E`'s. -/
  ad_pow_lie_E_E : ∀ i j, (ad R L (E i) ^ (-CM i j).toNat) ⁅E i, E j⁆ = 0
  /-- The higher Serre relation on the `F`'s. -/
  ad_pow_lie_F_F : ∀ i j, (ad R L (F i) ^ (-CM i j).toNat) ⁅F i, F j⁆ = 0

/-- The generators of `Matrix.ToLieAlgebra R CM` are a Serre system for `CM`. -/
theorem isSerreSystem_serre :
    IsSerreSystem R CM (serreH R CM) (serreE R CM) (serreF R CM) where
  lie_H_H := lie_serreH_serreH R CM
  lie_E_F_self := lie_serreE_serreF_self R CM
  lie_E_F_of_ne _ _ := lie_serreE_serreF_of_ne R CM
  lie_H_E := lie_serreH_serreE R CM
  lie_H_F := lie_serreH_serreF R CM
  ad_pow_lie_E_E := ad_pow_lie_serreE_serreE R CM
  ad_pow_lie_F_F := ad_pow_lie_serreF_serreF R CM

/-! ### Stability of Serre systems

Serre's relations are stable under reindexing the three families along an injective map of index
sets, provided the matrix is reindexed the same way, and under the signed exchange of the raising
and lowering families. Both are statements about an arbitrary Serre system in an arbitrary Lie
algebra; applied to the generators of the presented algebra they give its automorphisms, in
`TauCeti/Algebra/Lie/Presentation/Serre/Automorphism.lean`. -/

section Stability

variable {R CM} {H E F : B → L} {σ : Equiv.Perm B}

omit [DecidableEq B] in
/-- The image of a Serre system under a Lie algebra homomorphism is a Serre system. -/
theorem IsSerreSystem.map {L' : Type*} [LieRing L'] [LieAlgebra R L']
    (h : IsSerreSystem R CM H E F) (f : L →ₗ⁅R⁆ L') :
    IsSerreSystem R CM (f ∘ H) (f ∘ E) (f ∘ F) where
  lie_H_H i j := by
    simp only [Function.comp_apply, ← f.map_lie, h.lie_H_H i j, map_zero]
  lie_E_F_self i := by
    simp only [Function.comp_apply, ← f.map_lie, h.lie_E_F_self i]
  lie_E_F_of_ne i j hij := by
    simp only [Function.comp_apply, ← f.map_lie, h.lie_E_F_of_ne i j hij, map_zero]
  lie_H_E i j := by
    simp only [Function.comp_apply, ← f.map_lie, h.lie_H_E i j, map_zsmul]
  lie_H_F i j := by
    simp only [Function.comp_apply, ← f.map_lie, h.lie_H_F i j, map_neg, map_zsmul]
  ad_pow_lie_E_E i j := by
    simp only [Function.comp_apply, ← f.map_lie, ← LieHom.map_ad_pow,
      h.ad_pow_lie_E_E i j, map_zero]
  ad_pow_lie_F_F i j := by
    simp only [Function.comp_apply, ← f.map_lie, ← LieHom.map_ad_pow,
      h.ad_pow_lie_F_F i j, map_zero]

omit [DecidableEq B] in
/-- **A Serre system over one base ring transfers to any other base ring for which the same Lie
ring has a Lie-algebra structure.** -/
-- The other five fields are ring-independent as stated: the two eigenvector relations scale by
-- the integer entry `CM i j` through its `ℤ`-action, and the remaining three mention no scalars.
theorem IsSerreSystem.changeScalars {S : Type*} [CommRing S] [LieAlgebra S L]
    (h : IsSerreSystem R CM H E F) : IsSerreSystem S CM H E F :=
  { h with
    ad_pow_lie_E_E := fun i j => by
      rw [← TauCeti.ad_pow_apply_eq_ad_pow_apply R S]
      exact h.ad_pow_lie_E_E i j
    ad_pow_lie_F_F := fun i j => by
      rw [← TauCeti.ad_pow_apply_eq_ad_pow_apply R S]
      exact h.ad_pow_lie_F_F i j }

omit [DecidableEq B] in
/-- Reindexing a Serre system along an injective map of index sets gives a Serre system for the
matrix reindexed the same way. -/
theorem IsSerreSystem.submatrix {B' : Type*} {f : B' → B} (hf : Function.Injective f)
    (h : IsSerreSystem R CM H E F) :
    IsSerreSystem R (CM.submatrix f f) (H ∘ f) (E ∘ f) (F ∘ f) where
  lie_H_H i j := h.lie_H_H (f i) (f j)
  lie_E_F_self i := h.lie_E_F_self (f i)
  lie_E_F_of_ne i j hij := h.lie_E_F_of_ne (f i) (f j) fun hc => hij (hf hc)
  lie_H_E i j := h.lie_H_E (f i) (f j)
  lie_H_F i j := h.lie_H_F (f i) (f j)
  ad_pow_lie_E_E i j := h.ad_pow_lie_E_E (f i) (f j)
  ad_pow_lie_F_F i j := h.ad_pow_lie_F_F (f i) (f j)

omit [DecidableEq B] in
/-- Reindexing a Serre system along a permutation `σ` of the index set that preserves the matrix
gives a Serre system for the same matrix. -/
theorem IsSerreSystem.perm (h : IsSerreSystem R CM H E F) (hσ : CM.submatrix σ σ = CM) :
    IsSerreSystem R CM (H ∘ σ) (E ∘ σ) (F ∘ σ) :=
  hσ ▸ h.submatrix σ.injective

omit [DecidableEq B] in
/-- Negating the Cartan family of a Serre system and exchanging its raising and lowering families,
again with a sign, gives a Serre system for the same matrix. This is the symmetry of Serre's
relations behind the Chevalley involution. -/
theorem IsSerreSystem.neg_swap (h : IsSerreSystem R CM H E F) :
    IsSerreSystem R CM (fun i => -H i) (fun i => -F i) (fun i => -E i) where
  lie_H_H i j := by simp [h.lie_H_H i j]
  lie_E_F_self i := by
    rw [neg_lie, lie_neg, neg_neg, ← lie_skew, h.lie_E_F_self i]
  lie_E_F_of_ne i j hij := by
    rw [neg_lie, lie_neg, neg_neg, ← lie_skew, h.lie_E_F_of_ne j i (Ne.symm hij), neg_zero]
  lie_H_E i j := by rw [neg_lie, lie_neg, neg_neg, h.lie_H_F i j, smul_neg]
  lie_H_F i j := by rw [neg_lie, lie_neg, neg_neg, h.lie_H_E i j, smul_neg, neg_neg]
  ad_pow_lie_E_E i j := by
    rw [neg_lie, lie_neg, neg_neg]
    exact ad_neg_pow_apply_eq_zero (h.ad_pow_lie_F_F i j)
  ad_pow_lie_F_F i j := by
    rw [neg_lie, lie_neg, neg_neg]
    exact ad_neg_pow_apply_eq_zero (h.ad_pow_lie_E_E i j)

end Stability

/-! ### The universal property -/

variable {R CM}

omit [DecidableEq B] in
/-- The map on Serre generators determined by three families of elements of a Lie algebra. -/
private def serreGeneratorMap (H E F : B → L) : Generators B → L
  | .H i => H i
  | .E i => E i
  | .F i => F i

variable {H E F : B → L}

/-- A Serre system kills every relator, so the ideal they generate lies in the kernel of the
homomorphism the system induces on the free Lie algebra.

The six families of relators are handled one family at a time: `Set.union_subset_iff` and
`Set.range_subset_iff` reduce the containment to one statement per family, without the proof having
to know how the union in `CartanMatrix.Relations.toSet` is bracketed. -/
private theorem toIdeal_le_ker_lift (h : IsSerreSystem R CM H E F) :
    Relations.toIdeal R CM ≤ (FreeLieAlgebra.lift R (serreGeneratorMap H E F)).ker := by
  refine LieSubmodule.lieSpan_le.mpr ?_
  simp only [Relations.toSet, Set.union_subset_iff, Set.range_subset_iff, SetLike.mem_coe,
    LieHom.mem_ker, Prod.forall]
  and_intros
  · intro i j
    simpa [Relations.HH, serreGeneratorMap] using h.lie_H_H i j
  · intro i j
    rcases eq_or_ne i j with rfl | hij
    · simpa [Relations.EF, serreGeneratorMap, sub_eq_zero] using h.lie_E_F_self i
    · simpa [Relations.EF, serreGeneratorMap, hij] using h.lie_E_F_of_ne i j hij
  · intro i j
    simpa [Relations.HE, serreGeneratorMap, sub_eq_zero] using h.lie_H_E i j
  · intro i j
    simpa [Relations.HF, serreGeneratorMap, add_eq_zero_iff_eq_neg] using h.lie_H_F i j
  · intro i j
    simp only [Relations.adE, Function.uncurry, Function.comp_apply, LieHom.map_ad_pow,
      LieHom.map_lie, FreeLieAlgebra.lift_of_apply, serreGeneratorMap]
    exact h.ad_pow_lie_E_E i j
  · intro i j
    simp only [Relations.adF, Function.uncurry, Function.comp_apply, LieHom.map_ad_pow,
      LieHom.map_lie, FreeLieAlgebra.lift_of_apply, serreGeneratorMap]
    exact h.ad_pow_lie_F_F i j

/-- The homomorphism out of `Matrix.ToLieAlgebra R CM` determined by a Serre system: the universal
property of the presentation. -/
noncomputable def serreLift (h : IsSerreSystem R CM H E F) :
    Matrix.ToLieAlgebra R CM →ₗ⁅R⁆ L :=
  (Relations.toIdeal R CM).liftQ (FreeLieAlgebra.lift R (serreGeneratorMap H E F))
    (toIdeal_le_ker_lift h)

private theorem serreLift_comp_serreMk (h : IsSerreSystem R CM H E F) :
    (serreLift h).comp (serreMk R CM) = FreeLieAlgebra.lift R (serreGeneratorMap H E F) :=
  (Relations.toIdeal R CM).liftQ_mkQ _ _

/-- The homomorphism determined by a Serre system sends `Hᵢ` to `H i`. -/
@[simp]
theorem serreLift_serreH (h : IsSerreSystem R CM H E F) (i : B) :
    serreLift h (serreH R CM i) = H i := by
  rw [← serreMk_of_H R CM i]
  exact (DFunLike.congr_fun (serreLift_comp_serreMk h) _).trans
    (FreeLieAlgebra.lift_of_apply _ _)

/-- The homomorphism determined by a Serre system sends `Eᵢ` to `E i`. -/
@[simp]
theorem serreLift_serreE (h : IsSerreSystem R CM H E F) (i : B) :
    serreLift h (serreE R CM i) = E i := by
  rw [← serreMk_of_E R CM i]
  exact (DFunLike.congr_fun (serreLift_comp_serreMk h) _).trans
    (FreeLieAlgebra.lift_of_apply _ _)

/-- The homomorphism determined by a Serre system sends `Fᵢ` to `F i`. -/
@[simp]
theorem serreLift_serreF (h : IsSerreSystem R CM H E F) (i : B) :
    serreLift h (serreF R CM i) = F i := by
  rw [← serreMk_of_F R CM i]
  exact (DFunLike.congr_fun (serreLift_comp_serreMk h) _).trans
    (FreeLieAlgebra.lift_of_apply _ _)

/-- A nonzero Cartan element in a Serre system has a nonzero preimage among the presented Cartan
generators. -/
theorem serreH_ne_zero (h : IsSerreSystem R CM H E F) {i : B} (hi : H i ≠ 0) :
    serreH R CM i ≠ 0 := fun hzero =>
  hi <| by rw [← serreLift_serreH h i, hzero, map_zero]

/-- A nonzero raising element in a Serre system has a nonzero preimage among the presented raising
generators. -/
theorem serreE_ne_zero (h : IsSerreSystem R CM H E F) {i : B} (hi : E i ≠ 0) :
    serreE R CM i ≠ 0 := fun hzero =>
  hi <| by rw [← serreLift_serreE h i, hzero, map_zero]

/-- A nonzero lowering element in a Serre system has a nonzero preimage among the presented
lowering generators. -/
theorem serreF_ne_zero (h : IsSerreSystem R CM H E F) {i : B} (hi : F i ≠ 0) :
    serreF R CM i ≠ 0 := fun hzero =>
  hi <| by rw [← serreLift_serreF h i, hzero, map_zero]

/-- Linear independence of the Cartan family of a Serre system lifts to the presented Cartan
generators. -/
theorem linearIndependent_serreH (h : IsSerreSystem R CM H E F)
    (hH : LinearIndependent R H) : LinearIndependent R (serreH R CM) := by
  refine LinearIndependent.of_comp (serreLift h).toLinearMap ?_
  have : ⇑(serreLift h).toLinearMap ∘ serreH R CM = H :=
    funext fun i => serreLift_serreH h i
  rwa [this]

/-- Two homomorphisms out of `Matrix.ToLieAlgebra R CM` agreeing on the generators are equal. -/
@[ext]
theorem serre_hom_ext {g₁ g₂ : Matrix.ToLieAlgebra R CM →ₗ⁅R⁆ L}
    (hH : ∀ i, g₁ (serreH R CM i) = g₂ (serreH R CM i))
    (hE : ∀ i, g₁ (serreE R CM i) = g₂ (serreE R CM i))
    (hF : ∀ i, g₁ (serreF R CM i) = g₂ (serreF R CM i)) : g₁ = g₂ := by
  have hcomp : g₁.comp (serreMk R CM) = g₂.comp (serreMk R CM) := by
    refine FreeLieAlgebra.hom_ext fun g => ?_
    cases g with
    | H i => exact hH i
    | E i => exact hE i
    | F i => exact hF i
  refine (Relations.toIdeal R CM).lieHom_qext fun x => ?_
  exact congrArg (fun ψ : FreeLieAlgebra R (Generators B) →ₗ⁅R⁆ L => ψ x) hcomp

/-- Two equivalences out of `Matrix.ToLieAlgebra R CM` agreeing on the generators are equal. -/
@[ext]
theorem serre_equiv_ext {g₁ g₂ : Matrix.ToLieAlgebra R CM ≃ₗ⁅R⁆ L}
    (hH : ∀ i, g₁ (serreH R CM i) = g₂ (serreH R CM i))
    (hE : ∀ i, g₁ (serreE R CM i) = g₂ (serreE R CM i))
    (hF : ∀ i, g₁ (serreF R CM i) = g₂ (serreF R CM i)) : g₁ = g₂ :=
  LieEquiv.ext fun x =>
    DFunLike.congr_fun (serre_hom_ext (g₁ := g₁.toLieHom) (g₂ := g₂.toLieHom) hH hE hF) x

/-- `TauCeti.serreLift` is the unique homomorphism sending the generators to a given Serre
system. -/
theorem eq_serreLift {h : IsSerreSystem R CM H E F} {g : Matrix.ToLieAlgebra R CM →ₗ⁅R⁆ L}
    (hH : ∀ i, g (serreH R CM i) = H i) (hE : ∀ i, g (serreE R CM i) = E i)
    (hF : ∀ i, g (serreF R CM i) = F i) : g = serreLift h :=
  serre_hom_ext (fun i => by rw [hH, serreLift_serreH]) (fun i => by rw [hE, serreLift_serreE])
    fun i => by rw [hF, serreLift_serreF]

/-- A Serre system whose raising and lowering families generate the ambient Lie algebra presents
it: the homomorphism it determines is surjective. -/
theorem serreLift_surjective (h : IsSerreSystem R CM H E F)
    (hspan : LieSubalgebra.lieSpan R L (Set.range E ∪ Set.range F) = ⊤) :
    Function.Surjective (serreLift h) := by
  rw [← LieHom.range_eq_top, eq_top_iff, ← hspan, LieSubalgebra.lieSpan_le]
  rintro _ (⟨i, rfl⟩ | ⟨i, rfl⟩)
  · exact ⟨serreE R CM i, serreLift_serreE h i⟩
  · exact ⟨serreF R CM i, serreLift_serreF h i⟩

variable (R CM)

/-- Lifting the generators of `Matrix.ToLieAlgebra R CM` along their own Serre system returns the
identity. -/
@[simp]
theorem serreLift_eq_id :
    serreLift (isSerreSystem_serre R CM) = LieHom.id :=
  serre_hom_ext (fun i => by simp) (fun i => by simp) fun i => by simp

/-- The generators `TauCeti.serreH`, `TauCeti.serreE` and `TauCeti.serreF` generate
`Matrix.ToLieAlgebra R CM` as a Lie subalgebra. -/
theorem lieSpan_serreGenerators_eq_top :
    LieSubalgebra.lieSpan R (Matrix.ToLieAlgebra R CM)
        (Set.range (serreH R CM) ∪ Set.range (serreE R CM) ∪ Set.range (serreF R CM)) = ⊤ := by
  set K := LieSubalgebra.lieSpan R (Matrix.ToLieAlgebra R CM)
    (Set.range (serreH R CM) ∪ Set.range (serreE R CM) ∪ Set.range (serreF R CM))
  have hgen : ∀ g : Generators B, serreMk R CM (FreeLieAlgebra.of R g) ∈ K := by
    rintro (i | i | i) <;> refine LieSubalgebra.subset_lieSpan ?_
    · exact Or.inl (Or.inl ⟨i, rfl⟩)
    · exact Or.inl (Or.inr ⟨i, rfl⟩)
    · exact Or.inr ⟨i, rfl⟩
  have hle : LieSubalgebra.lieSpan R (FreeLieAlgebra R (Generators B))
      (Set.range (FreeLieAlgebra.of R)) ≤ K.comap (serreMk R CM) := by
    refine LieSubalgebra.lieSpan_le.mpr ?_
    rintro _ ⟨g, rfl⟩
    exact hgen g
  refine eq_top_iff.2 fun y _ => ?_
  obtain ⟨x, rfl⟩ := serreMk_surjective R CM y
  exact hle (by rw [FreeLieAlgebra.lieSpan_range_of_eq_top]; trivial)

/-- The raising and lowering generators of `Matrix.ToLieAlgebra R CM` generate it: the Cartan
generators are their brackets `Hᵢ = ⁅Eᵢ, Fᵢ⁆`. -/
theorem lieSpan_serreE_union_serreF_eq_top :
    LieSubalgebra.lieSpan R (Matrix.ToLieAlgebra R CM)
      (Set.range (serreE R CM) ∪ Set.range (serreF R CM)) = ⊤ := by
  rw [eq_top_iff, ← lieSpan_serreGenerators_eq_top R CM, LieSubalgebra.lieSpan_le]
  rintro _ ((⟨i, rfl⟩ | ⟨i, rfl⟩) | ⟨i, rfl⟩)
  · rw [← lie_serreE_serreF_self R CM i]
    exact LieSubalgebra.lie_mem _ (LieSubalgebra.subset_lieSpan (Or.inl ⟨i, rfl⟩))
      (LieSubalgebra.subset_lieSpan (Or.inr ⟨i, rfl⟩))
  · exact LieSubalgebra.subset_lieSpan (Or.inl ⟨i, rfl⟩)
  · exact LieSubalgebra.subset_lieSpan (Or.inr ⟨i, rfl⟩)

end TauCeti
