/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.KnotTheory.BraidWord.PDCode

/-!
# Free cancellation in braid words

The word presentation of a braid has the elementary free relation
`σ i ^ ε σ i ^ (-ε) = 1`.  This file records the relation on words, its closure under
insertion and deletion, and the invariants that the relation preserves.  The relation is the
word-level prerequisite for the second Reidemeister move on braid closures.

The diagrammatic statement that a closure changes by a Reidemeister move is deliberately left to
the consumer: it must identify the two newly created crossings with the corresponding clasp in the
PD-code.  The present API isolates the list and group calculation that that construction uses.

## Main declarations

* `TauCeti.BraidWord.FreeCancelStep`: insertion or deletion of one adjacent inverse pair.
* `TauCeti.BraidWord.FreeCancelEquiv`: the equivalence relation generated by those steps.
* `TauCeti.BraidWord.toBraid_freeCancel` and `writhe_closure_freeCancel`: invariance of the
  represented braid and closure writhe under one step.

## References

* J. Birman, *Braids, Links, and Mapping Class Groups*, Annals of Mathematics Studies 82 (1974),
  Chapter 1.
* W. B. R. Lickorish, *An Introduction to Knot Theory*, Springer GTM 175 (1997), Chapter 1.
-/

public section

namespace TauCeti

namespace BraidWord

open BraidGroup

variable {n : ℕ}

/-- One free-cancellation step inserts or deletes adjacent inverse letters in a braid word. -/
inductive FreeCancelStep : BraidWord n → BraidWord n → Prop
  | insert (u v : BraidWord n) (i : Fin (n - 1)) (ε : ℤˣ) :
      FreeCancelStep (u ++ v) (u ++ [(i, ε), (i, -ε)] ++ v)
  | delete (u v : BraidWord n) (i : Fin (n - 1)) (ε : ℤˣ) :
      FreeCancelStep (u ++ [(i, ε), (i, -ε)] ++ v) (u ++ v)

/-- The equivalence relation generated by free insertion and deletion of inverse pairs. -/
def FreeCancelEquiv : BraidWord n → BraidWord n → Prop := Relation.EqvGen FreeCancelStep

namespace FreeCancelEquiv

/-- Free-cancellation equivalence is reflexive. -/
@[refl]
theorem refl (w : BraidWord n) : FreeCancelEquiv w w := Relation.EqvGen.refl _

/-- Free-cancellation equivalence is symmetric. -/
@[symm]
theorem symm {w w' : BraidWord n} (h : FreeCancelEquiv w w') : FreeCancelEquiv w' w :=
  Relation.EqvGen.symm _ _ h

/-- Free-cancellation equivalence is transitive. -/
@[trans]
theorem trans {w w' w'' : BraidWord n} (h : FreeCancelEquiv w w')
    (h' : FreeCancelEquiv w' w'') : FreeCancelEquiv w w'' :=
  Relation.EqvGen.trans _ _ _ h h'

/-- A single free-cancellation step is a free-cancellation equivalence. -/
theorem of_step {w w' : BraidWord n} (h : FreeCancelStep w w') : FreeCancelEquiv w w' :=
  Relation.EqvGen.rel _ _ h

end FreeCancelEquiv

private theorem toBraid_insert (u v : BraidWord n) (i : Fin (n - 1)) (ε : ℤˣ) :
    toBraid (u ++ [(i, ε), (i, -ε)] ++ v) = toBraid (u ++ v) := by
  rw [toBraid_append, toBraid_append, toBraid_append, toBraid_cons, toBraid_cons, toBraid_nil,
    mul_one]
  change u.toBraid * (sigma i ^ (ε : ℤ) * sigma i ^ ((-ε : ℤˣ) : ℤ)) * v.toBraid = _
  rw [Units.val_neg]
  rw [zpow_neg]
  simp

/-- A free-cancellation step does not change the braid represented by a word. -/
theorem toBraid_freeCancel {w w' : BraidWord n} (h : FreeCancelStep w w') :
    toBraid w = toBraid w' := by
  cases h with
  | insert u v i ε => exact (toBraid_insert u v i ε).symm
  | delete u v i ε => exact toBraid_insert u v i ε

/-- Free-cancellation equivalence preserves the represented braid. -/
theorem toBraid_freeCancelEquiv {w w' : BraidWord n} (h : FreeCancelEquiv w w') :
    toBraid w = toBraid w' := by
  induction h with
  | rel _ _ h => exact toBraid_freeCancel h
  | refl => rfl
  | symm _ _ _ ih => exact ih.symm
  | trans _ _ _ _ _ ih₁ ih₂ => exact ih₁.trans ih₂

/-- Inserting a free-cancelled pair adds two crossings. -/
theorem length_freeCancel_insert (u v : BraidWord n) (i : Fin (n - 1)) (ε : ℤˣ) :
    (u ++ [(i, ε), (i, -ε)] ++ v).length = (u ++ v).length + 2 := by
  simp [List.length_append]
  omega

/-- The two letters inserted by a free cancellation have opposite signs. -/
theorem sum_signs_freeCancel_insert (u v : BraidWord n) (i : Fin (n - 1)) (ε : ℤˣ) :
    Multiplicative.ofAdd (((u ++ [(i, ε), (i, -ε)] ++ v).map fun x ↦ (x.2 : ℤ)).sum) =
      Multiplicative.ofAdd (((u ++ v).map fun x ↦ (x.2 : ℤ)).sum) := by
  simp [List.sum_append]

/-- The closure writhe is unchanged by one free-cancellation step. -/
theorem writhe_closure_freeCancel {w w' : BraidWord n} (h : FreeCancelStep w w') :
    w.closure.writhe = w'.closure.writhe := by
  rw [writhe_closure, writhe_closure]
  exact congrArg (Multiplicative.toAdd ∘ ArtinGroup.exponentSum _) (toBraid_freeCancel h)

/-- The closure writhe is invariant under the equivalence generated by free cancellations. -/
theorem writhe_closure_freeCancelEquiv {w w' : BraidWord n} (h : FreeCancelEquiv w w') :
    w.closure.writhe = w'.closure.writhe := by
  induction h with
  | rel _ _ h => exact writhe_closure_freeCancel h
  | refl => rfl
  | symm _ _ _ ih => exact ih.symm
  | trans _ _ _ _ _ ih₁ ih₂ => exact ih₁.trans ih₂

end BraidWord

end TauCeti
