/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Geometry.Lie.Exponential.Smoothness
public import TauCeti.Geometry.Lie.RightInvariantVectorField
import TauCeti.Geometry.Lie.Interior
import TauCeti.Geometry.Manifold.ContMDiff.Prod

/-!
# Derivative of the Lie-group exponential

Let `center = extChartAt I 1 1` and let `F` be the tangent-space exponential written in the
extended chart at the identity. Smoothness of the exponential makes `F` differentiable at zero.
Along each line `t ↦ t • v`, the scaling law identifies `F` with the coordinate expression of
the canonical integral curve generated by `v`. Its initial velocity is `v`, so `F` has derivative
the identity at zero; equivalently, `F(v) = F(0) + v + o(‖v‖)`. The same integral-curve
calculation supplies reusable chain rules for functions along translated exponential lines.

## Main results

* `hasFDerivAt_extChartAt_mulInvariantExp_zero`: in model-space identity coordinates, the
  tangent-space exponential has derivative the identity at zero.
* `hasFDerivAt_extChartAt_lieExp_zero`: the identity-chart derivative of the derivation-based
  exponential is the canonical linear isometry to the model space.
* `hasFDerivAt_extChartAt_mulInvariantExp_smul_mul_mulInvariantExp_smul`: two exponential
  lines multiplied together have initial coordinate derivative `X + Y`.
* `contMDiff_mulInvariantExp_smul`: an exponential line is smooth.
* `contMDiff_mulInvariantExp_smul_mul_mul_mulInvariantExp_smul`: two exponential lines multiplied
  around a fixed group element give a smooth two-parameter map.
* `hasMFDerivAt_mulInvariantExp_smul_zero`: an exponential line has its generator as initial
  velocity.
* `hasMFDerivAt_mulInvariantExp_smul`: at every time, an exponential line's velocity is its
  generating left-invariant vector field at the current point.
* `HasMFDerivAt.hasDerivAt_comp_mulInvariantExp_smul_zero`: the chain rule along an exponential
  line at zero.
* `HasMFDerivAt.hasDerivAt_comp_mul_mulInvariantExp_smul_zero`: the chain rule after left
  translation at zero.
* `HasMFDerivAt.hasDerivAt_comp_mulInvariantExp_smul_mul_zero`: the chain rule after right
  translation at zero.

-/

public section

open Function Manifold
open scoped ContDiff Manifold Topology

noncomputable section

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
  {F : Type*} [NormedAddCommGroup F] [NormedSpace ℝ F]
  {H : Type*} [TopologicalSpace H] {I : ModelWithCorners ℝ E H}
  {G : Type*} [TopologicalSpace G] [ChartedSpace H G] [Group G]

attribute [local instance] LieGroup.minSmoothnessThree

section ExponentialLine

variable [CompleteSpace E]

section Smoothness

variable [LieGroup I ∞ G]

local instance exponentialLineContMDiffMulOne : ContMDiffMul I 1 G :=
  ContMDiffMul.of_le (m := 1) (n := ∞) (by norm_num)

local instance exponentialLineBoundarylessManifold : BoundarylessManifold I G :=
  ContMDiffMul.boundarylessManifold

/-- The exponential line generated by `X` is smooth. -/
theorem contMDiff_mulInvariantExp_smul (X : GroupLieAlgebra I G) :
    let _ : T2Space G := t2Space_of_lieGroup (I := I) (n := ∞)
    ContMDiff 𝓘(ℝ, ℝ) I ∞
      (fun t : ℝ => mulInvariantExp (I := I) (G := G) (t • X)) := by
  let _ : T2Space G := t2Space_of_lieGroup (I := I) (n := ∞)
  dsimp only
  simpa only [mulInvariantOneParameterSubgroup_eq_mulInvariantExp_smul] using
    contMDiff_mulInvariantOneParameterSubgroup (I := I) (G := G) X

/-- Two exponential lines multiplied around a fixed group element give a smooth two-parameter
map. -/
theorem contMDiff_mulInvariantExp_smul_mul_mul_mulInvariantExp_smul
    (g : G) (X Y : GroupLieAlgebra I G) :
    let _ : T2Space G := t2Space_of_lieGroup (I := I) (n := ∞)
    ContMDiff 𝓘(ℝ, ℝ × ℝ) I ∞ (fun p : ℝ × ℝ =>
      mulInvariantExp (I := I) (G := G) (p.1 • X) * g *
        mulInvariantExp (I := I) (G := G) (p.2 • Y)) := by
  let _ : T2Space G := t2Space_of_lieGroup (I := I) (n := ∞)
  dsimp only
  have hX := contMDiff_mulInvariantExp_smul (I := I) (G := G) X
  have hY := contMDiff_mulInvariantExp_smul (I := I) (G := G) Y
  have hprod : ContMDiff (𝓘(ℝ, ℝ).prod 𝓘(ℝ, ℝ)) I ∞ (fun p : ℝ × ℝ =>
      mulInvariantExp (I := I) (G := G) (p.1 • X) * g *
        mulInvariantExp (I := I) (G := G) (p.2 • Y)) :=
    ((hX.comp contMDiff_fst).mul contMDiff_const).mul (hY.comp contMDiff_snd)
  exact (contMDiff_prod_modelWithCornersSelf_iff (I' := I)).mp hprod

end Smoothness

section Derivative

variable [LieGroup I (minSmoothness ℝ 3) G] [IsManifold I 1 G] [T2Space G]
  [BoundarylessManifold I G]

/-- At time `t`, an exponential line has velocity the left-invariant vector field generated by `X`,
evaluated at the point `mulInvariantExp (t • X)` reached by the line. -/
theorem hasMFDerivAt_mulInvariantExp_smul (X : GroupLieAlgebra I G) (t : ℝ) :
    HasMFDerivAt 𝓘(ℝ, ℝ) I
      (fun s : ℝ => mulInvariantExp (I := I) (G := G) (s • X)) t
      ((1 : ℝ →L[ℝ] ℝ).smulRight
        (mulInvariantVectorField X
          (mulInvariantExp (I := I) (G := G) (t • X)))) := by
  have hcurve := isMIntegralCurve_mulInvariantIntegralCurve
    (I := I) (G := G) X (1 : G) t
  have hfun : (fun s : ℝ => mulInvariantExp (I := I) (G := G) (s • X)) =
      mulInvariantIntegralCurve (I := I) (G := G) X 1 := by
    funext s
    rw [mulInvariantExp_smul]
  rw [hfun, mulInvariantExp_smul]
  exact hcurve

/-- The exponential line generated by `X` has initial velocity `X`. -/
theorem hasMFDerivAt_mulInvariantExp_smul_zero (X : GroupLieAlgebra I G) :
    HasMFDerivAt 𝓘(ℝ, ℝ) I
      (fun t : ℝ => mulInvariantExp (I := I) (G := G) (t • X)) 0
      ((1 : ℝ →L[ℝ] ℝ).smulRight X) := by
  have h := hasMFDerivAt_mulInvariantExp_smul (I := I) (G := G) X 0
  rw [zero_smul, mulInvariantExp_zero, mulInvariantVectorField_one] at h
  exact h

/-- Differentiating a function that is manifold-differentiable at the identity along an exponential
line gives its directional derivative there. -/
theorem HasMFDerivAt.hasDerivAt_comp_mulInvariantExp_smul_zero {f : G → F}
    {f' : TangentSpace I (1 : G) →L[ℝ] F}
    (hf : HasMFDerivAt I 𝓘(ℝ, F) f 1 f') (X : GroupLieAlgebra I G) :
    HasDerivAt (fun t : ℝ => f (mulInvariantExp (I := I) (G := G) (t • X))) (f' X) 0 := by
  -- `HasMFDerivAt.comp` expects function composition, while the statement uses application.
  change HasDerivAt
    (f ∘ fun t : ℝ => mulInvariantExp (I := I) (G := G) (t • X)) (f' X) 0
  have hf0 : HasMFDerivAt I 𝓘(ℝ, F) f
      (mulInvariantExp (I := I) (G := G) ((0 : ℝ) • X)) f' := by
    rw [zero_smul, mulInvariantExp_zero]
    exact hf
  have hcomp := hf0.comp 0 (hasMFDerivAt_mulInvariantExp_smul_zero (I := I) (G := G) X)
  have hF : HasFDerivAt (f ∘ fun t : ℝ => mulInvariantExp (I := I) (G := G) (t • X))
      (f'.comp ((1 : ℝ →L[ℝ] ℝ).smulRight X)) 0 := hcomp.hasFDerivAt
  simpa only [ContinuousLinearMap.comp_apply,
    ContinuousLinearMap.smulRight_apply, one_apply_eq_self, one_smul] using hF.hasDerivAt

/-- Differentiating a function after left multiplication along an exponential line gives
its left-invariant directional derivative. -/
theorem HasMFDerivAt.hasDerivAt_comp_mul_mulInvariantExp_smul_zero {f : G → F} {g : G}
    {f' : TangentSpace I g →L[ℝ] F} (hf : HasMFDerivAt I 𝓘(ℝ, F) f g f')
    (Y : GroupLieAlgebra I G) :
    HasDerivAt
      (fun t : ℝ => f (g * mulInvariantExp (I := I) (G := G) (t • Y)))
      (f' (mulInvariantVectorField Y g)) 0 := by
  have hmul := (contMDiffAt_mul_left
      (I := I) (n := minSmoothness ℝ 3) (a := g) (b := (1 : G)))
    |>.mdifferentiableAt (by simp) |>.hasMFDerivAt
  have hfg : HasMFDerivAt I 𝓘(ℝ, F) f (g * 1) f' := by
    rw [mul_one]
    exact hf
  have hcomp := hfg.comp 1 hmul
  have h := HasMFDerivAt.hasDerivAt_comp_mulInvariantExp_smul_zero hcomp Y
  simp only [Function.comp_apply] at h
  simp only [mulInvariantVectorField]
  convert h using 1
  exact ContinuousLinearMap.comp_apply _ _ _

/-- Differentiating a function after right multiplication along an exponential line gives
its right-invariant directional derivative. -/
theorem HasMFDerivAt.hasDerivAt_comp_mulInvariantExp_smul_mul_zero {f : G → F} {g : G}
    {f' : TangentSpace I g →L[ℝ] F} (hf : HasMFDerivAt I 𝓘(ℝ, F) f g f')
    (X : GroupLieAlgebra I G) :
    HasDerivAt
      (fun t : ℝ => f (mulInvariantExp (I := I) (G := G) (t • X) * g))
      (f' (mulRightInvariantVectorField X g)) 0 := by
  have hmul := (contMDiffAt_mul_right
      (I := I) (n := minSmoothness ℝ 3) (a := g) (b := (1 : G)))
    |>.mdifferentiableAt (by simp) |>.hasMFDerivAt
  have hfg : HasMFDerivAt I 𝓘(ℝ, F) f (1 * g) f' := by
    rw [one_mul]
    exact hf
  have hcomp := hfg.comp 1 hmul
  have h := HasMFDerivAt.hasDerivAt_comp_mulInvariantExp_smul_zero hcomp X
  rw [mulRightInvariantVectorField_apply]
  simp only [Function.comp_apply] at h
  convert h using 1
  exact ContinuousLinearMap.comp_apply _ _ _

end Derivative

end ExponentialLine

/-- **In identity coordinates the exponential along a ray is the integral curve of its
direction.** -/
private theorem extChartAt_mulInvariantExp_smul_eq [CompleteSpace E]
    [LieGroup I (minSmoothness ℝ 3) G] [T2Space G] [BoundarylessManifold I G] (v : E) :
    (fun t : ℝ => extChartAt I (1 : G)
        (mulInvariantExp (I := I) (G := G) (((t • v : E) : GroupLieAlgebra I G)))) =
      (extChartAt I (1 : G)) ∘
        mulInvariantIntegralCurve (I := I) (G := G) (v : GroupLieAlgebra I G) 1 := by
  funext t
  simp only [Function.comp_apply]
  apply congrArg (extChartAt I (1 : G))
  have hsmul : ((t • v : E) : GroupLieAlgebra I G) = t • (v : GroupLieAlgebra I G) :=
    (groupLieAlgebraEquivModelVectorSpace (I := I) (G := G)).symm.map_smul t v
  rw [hsmul]
  exact mulInvariantExp_smul (I := I) (G := G) (v : GroupLieAlgebra I G) t

/-- **In model-space identity coordinates, the tangent-space exponential is differentiable at
zero.** -/
private theorem differentiableAt_extChartAt_mulInvariantExp_zero [FiniteDimensional ℝ E]
    [LieGroup I ∞ G] [T2Space G] [BoundarylessManifold I G] :
    DifferentiableAt ℝ (fun v : E => extChartAt I (1 : G)
      (mulInvariantExp (I := I) (G := G) (v : GroupLieAlgebra I G))) 0 := by
  have hsource : mulInvariantExp (I := I) (G := G)
      (0 : GroupLieAlgebra I G) ∈ (chartAt H (1 : G)).source := by
    rw [mulInvariantExp_zero]
    exact mem_chart_source H (1 : G)
  have hsmoothCoord := (contMDiffAt_iff_target_of_mem_source
    (f := fun v : E => mulInvariantExp (I := I) (G := G)
      (v : GroupLieAlgebra I G)) (y := (1 : G)) hsource).mp
    (contMDiffAt_mulInvariantExp_modelSpace_zero (I := I) (G := G))
  exact (hsmoothCoord.2.mdifferentiableAt (by simp)).differentiableAt

/-- In model-space identity coordinates, the tangent-space exponential has derivative the identity
at zero. -/
theorem hasFDerivAt_extChartAt_mulInvariantExp_zero
    [FiniteDimensional ℝ E] [LieGroup I ∞ G] [T2Space G] [BoundarylessManifold I G] :
    HasFDerivAt
      (fun v : E => extChartAt I (1 : G)
        (mulInvariantExp (I := I) (G := G) (v : GroupLieAlgebra I G)))
      (ContinuousLinearMap.id ℝ E) 0 := by
  let _ : CompleteSpace E := FiniteDimensional.complete ℝ E
  have hFdiff := differentiableAt_extChartAt_mulInvariantExp_zero (I := I) (G := G)
  apply hFdiff.hasFDerivAt.congr_fderiv
  apply ContinuousLinearMap.ext
  intro v
  have hscale : HasDerivAt (fun t : ℝ => t • v) v 0 := by
    simpa using ((hasDerivAt_id (𝕜 := ℝ) (0 : ℝ)).smul_const v)
  have hline := hFdiff.hasFDerivAt.comp_hasDerivAt_of_eq 0 hscale (by simp)
  have hlineCurve : HasDerivAt (fun t : ℝ => extChartAt I (1 : G)
      (mulInvariantExp (I := I) (G := G) (((t • v : E) : GroupLieAlgebra I G)))) v 0 := by
    rw [extChartAt_mulInvariantExp_smul_eq v]
    exact hasDerivAt_extChartAt_mulInvariantIntegralCurve_zero (I := I) (G := G) v
  exact hline.unique hlineCurve

/-- In identity-chart coordinates, the derivative of the derivation-based Lie exponential at zero
is the canonical linear isometry from left-invariant derivations to the model space. -/
theorem hasFDerivAt_extChartAt_lieExp_zero
    [FiniteDimensional ℝ E] [LieGroup I ∞ G] [T2Space G] [BoundarylessManifold I G] :
    HasFDerivAt
      (fun X : LeftInvariantDerivation I G => extChartAt I (1 : G) (lieExp X))
      (leftInvariantDerivationLinearIsometryEquivModelVectorSpace
        (I := I) (G := G)).toContinuousLinearEquiv.toContinuousLinearMap 0 := by
  let L := leftInvariantDerivationLinearIsometryEquivModelVectorSpace
    (I := I) (G := G)
  have hmodel := hasFDerivAt_extChartAt_mulInvariantExp_zero (I := I) (G := G)
  have hmodelAt : HasFDerivAt
      (fun v : E => extChartAt I (1 : G)
        (mulInvariantExp (I := I) (G := G) (v : GroupLieAlgebra I G)))
      (ContinuousLinearMap.id ℝ E) (L 0) := by
    simpa using hmodel
  have hcomp := hmodelAt.comp 0 L.toContinuousLinearEquiv.hasFDerivAt
  have hfun :
      (fun X : LeftInvariantDerivation I G => extChartAt I (1 : G) (lieExp X)) =
        (fun v : E => extChartAt I (1 : G)
          (mulInvariantExp (I := I) (G := G) (v : GroupLieAlgebra I G))) ∘ L := by
    funext X
    apply congrArg (extChartAt I (1 : G))
    rw [lieExp_eq_mulInvariantExp]
    simp only [L, leftInvariantDerivationLinearIsometryEquivModelVectorSpace_apply]
  rw [hfun]
  simpa only [ContinuousLinearMap.id_comp] using hcomp

/-- In identity-chart coordinates, the product of the exponential lines generated by `X` and
`Y` has initial derivative `X + Y`. -/
theorem hasFDerivAt_extChartAt_mulInvariantExp_smul_mul_mulInvariantExp_smul
    [FiniteDimensional ℝ E]
    [LieGroup I ∞ G] [T2Space G] [BoundarylessManifold I G]
    (X Y : GroupLieAlgebra I G) :
    HasFDerivAt
      (fun t : ℝ => extChartAt I (1 : G)
        (mulInvariantExp (I := I) (G := G) (t • X) *
          mulInvariantExp (I := I) (G := G) (t • Y)))
      ((1 : ℝ →L[ℝ] ℝ).smulRight ((show E from X) + (show E from Y))) 0 := by
  let _ : CompleteSpace E := FiniteDimensional.complete ℝ E
  have hX := hasMFDerivAt_mulInvariantExp_smul_zero (I := I) (G := G) X
  have hY := hasMFDerivAt_mulInvariantExp_smul_zero (I := I) (G := G) Y
  have hpair := hX.prodMk hY
  have hmul := (contMDiff_mul (G := G) I ∞).contMDiffAt
    (x := (mulInvariantExp (I := I) (G := G) ((0 : ℝ) • X),
      mulInvariantExp (I := I) (G := G) ((0 : ℝ) • Y)))
    |>.mdifferentiableAt (by simp)
  have hcurve := hmul.hasMFDerivAt.comp 0 hpair
  have hzero :
      mulInvariantExp (I := I) (G := G) ((0 : ℝ) • X) *
        mulInvariantExp (I := I) (G := G) ((0 : ℝ) • Y) = (1 : G) := by
    simp
  rw [hzero] at hcurve
  have hsource :
      mulInvariantExp (I := I) (G := G) ((0 : ℝ) • X) *
          mulInvariantExp (I := I) (G := G) ((0 : ℝ) • Y) ∈
        (chartAt H (1 : G)).source := by
    rw [hzero]
    exact mem_chart_source H (1 : G)
  have hext := (mdifferentiableAt_extChartAt (I := I)
    (x := (1 : G)) hsource).hasMFDerivAt
  have hchart := hext.comp 0 hcurve
  simp only [Function.comp_apply] at hchart
  rw [hzero] at hchart
  apply hchart.mdifferentiableAt.differentiableAt.hasFDerivAt.congr_fderiv
  rw [← mfderiv_eq_fderiv, hchart.mfderiv]
  apply DFunLike.coe_injective
  funext t
  rw [show (0 : ℝ) • X = 0 by exact zero_smul ℝ X,
    show (0 : ℝ) • Y = 0 by exact zero_smul ℝ Y,
    mulInvariantExp_zero]
  have hmul_apply := mfderiv_mul_apply_one (I := I) (G := G) (t • X) (t • Y)
  have hmul_model := congrArg (fun Z : GroupLieAlgebra I G => show E from Z)
    (hmul_apply.trans (smul_add t X Y).symm)
  rw [mfderiv_extChartAt_self]
  -- `extChartAt` lands in the self-model, whose tangent space is the model-space synonym `E`.
  -- Expose that final chart boundary before applying the model-space equality above.
  change
    (show E from
      (mfderiv (I.prod I) I (fun p : G × G => p.1 * p.2) ((1, 1) : G × G))
        (t • X, t • Y)) =
      (show E from t • (X + Y))
  exact hmul_model
