/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.AlgebraicGroup.GeneralLinear.UpperTriangular.Basic
public import TauCeti.Algebra.AlgebraicGroup.Smooth.CommHopfAlgCat
public import TauCeti.Algebra.AlgebraicGroup.Solvable.Basic
public import TauCeti.Algebra.AlgebraicGroup.SpecialLinear.Smooth
import TauCeti.LinearAlgebra.Matrix.GeneralLinearGroup.UpperTriangular.Solvable
import TauCeti.LinearAlgebra.Matrix.SpecialLinearGroup.Lift

/-!
# The upper-triangular subgroup scheme of `SLₙ`

The matrix coordinates strictly below the diagonal generate a Hopf ideal in `O(SLₙ)`: it is the
image of the upper-triangular Hopf ideal of `GLₙ` under the determinant-one quotient. Its quotient
represents the upper-triangular determinant-one matrices: over every commutative algebra `A`,
the points cut out by this ideal are the matrices of `SLₙ(A)` that are upper triangular in
`GLₙ(A)`.

This closed subgroup is smooth over every commutative ring, because upper-triangular
determinant-one matrices lift across nilpotent thickenings, and its geometric points form a
solvable group. These are inputs for identifying it as a Borel subgroup of `SLₙ`.

## Main declarations

* `TauCeti.SpecialLinear.UpperTriangular.definingHopfIdeal`: the upper-triangular Hopf ideal in
  `O(SLₙ)`.
* `TauCeti.SpecialLinear.UpperTriangular.definingHopfIdeal_toIdeal`: it is generated by the
  coordinates strictly below the diagonal.
* `TauCeti.SpecialLinear.UpperTriangular.mem_definingPointsSubgroup_iff`: a point lies in the
  closed subgroup exactly when its matrix is upper triangular.
* `TauCeti.SpecialLinear.UpperTriangular.pointsMulEquiv`: the points of the quotient Hopf algebra
  are the upper-triangular determinant-one matrices.
* `TauCeti.SpecialLinear.UpperTriangular.instSmoothCoordinateHopfAlgebra`: smoothness over every
  commutative ring.
* `TauCeti.SpecialLinear.UpperTriangular.
    geometricallySolvablePointsCommHopfAlgProperty_coordinateHopfAlgebra`:
  solvability of the geometric points.

## References

* J. S. Milne, *Algebraic Groups* (2017), Chapters 12 and 21.
* The construction generalizes the rank-two subgroup
  `TauCeti.Algebra.AlgebraicGroup.SpecialLinear.Borel.Basic` and follows the general-linear
  subgroup `TauCeti.Algebra.AlgebraicGroup.GeneralLinear.UpperTriangular.Basic`.
-/

public section

open CategoryTheory WithConv

namespace TauCeti.SpecialLinear.UpperTriangular

universe u w w'

variable (R : Type u) [CommRing R] (n : ℕ)

/-- The Hopf ideal cutting out upper-triangular matrices inside `SLₙ`: the image of the
general-linear upper-triangular Hopf ideal under the determinant-one quotient map. -/
noncomputable def definingHopfIdeal : HopfIdeal R (SpecialLinear.coordinateHopfAlgebra R n) :=
  (GeneralLinear.UpperTriangular.definingHopfIdeal R n).map (SpecialLinear.coordinateMap R n).hom

/-- The special-linear upper-triangular ideal is the image of the general-linear one. -/
theorem definingHopfIdeal_def :
    definingHopfIdeal R n =
      (GeneralLinear.UpperTriangular.definingHopfIdeal R n).map
        (SpecialLinear.coordinateMap R n).hom :=
  by rw [definingHopfIdeal]

/-- The underlying ideal of the upper-triangular Hopf ideal of `SLₙ` is generated by the images of
the matrix coordinates strictly below the diagonal. -/
theorem definingHopfIdeal_toIdeal :
    (definingHopfIdeal R n).toIdeal =
      Ideal.span ((SpecialLinear.coordinateMap R n).hom ''
        GeneralLinear.UpperTriangular.definingRelationSet R n) := by
  rw [definingHopfIdeal, HopfIdeal.map_toIdeal,
    GeneralLinear.UpperTriangular.definingHopfIdeal_toIdeal, Ideal.map_span]
  rfl

/-- The upper-triangular Hopf ideal of `SLₙ` is finitely generated as an ideal. -/
theorem definingHopfIdeal_toIdeal_fg : (definingHopfIdeal R n).toIdeal.FG := by
  rw [definingHopfIdeal_toIdeal]
  refine Submodule.fg_span (Set.Finite.image _ ?_)
  refine (Set.finite_range fun p : Fin n × Fin n ↦
    GeneralLinear.coordinateHopfAlgebraAlgEquiv R n
      (GeneralLinear.coordinateRingMap R n (MvPolynomial.X p))).subset ?_
  intro x hx
  obtain ⟨i, j, -, rfl⟩ := (GeneralLinear.UpperTriangular.mem_definingRelationSet_iff R n x).mp hx
  exact ⟨(i, j), rfl⟩

/-- The coordinate Hopf algebra of the upper-triangular closed subgroup scheme of `SLₙ`. -/
noncomputable abbrev coordinateHopfAlgebra : _root_.CommHopfAlgCat.{u} R :=
  CommHopfAlgCat.quotient (SpecialLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n)

/-- The quotient coordinate morphism from `O(SLₙ)` to the upper-triangular coordinate Hopf
algebra. -/
noncomputable abbrev coordinateMap :
    SpecialLinear.coordinateHopfAlgebra R n ⟶ coordinateHopfAlgebra R n :=
  CommHopfAlgCat.mkQuotient (SpecialLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n)

section Points

variable {A : Type w} [CommRing A] [Algebra R A]

/-- An `SLₙ`-point belongs to the upper-triangular closed subgroup exactly when its matrix is
upper triangular. -/
@[simp↓]
theorem mem_definingPointsSubgroup_iff
    (g : HopfAlgebra.points (R := R) (H := SpecialLinear.coordinateHopfAlgebra R n)
      (CommAlgCat.of R A)) :
    g ∈ CommHopfAlgCat.quotientPointsSubgroup
        (SpecialLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n)
        (CommAlgCat.of R A) ↔
      Matrix.SpecialLinearGroup.toGL (SpecialLinear.pointsMulEquiv (R := R) (A := A) n g) ∈
        upperTriangularGroup (Fin n) A := by
  rw [definingHopfIdeal_def,
    CommHopfAlgCat.mem_quotientPointsSubgroup_map_iff (SpecialLinear.coordinateMap R n),
    GeneralLinear.UpperTriangular.mem_definingPointsSubgroup_iff,
    CommHopfAlgCat.mapPointsFunctor_app_apply,
    ← CommHopfAlgCat.quotientPointsHom_apply
      (GeneralLinear.coordinateHopfAlgebra R n) (SpecialLinear.definingHopfIdeal R n)
      (CommAlgCat.of R A) g,
    SpecialLinear.pointsMulEquiv_toGL]

/-- The point subgroup cut out by the upper-triangular Hopf ideal is the subgroup of
upper-triangular determinant-one matrices. -/
private noncomputable def definingPointsSubgroupMulEquiv :
    CommHopfAlgCat.quotientPointsSubgroup
        (SpecialLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n)
        (CommAlgCat.of R A) ≃*
      (upperTriangularGroup (Fin n) A).comap Matrix.SpecialLinearGroup.toGL :=
  Subgroup.congrOfMapEq (SpecialLinear.pointsMulEquiv (R := R) (A := A) n) <| by
    ext g
    rw [← (SpecialLinear.pointsMulEquiv (R := R) (A := A) n).toMonoidHom_eq_coe,
      Subgroup.mem_map_equiv, mem_definingPointsSubgroup_iff, MulEquiv.apply_symm_apply,
      Subgroup.mem_comap]

/-- The group of algebra-valued points of the upper-triangular coordinate Hopf algebra of `SLₙ`
is the group of upper-triangular determinant-one matrices. -/
noncomputable def pointsMulEquiv :
    HopfAlgebra.points (R := R) (H := coordinateHopfAlgebra R n) (CommAlgCat.of R A) ≃*
      (upperTriangularGroup (Fin n) A).comap Matrix.SpecialLinearGroup.toGL :=
  ((CommHopfAlgCat.quotientPointsSubgroupNatIso
      (SpecialLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n)).app
      (CommAlgCat.of R A)).groupIsoToMulEquiv.trans
    (definingPointsSubgroupMulEquiv R n)

/-- Under the upper-triangular and special-linear point equivalences, the quotient-point
inclusion is the ordinary inclusion of upper-triangular matrices into `SLₙ`. -/
@[simp↓]
theorem pointsMulEquiv_coe
    (f : HopfAlgebra.points (R := R) (H := coordinateHopfAlgebra R n) (CommAlgCat.of R A)) :
    SpecialLinear.pointsMulEquiv (R := R) (A := A) n
        (CommHopfAlgCat.quotientPointsHom
          (SpecialLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n)
          (CommAlgCat.of R A) f) =
      (pointsMulEquiv R n (A := A) f : Matrix.SpecialLinearGroup (Fin n) A) := by
  have hcomponent := CommHopfAlgCat.quotientPointsSubgroupNatIso_hom_app_apply
    (SpecialLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n) (CommAlgCat.of R A) f
  calc
    _ = SpecialLinear.pointsMulEquiv (R := R) (A := A) n
          (((CommHopfAlgCat.quotientPointsSubgroupNatIso
            (SpecialLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n)).app
            (CommAlgCat.of R A)).hom f).1 :=
      (congrArg
        (fun g ↦ SpecialLinear.pointsMulEquiv (R := R) (A := A) n g.1) hcomponent).symm
    _ = _ := (Subgroup.coe_congrOfMapEq_apply _ _ _).symm

/-- The ambient point attached to an upper-triangular determinant-one matrix is the
special-linear point attached to that matrix. -/
@[simp↓]
theorem quotientPointsHom_pointsMulEquiv_symm
    (g : (upperTriangularGroup (Fin n) A).comap Matrix.SpecialLinearGroup.toGL) :
    CommHopfAlgCat.quotientPointsHom
        (SpecialLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n)
        (CommAlgCat.of R A) ((pointsMulEquiv R n (A := A)).symm g) =
      (SpecialLinear.pointsMulEquiv (R := R) (A := A) n).symm g.1 := by
  apply (SpecialLinear.pointsMulEquiv (R := R) (A := A) n).injective
  rw [pointsMulEquiv_coe, MulEquiv.apply_symm_apply, MulEquiv.apply_symm_apply]

variable {B : Type w'} [CommRing B] [Algebra R B]

/-- The upper-triangular point equivalence of `SLₙ` is natural in the value algebra:
postcomposition of points agrees with entrywise mapping of matrices. -/
@[simp↓]
theorem pointsMulEquiv_mapValue (phi : A →ₐ[R] B)
    (f : HopfAlgebra.points (R := R) (H := coordinateHopfAlgebra R n) (CommAlgCat.of R A)) :
    (pointsMulEquiv R n (A := B) (AlgHom.mapValue (H := coordinateHopfAlgebra R n) phi f) :
        Matrix.SpecialLinearGroup (Fin n) B) =
      Matrix.SpecialLinearGroup.map phi.toRingHom (pointsMulEquiv R n (A := A) f) := by
  rw [← pointsMulEquiv_coe, ← CommHopfAlgCat.mapValue_quotientPointsHom,
    SpecialLinear.pointsMulEquiv_mapValue, pointsMulEquiv_coe]

/-- Every algebra-valued point group of the upper-triangular subgroup of `SLₙ` is solvable. -/
theorem isSolvable_points :
    Group.IsSolvable
      (HopfAlgebra.points (R := R) (H := coordinateHopfAlgebra R n) (CommAlgCat.of R A)) := by
  let toUpper : (upperTriangularGroup (Fin n) A).comap Matrix.SpecialLinearGroup.toGL →*
      upperTriangularGroup (Fin n) A :=
    (Matrix.SpecialLinearGroup.toGL.comp (Subgroup.subtype _)).codRestrict _ fun g ↦ g.2
  have htoUpper : Function.Injective toUpper := fun g h hgh ↦
    Subtype.ext (Matrix.SpecialLinearGroup.toGL_injective (congrArg Subtype.val hgh))
  exact Group.isSolvable_of_isSolvable_injective
    (f := toUpper.comp (pointsMulEquiv R n (A := A)).toMonoidHom)
    (htoUpper.comp (pointsMulEquiv R n (A := A)).injective)

end Points

/-- The upper-triangular subgroup of `SLₙ` has a solvable group of geometric points. -/
theorem geometricallySolvablePointsCommHopfAlgProperty_coordinateHopfAlgebra
    (k : Type u) [Field k] :
    geometricallySolvablePointsCommHopfAlgProperty k (coordinateHopfAlgebra k n) := by
  rw [geometricallySolvablePointsCommHopfAlgProperty_iff]
  exact isSolvable_points k n

/-- The upper-triangular coordinate algebra of `SLₙ` is formally smooth: upper-triangular
determinant-one matrices lift through square-zero quotients. -/
private instance instFormallySmoothCoordinateHopfAlgebra :
    Algebra.FormallySmooth R (coordinateHopfAlgebra R n) := by
  apply Algebra.FormallySmooth.of_comp_surjective
  intro B _ _ I hI f
  let g := pointsMulEquiv R n (A := B ⧸ I) (toConv f)
  obtain ⟨N, hNupper, hN⟩ :=
    Matrix.SpecialLinearGroup.exists_isUpperTriangular_map_eq_of_isNilpotent I ⟨2, hI⟩ g.1
      (UpperTriangularGroup.mem_comap_toGL_iff.mp g.2)
  let lift : WithConv (coordinateHopfAlgebra R n →ₐ[R] B) :=
    (pointsMulEquiv R n (A := B)).symm ⟨N, UpperTriangularGroup.mem_comap_toGL_iff.mpr hNupper⟩
  refine ⟨lift.ofConv, ?_⟩
  apply toConv_injective
  apply (pointsMulEquiv R n (A := B ⧸ I)).injective
  apply Subtype.ext
  rw [← AlgHom.mapValue_apply, pointsMulEquiv_mapValue, Ideal.Quotient.mkₐ_toRingHom]
  simpa only [lift, MulEquiv.apply_symm_apply] using hN

/-- **The upper-triangular subgroup of `SLₙ` is smooth over every commutative ring.** -/
instance instSmoothCoordinateHopfAlgebra : Algebra.Smooth R (coordinateHopfAlgebra R n) := by
  let _ : Algebra.FinitePresentation R (coordinateHopfAlgebra R n) :=
    Algebra.FinitePresentation.quotient (definingHopfIdeal_toIdeal_fg R n)
  exact ⟨inferInstance, inferInstance⟩

/-- The upper-triangular coordinate Hopf algebra of `SLₙ` is smooth over a field. -/
theorem smoothCommHopfAlgProperty_coordinateHopfAlgebra (k : Type u) [Field k] :
    smoothCommHopfAlgProperty k (coordinateHopfAlgebra k n) := by
  rw [smoothCommHopfAlgProperty_iff]
  infer_instance

end TauCeti.SpecialLinear.UpperTriangular
