/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.RingTheory.SimpleModule.Basic
public import TauCeti.Algebra.Lie.Submodule.Atom
public import TauCeti.Algebra.Lie.UniversalEnveloping.Basic

/-!
# The enveloping-algebra dictionary for Lie modules

A module over a Lie algebra `L` is the same data as a module over its universal enveloping algebra
`U(L)`. This file makes that dictionary explicit and, more importantly, extends it to the
structures built on top of a module: Lie submodules are exactly `U(L)`-submodules, and Lie module
homomorphisms are exactly `U(L)`-linear maps.

The two translations of the underlying data are immediate from Mathlib. In one direction the
representation `TauCeti.UniversalEnvelopingAlgebra.representation` supplies a `U(L)`-module
structure by restriction of scalars. In the other direction `LieRingModule.compLieHom` composes the
canonical Lie map `UniversalEnvelopingAlgebra.ι` with the commutator action of an associative
algebra on a module over it.

The dictionary for submodules and homomorphisms is not immediate: it rests on `U(L)` being
generated as an `R`-algebra by the canonical Lie generators
(`TauCeti.UniversalEnvelopingAlgebra.induction_ι`), so that an `R`-submodule stable under the
bracket is automatically stable under all of `U(L)`, and likewise an `R`-linear map commuting with
the bracket is `U(L)`-linear. Everything here is therefore available over an arbitrary commutative
ring, with no Poincaré--Birkhoff--Witt hypothesis.

The dictionary is stated for an *arbitrary* `U(L)`-module structure compatible with the bracket
(the hypothesis `hcompat : ∀ x m, ι R x • m = ⁅x, m⁆`), not only for the one manufactured by
`TauCeti.UniversalEnvelopingAlgebra.asModule`. That is what lets a module produced as a
`U(L)`-module elsewhere — a quotient of `U(L)` by a left ideal is the motivating example — be read
as a Lie module without transporting it along an equivalence first.

This is the `U(L)` analogue of Mathlib's dictionary between representations of a group `G` and
modules over its group algebra `k[G]`, in `Mathlib/RepresentationTheory/`; the correspondence
below is named after its counterparts there wherever one exists.

## Main definitions

* `TauCeti.UniversalEnvelopingAlgebra.asModule`: the `U(L)`-module structure on a Lie module, the
  analogue of `Representation.asModule`. A `def`, not an `instance`, since a global instance would
  compete with the restriction-of-scalars paths already present.
* `TauCeti.UniversalEnvelopingAlgebra.asLieRingModule` and
  `TauCeti.UniversalEnvelopingAlgebra.asLieModule`: the Lie module structure on a `U(L)`-module,
  the converse translation.
* `TauCeti.UniversalEnvelopingAlgebra.lieSubmoduleOrderIso`: **the dictionary for submodules**, an
  order isomorphism between the Lie submodules of `M` and its `U(L)`-submodules; the analogue of
  `Representation.mapSubmodule`.
* `TauCeti.UniversalEnvelopingAlgebra.lieSubmoduleOrderIsoAsModule`: that order isomorphism at the
  canonical structure `TauCeti.UniversalEnvelopingAlgebra.asModule`.
* `TauCeti.UniversalEnvelopingAlgebra.lieModuleHomEquiv`: **the dictionary for homomorphisms**, an
  `R`-linear equivalence between Lie module homomorphisms and `U(L)`-linear maps.
* `TauCeti.UniversalEnvelopingAlgebra.lieModuleEquivEquivLinearEquiv`: the corresponding
  dictionary from Lie-module equivalences to `U(L)`-linear equivalences.
* `TauCeti.UniversalEnvelopingAlgebra.lieSubmoduleLinearEquiv`: the identity equivalence between a
  Lie submodule and its image under an arbitrary compatible submodule dictionary.

## Main results

* `TauCeti.UniversalEnvelopingAlgebra.smul_mem_of_forall_ι_smul_mem`: an `R`-submodule stable under
  the canonical Lie generators is stable under the whole enveloping algebra; the analogue of
  `Representation.asAlgebraHom_mem_of_forall_mem`.
* `TauCeti.UniversalEnvelopingAlgebra.map_smul_of_map_ι_smul`: an `R`-linear map equivariant for
  the canonical Lie generators is `U(L)`-linear.
* `TauCeti.UniversalEnvelopingAlgebra.lieSubmoduleOrderIso_lieSpan`: the Lie submodule generated by
  a set is its `U(L)`-span.
* `TauCeti.UniversalEnvelopingAlgebra.isIrreducible_iff_isSimpleModule`: irreducibility of a Lie
  module is simplicity of the corresponding `U(L)`-module.
* `TauCeti.UniversalEnvelopingAlgebra.complementedLattice_lieSubmodule_iff_isSemisimpleModule`:
  complete reducibility of a Lie module is semisimplicity of the corresponding `U(L)`-module.

## Roadmap

This is the pinned enveloping-algebra dictionary (`asModule`, `lieSubmoduleOrderIso`) of the
decomposition toolkit in Layer 6 of
`TauCetiRoadmap/RepresentationTheory/LieHighestWeight/README.md`, which asks that the Lie-level
isotypic notions consume Mathlib's ring-level machinery in `Mathlib/RingTheory/SimpleModule/`
through this dictionary rather than duplicate it. The converse translation
`TauCeti.UniversalEnvelopingAlgebra.asLieRingModule` is what Layer 3 needs in order to read a
module manufactured as a quotient of `U(L)` as a Lie module.

## References

* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, Chapter V, §17.
* N. Bourbaki, *Lie Groups and Lie Algebras*, Chapter I, §2.
* `Mathlib/RepresentationTheory/Basic.lean` (Antoine Labelle) and
  `Mathlib/RepresentationTheory/Submodule.lean` (Oliver Nash): the group-algebra dictionary
  `Representation.asAlgebraHom`, `Representation.asModule`,
  `Representation.asAlgebraHom_mem_of_forall_mem` and `Representation.mapSubmodule`, which this
  file follows for `U(L)` in place of `k[G]`.
* `Mathlib/RepresentationTheory/Intertwining.lean` (Stepan Nesterov, Edison Xie):
  `Representation.IntertwiningMap.equivLinearMapAsModule`, the group-algebra homomorphism
  dictionary that `lieModuleHomEquiv` follows.
* `Mathlib/RepresentationTheory/Irreducible.lean` and
  `Mathlib/RepresentationTheory/Semisimple.lean` (Stepan Nesterov): the source of the pattern by
  which the two corollaries below compose an order isomorphism of submodule lattices with
  `isSimpleModule_iff` and `isSemisimpleModule_iff`.
-/

public section

open UniversalEnvelopingAlgebra

universe u v w x

namespace TauCeti.UniversalEnvelopingAlgebra

variable (R : Type u) (L : Type v) (M : Type w) (N : Type x)
variable [CommRing R] [LieRing L] [LieAlgebra R L]
variable [AddCommGroup M] [Module R M] [AddCommGroup N] [Module R N]

local notation "U" => _root_.UniversalEnvelopingAlgebra R L

attribute [local instance 100] LieRing.ofAssociativeRing

/-! ### From a Lie module to a module over the enveloping algebra -/

section OfLieModule

variable [LieRingModule L M] [LieModule R L M]

/-- **The enveloping-algebra module structure** on a Lie module, by restriction of scalars along
`TauCeti.UniversalEnvelopingAlgebra.representation`. This is the `U(L)` analogue of Mathlib's
`Representation.asModule`, carried by `M` itself rather than by a type synonym.

This is a `def` rather than an `instance`: a global instance would compete with the
restriction-of-scalars paths that a module already carries, and the dictionary below is stated for
an arbitrary compatible `U(L)`-module structure, of which this is one. -/
@[instance_reducible]
noncomputable def asModule : Module U M :=
  Module.compHom M (representation R L M).toRingHom

attribute [local instance] asModule

-- The parenthesised proofs here and below keep the definitional step inside this module, so the
-- characterising lemmas are the whole interface and the bodies stay unexposed.
/-- The scalar action of `TauCeti.UniversalEnvelopingAlgebra.asModule` is evaluation of
`TauCeti.UniversalEnvelopingAlgebra.representation`. -/
theorem asModule_smul_def (u : U) (m : M) :
    u • m = representation R L M u m :=
  (rfl)

-- Not a `simp` lemma: `simp` rewrites `UniversalEnvelopingAlgebra.ι` on the left-hand side into
-- the tensor-algebra presentation, exactly as for Mathlib's own `lift_ι_apply`. The simp-normal
-- form is `asModule_ι_smul'` below.
/-- The canonical Lie generators act through `TauCeti.UniversalEnvelopingAlgebra.asModule` by the
Lie bracket. This is the compatibility hypothesis that the dictionary below consumes. -/
theorem asModule_ι_smul (x : L) (m : M) :
    (ι R x : U) • m = ⁅x, m⁆ :=
  (representation_ι_apply R L M x m)

/-- The `simp`-normal form of `TauCeti.UniversalEnvelopingAlgebra.asModule_ι_smul`, stated for the
canonical generators as `simp` writes them. -/
@[simp]
theorem asModule_ι_smul' (x : L) (m : M) :
    (mkAlgHom R L (TensorAlgebra.ι R x) : U) • m = ⁅x, m⁆ := by
  rw [← _root_.UniversalEnvelopingAlgebra.ι_apply]
  exact asModule_ι_smul R L M x m

/-- The scalars of `TauCeti.UniversalEnvelopingAlgebra.asModule` extend those of `R`, since
`TauCeti.UniversalEnvelopingAlgebra.representation` is an `R`-algebra homomorphism. -/
theorem isScalarTower_asModule :
    IsScalarTower R U M where
  smul_assoc r u m := by
    simp only [asModule_smul_def, map_smul, LinearMap.smul_apply]

end OfLieModule

/-! ### From a module over the enveloping algebra to a Lie module -/

section OfModule

variable [Module (_root_.UniversalEnvelopingAlgebra R L) M]

attribute [local instance] LieRingModule.ofAssociativeModule

/-- **The Lie module structure on a `U(L)`-module**, obtained by composing the canonical Lie map
`UniversalEnvelopingAlgebra.ι` with the commutator action of `U(L)` on `M`.

This cannot be an instance: the base ring `R` is not determined by the conclusion. -/
@[instance_reducible]
def asLieRingModule : LieRingModule L M :=
  LieRingModule.compLieHom M (ι R)

omit [Module R M] in
/-- The bracket of `TauCeti.UniversalEnvelopingAlgebra.asLieRingModule` is the action of the
canonical Lie generator. -/
theorem asLieRingModule_bracket (x : L) (m : M) :
    letI := asLieRingModule R L M
    ⁅x, m⁆ = (ι R x : U) • m :=
  (rfl)

/-- The bracket of `TauCeti.UniversalEnvelopingAlgebra.asLieRingModule` is `R`-bilinear, so a
`U(L)`-module whose scalars extend those of `R` is a Lie module over `R`. -/
theorem asLieModule [IsScalarTower R U M] :
    letI := asLieRingModule R L M
    LieModule R L M :=
  letI := LieModule.ofAssociativeModule (R := R)
    (A := U) (M := M)
  (LieModule.compLieHom M (ι R))

end OfModule

/-! ### The dictionary for submodules and homomorphisms -/

section Dictionary

variable {R L M N}
variable [Module (_root_.UniversalEnvelopingAlgebra R L) M]
variable [IsScalarTower R (_root_.UniversalEnvelopingAlgebra R L) M]

/-- **An `R`-submodule stable under the canonical Lie generators is stable under the whole
enveloping algebra.** The elements of `U(L)` that preserve the submodule form an `R`-subalgebra,
and it contains the generators, which generate `U(L)`. This is the `U(L)` analogue of
`Representation.asAlgebraHom_mem_of_forall_mem`. -/
theorem smul_mem_of_forall_ι_smul_mem {P : Submodule R M}
    (hP : ∀ (x : L) (m : M), m ∈ P → ι R x • m ∈ P)
    (u : U) (m : M) (hm : m ∈ P) : u • m ∈ P := by
  revert m
  induction u using induction_ι with
  | ι x => exact hP x
  | algebraMap r =>
    intro m hm
    rw [algebraMap_smul]
    exact P.smul_mem r hm
  | add u v hu hv =>
    intro m hm
    rw [add_smul]
    exact P.add_mem (hu m hm) (hv m hm)
  | mul u v hu hv =>
    intro m hm
    rw [mul_smul]
    exact hu _ (hv m hm)

variable [LieRingModule L M]

/-- **The enveloping-algebra dictionary for submodules.** For a `U(L)`-module structure on `M`
compatible with the `R`-structure and with the Lie action, the Lie submodules of `M` are exactly
its `U(L)`-submodules, and the correspondence is the identity on underlying sets. This is the
`U(L)` analogue of `Representation.mapSubmodule`, and the route from the ring-level module theory
of `Mathlib/RingTheory/SimpleModule/` to Lie modules.

The `coe_`/`mem_` lemmas below are the whole interface: nothing downstream unfolds the body. -/
def lieSubmoduleOrderIso
    (hcompat : ∀ (x : L) (m : M), ι R x • m = ⁅x, m⁆) :
    LieSubmodule R L M ≃o Submodule U M where
  toFun P :=
    { carrier := P
      zero_mem' := P.zero_mem
      add_mem' := fun ha hb => P.add_mem ha hb
      smul_mem' := fun u _ hm =>
        smul_mem_of_forall_ι_smul_mem
          (fun x m hm => by rw [hcompat]; exact P.lie_mem hm) u _ hm }
  invFun Q :=
    { toSubmodule := Q.restrictScalars R
      lie_mem := fun {x _} hm => by rw [← hcompat]; exact Q.smul_mem _ hm }
  left_inv _ := SetLike.coe_injective rfl
  right_inv _ := SetLike.coe_injective rfl
  map_rel_iff' := Iff.rfl

@[simp]
theorem coe_lieSubmoduleOrderIso
    (hcompat : ∀ (x : L) (m : M), ι R x • m = ⁅x, m⁆)
    (P : LieSubmodule R L M) :
    (lieSubmoduleOrderIso hcompat P : Set M) = P :=
  (rfl)

@[simp]
theorem mem_lieSubmoduleOrderIso
    (hcompat : ∀ (x : L) (m : M), ι R x • m = ⁅x, m⁆)
    {P : LieSubmodule R L M} {m : M} :
    m ∈ lieSubmoduleOrderIso hcompat P ↔ m ∈ P :=
  (Iff.rfl)

@[simp]
theorem coe_lieSubmoduleOrderIso_symm
    (hcompat : ∀ (x : L) (m : M), ι R x • m = ⁅x, m⁆)
    (Q : Submodule U M) :
    (((lieSubmoduleOrderIso hcompat).symm Q : LieSubmodule R L M) : Set M) = Q :=
  (rfl)

@[simp]
theorem mem_lieSubmoduleOrderIso_symm
    (hcompat : ∀ (x : L) (m : M), ι R x • m = ⁅x, m⁆)
    {Q : Submodule U M} {m : M} :
    m ∈ (lieSubmoduleOrderIso hcompat).symm Q ↔ m ∈ Q :=
  (Iff.rfl)

/-- **The dictionary carries generated submodules to generated submodules**: the Lie submodule
generated by a set is its `U(L)`-span. In particular a Lie module is generated by a vector exactly
when that vector generates it as a `U(L)`-module, which is how a highest weight vector is checked
to generate its module. -/
theorem lieSubmoduleOrderIso_lieSpan
    (hcompat : ∀ (x : L) (m : M), ι R x • m = ⁅x, m⁆) (S : Set M) :
    lieSubmoduleOrderIso hcompat (LieSubmodule.lieSpan R L S) = Submodule.span U S := by
  have h : LieSubmodule.lieSpan R L S ≤
      (lieSubmoduleOrderIso hcompat).symm (Submodule.span U S) :=
    LieSubmodule.lieSpan_le.2 fun n hn =>
      (mem_lieSubmoduleOrderIso_symm hcompat).2 (Submodule.subset_span hn)
  exact le_antisymm ((lieSubmoduleOrderIso hcompat).le_symm_apply.1 h)
    (Submodule.span_le.2 fun m hm =>
      (mem_lieSubmoduleOrderIso hcompat).2 (LieSubmodule.subset_lieSpan hm))

/-- **Irreducibility of a Lie module is simplicity over the enveloping algebra.** -/
theorem isIrreducible_iff_isSimpleModule
    (hcompat : ∀ (x : L) (m : M), ι R x • m = ⁅x, m⁆) :
    IsSimpleOrder (LieSubmodule R L M) ↔ IsSimpleModule U M :=
  (lieSubmoduleOrderIso hcompat).isSimpleOrder_iff.trans (isSimpleModule_iff U M).symm

/-- A Lie submodule is irreducible exactly when its image under a compatible enveloping-algebra
submodule dictionary is simple. -/
theorem isSimpleModule_lieSubmoduleOrderIso_iff
    (hcompat : ∀ (x : L) (m : M), ι R x • m = ⁅x, m⁆)
    (P : LieSubmodule R L M) :
    IsSimpleModule U (lieSubmoduleOrderIso hcompat P) ↔ LieModule.IsIrreducible R L P :=
  isSimpleModule_iff_isAtom.trans <|
    ((lieSubmoduleOrderIso hcompat).isAtom_iff P).trans
      (TauCeti.isIrreducible_iff_isAtom P).symm

/-- **Complete reducibility is semisimplicity over the enveloping algebra**: every Lie submodule of
`M` has a complement exactly when `M` is a semisimple `U(L)`-module. -/
theorem complementedLattice_lieSubmodule_iff_isSemisimpleModule
    (hcompat : ∀ (x : L) (m : M), ι R x • m = ⁅x, m⁆) :
    ComplementedLattice (LieSubmodule R L M) ↔ IsSemisimpleModule U M :=
  (lieSubmoduleOrderIso hcompat).complementedLattice_iff.trans
    (isSemisimpleModule_iff U M).symm

section Hom

-- `[LieModule R L N]` is what carries Mathlib's `Module R (M →ₗ⁅R,L⁆ N)` instance
-- (`Mathlib/Algebra/Lie/Basic.lean`), so the `R`-linear equivalence below cannot be stated
-- without it. No such assumption on `M` is needed, and none is made.
variable [LieRingModule L N] [LieModule R L N]
variable [Module (_root_.UniversalEnvelopingAlgebra R L) N]
variable [IsScalarTower R (_root_.UniversalEnvelopingAlgebra R L) N]

omit [LieRingModule L M] [LieRingModule L N] [LieModule R L N] in
/-- **An `R`-linear map equivariant for the canonical Lie generators is `U(L)`-linear.** As in
`TauCeti.UniversalEnvelopingAlgebra.smul_mem_of_forall_ι_smul_mem`, the elements of `U(L)` over
which the map is equivariant form an `R`-subalgebra containing the generators. -/
theorem map_smul_of_map_ι_smul (f : M →ₗ[R] N)
    (hf : ∀ (x : L) (m : M), f (ι R x • m) = ι R x • f m)
    (u : U) (m : M) :
    f (u • m) = u • f m := by
  revert m
  induction u using induction_ι with
  | ι x => exact hf x
  | algebraMap r =>
    intro m
    rw [algebraMap_smul, algebraMap_smul, map_smul]
  | add u v hu hv =>
    intro m
    rw [add_smul, add_smul, map_add, hu, hv]
  | mul u v hu hv =>
    intro m
    rw [mul_smul, mul_smul, hu, hv]

/-- **The enveloping-algebra dictionary for homomorphisms**: Lie module homomorphisms `M → N` are
exactly `U(L)`-linear maps, by the identity on underlying functions, `R`-linearly in the
homomorphism. As for `TauCeti.UniversalEnvelopingAlgebra.lieSubmoduleOrderIso`, the `coe_` lemmas
below are the whole interface. -/
def lieModuleHomEquiv
    (hM : ∀ (x : L) (m : M), ι R x • m = ⁅x, m⁆)
    (hN : ∀ (x : L) (n : N), ι R x • n = ⁅x, n⁆) :
    (M →ₗ⁅R,L⁆ N) ≃ₗ[R] (M →ₗ[U] N) where
  toFun f :=
    { toFun := f
      map_add' := f.map_add
      map_smul' := fun u m =>
        map_smul_of_map_ι_smul (f : M →ₗ[R] N)
          (fun x m => by rw [hM, hN]; exact f.map_lie x m) u m }
  map_add' _ _ := rfl
  map_smul' _ _ := rfl
  invFun g :=
    { toFun := g
      map_add' := g.map_add
      map_smul' := fun r m => by
        have h : (algebraMap R U r) • m = r • m :=
          algebraMap_smul _ r m
        rw [← h, map_smul, algebraMap_smul, RingHom.id_apply]
      map_lie' := fun {x m} => by rw [← hM, map_smul, hN] }
  left_inv _ := rfl
  right_inv _ := rfl

@[simp]
theorem coe_lieModuleHomEquiv
    (hM : ∀ (x : L) (m : M), ι R x • m = ⁅x, m⁆)
    (hN : ∀ (x : L) (n : N), ι R x • n = ⁅x, n⁆) (f : M →ₗ⁅R,L⁆ N) :
    ⇑(lieModuleHomEquiv hM hN f) = ⇑f :=
  (rfl)

@[simp]
theorem coe_lieModuleHomEquiv_symm
    (hM : ∀ (x : L) (m : M), ι R x • m = ⁅x, m⁆)
    (hN : ∀ (x : L) (n : N), ι R x • n = ⁅x, n⁆)
    (g : M →ₗ[U] N) :
    ⇑((lieModuleHomEquiv hM hN).symm g) = ⇑g :=
  (rfl)

/-! #### Equivalences -/

section Equiv

/-- **The enveloping-algebra dictionary for equivalences**: Lie module equivalences are exactly
`U(L)`-linear equivalences when both actions are compatible with the canonical Lie generators.
The correspondence is the identity on underlying functions. -/
def lieModuleEquivEquivLinearEquiv
    (hM : ∀ (x : L) (m : M), ι R x • m = ⁅x, m⁆)
    (hN : ∀ (x : L) (n : N), ι R x • n = ⁅x, n⁆) :
    (M ≃ₗ⁅R,L⁆ N) ≃ (M ≃ₗ[U] N) where
  toFun e :=
    { lieModuleHomEquiv hM hN e.toLieModuleHom with
      invFun := e.symm
      left_inv := e.left_inv
      right_inv := e.right_inv }
  invFun e :=
    { (lieModuleHomEquiv hM hN).symm e.toLinearMap with
      invFun := e.symm
      left_inv := e.left_inv
      right_inv := e.right_inv }
  left_inv _ := rfl
  right_inv _ := rfl

/-- The forward equivalence dictionary does not change the underlying function. -/
@[simp]
theorem coe_lieModuleEquivEquivLinearEquiv
    (hM : ∀ (x : L) (m : M), ι R x • m = ⁅x, m⁆)
    (hN : ∀ (x : L) (n : N), ι R x • n = ⁅x, n⁆)
    (e : M ≃ₗ⁅R,L⁆ N) :
    ⇑(lieModuleEquivEquivLinearEquiv (R := R) (L := L) (M := M) (N := N) hM hN e) = ⇑e :=
  (rfl)

/-- The inverse of the forward equivalence dictionary is the original inverse function. -/
@[simp]
theorem coe_lieModuleEquivEquivLinearEquiv_apply_symm
    (hM : ∀ (x : L) (m : M), ι R x • m = ⁅x, m⁆)
    (hN : ∀ (x : L) (n : N), ι R x • n = ⁅x, n⁆)
    (e : M ≃ₗ⁅R,L⁆ N) :
    ⇑(lieModuleEquivEquivLinearEquiv (R := R) (L := L) (M := M) (N := N) hM hN e).symm =
      ⇑e.symm :=
  (rfl)

/-- The inverse equivalence dictionary does not change the underlying function. -/
@[simp]
theorem coe_lieModuleEquivEquivLinearEquiv_symm
    (hM : ∀ (x : L) (m : M), ι R x • m = ⁅x, m⁆)
    (hN : ∀ (x : L) (n : N), ι R x • n = ⁅x, n⁆)
    (e : M ≃ₗ[U] N) :
    ⇑((lieModuleEquivEquivLinearEquiv (R := R) (L := L) (M := M) (N := N) hM hN).symm e) =
      ⇑e :=
  (rfl)

/-- The inverse of the backward equivalence dictionary is the original inverse function. -/
@[simp]
theorem coe_lieModuleEquivEquivLinearEquiv_symm_apply_symm
    (hM : ∀ (x : L) (m : M), ι R x • m = ⁅x, m⁆)
    (hN : ∀ (x : L) (n : N), ι R x • n = ⁅x, n⁆)
    (e : M ≃ₗ[U] N) :
    ⇑((lieModuleEquivEquivLinearEquiv (R := R) (L := L) (M := M) (N := N) hM hN).symm e).symm =
      ⇑e.symm :=
  (rfl)

end Equiv

end Hom

/-! #### Submodule equivalences -/

/-- A compatible enveloping-algebra action on a Lie submodule agrees, after inclusion, with the
action on the ambient Lie module. -/
theorem coe_smul_of_ι_smul
    [LieModule R L M]
    (hM : ∀ (x : L) (m : M), ι R x • m = ⁅x, m⁆)
    (P : LieSubmodule R L M) (u : U) (p : P) :
    letI := asModule R L P
    ((u • p : P) : M) = u • (p : M) := by
  let : Module U P := asModule R L P
  let : IsScalarTower R U P := isScalarTower_asModule R L P
  exact map_smul_of_map_ι_smul (R := R) (L := L) (M := P) (N := M) P.subtype
    (fun x p => by rw [asModule_ι_smul R L P, hM]; exact P.incl.map_lie x p) u p

/-- A Lie submodule with its canonical `U(L)`-action is linearly equivalent, by the identity map,
to its image under an arbitrary compatible enveloping-algebra submodule dictionary. -/
noncomputable def lieSubmoduleLinearEquiv
    [LieModule R L M]
    (hM : ∀ (x : L) (m : M), ι R x • m = ⁅x, m⁆) (P : LieSubmodule R L M) :
    letI := asModule R L P
    P ≃ₗ[U] lieSubmoduleOrderIso hM P := by
  let : Module U P := asModule R L P
  let : IsScalarTower R U P := isScalarTower_asModule R L P
  exact
    { toFun := fun p => ⟨p, (mem_lieSubmoduleOrderIso hM).mpr p.property⟩
      invFun := fun p => ⟨p, (mem_lieSubmoduleOrderIso hM).mp p.property⟩
      left_inv := fun _ => rfl
      right_inv := fun _ => rfl
      map_add' := fun _ _ => rfl
      map_smul' := fun u p => by
        ext
        exact coe_smul_of_ι_smul hM P u p }

/-- The compatible-action submodule equivalence preserves the underlying ambient element. -/
@[simp]
theorem coe_lieSubmoduleLinearEquiv
    [LieModule R L M]
    (hM : ∀ (x : L) (m : M), ι R x • m = ⁅x, m⁆) (P : LieSubmodule R L M) :
    letI := asModule R L P
    ⇑(lieSubmoduleLinearEquiv hM P) =
      fun p => ⟨p, (mem_lieSubmoduleOrderIso hM).mpr p.property⟩ :=
  (rfl)

/-- The inverse compatible-action submodule equivalence preserves the underlying ambient element. -/
@[simp]
theorem coe_lieSubmoduleLinearEquiv_symm
    [LieModule R L M]
    (hM : ∀ (x : L) (m : M), ι R x • m = ⁅x, m⁆) (P : LieSubmodule R L M) :
    letI := asModule R L P
    ⇑(lieSubmoduleLinearEquiv hM P).symm =
      fun p => ⟨p, (mem_lieSubmoduleOrderIso hM).mp p.property⟩ :=
  (rfl)

/-- Equivalence to a fixed Lie module is the same as linear equivalence from the corresponding
compatible enveloping-algebra submodule. -/
theorem nonempty_lieModuleEquiv_iff_nonempty_linearEquiv
    [LieModule R L M]
    (hM : ∀ (x : L) (m : M), ι R x • m = ⁅x, m⁆)
    (S : Type*) [AddCommGroup S] [Module R S] [LieRingModule L S] [LieModule R L S]
    [Module U S] [IsScalarTower R U S]
    (hS : ∀ (x : L) (s : S), ι R x • s = ⁅x, s⁆)
    (P : LieSubmodule R L M) :
    Nonempty (P ≃ₗ⁅R,L⁆ S) ↔ Nonempty (lieSubmoduleOrderIso hM P ≃ₗ[U] S) := by
  let : Module U P := asModule R L P
  let : IsScalarTower R U P := isScalarTower_asModule R L P
  constructor
  · rintro ⟨e⟩
    exact ⟨(lieSubmoduleLinearEquiv hM P).symm.trans
      (lieModuleEquivEquivLinearEquiv (asModule_ι_smul R L P) hS e)⟩
  · rintro ⟨e⟩
    exact ⟨(lieModuleEquivEquivLinearEquiv (asModule_ι_smul R L P) hS).symm
      ((lieSubmoduleLinearEquiv hM P).trans e)⟩

end Dictionary

/-! ### The dictionary for the canonical enveloping-algebra module structure

The statements above take the `U(L)`-module structure as a hypothesis. Instantiated at
`TauCeti.UniversalEnvelopingAlgebra.asModule`, they say that the lattice of Lie submodules of any
Lie module is the lattice of `U(L)`-submodules of the same module. -/

section Canonical

variable [LieRingModule L M] [LieModule R L M]

attribute [local instance] asModule isScalarTower_asModule

/-- The submodule dictionary for the canonical enveloping-algebra module structure
`TauCeti.UniversalEnvelopingAlgebra.asModule`. -/
noncomputable def lieSubmoduleOrderIsoAsModule :
    LieSubmodule R L M ≃o Submodule U M :=
  lieSubmoduleOrderIso (asModule_ι_smul R L M)

/-- `TauCeti.UniversalEnvelopingAlgebra.lieSubmoduleOrderIsoAsModule` is the general dictionary at
the compatibility supplied by `TauCeti.UniversalEnvelopingAlgebra.asModule_ι_smul`, so all the
lemmas about the former apply to it. -/
theorem lieSubmoduleOrderIsoAsModule_def :
    lieSubmoduleOrderIsoAsModule R L M = lieSubmoduleOrderIso (asModule_ι_smul R L M) :=
  (rfl)

/-- Membership in the canonical submodule dictionary is membership in the Lie submodule. -/
@[simp]
theorem mem_lieSubmoduleOrderIsoAsModule {P : LieSubmodule R L M} {m : M} :
    m ∈ lieSubmoduleOrderIsoAsModule R L M P ↔ m ∈ P :=
  (Iff.rfl)

/-- Membership in the inverse of the canonical submodule dictionary is membership in the
`U(L)`-submodule. -/
@[simp]
theorem mem_lieSubmoduleOrderIsoAsModule_symm {Q : Submodule U M} {m : M} :
    m ∈ (lieSubmoduleOrderIsoAsModule R L M).symm Q ↔ m ∈ Q :=
  (Iff.rfl)

end Canonical

end TauCeti.UniversalEnvelopingAlgebra
