/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.Module.Projective
public import Mathlib.RepresentationTheory.Invariants
public import Mathlib.RepresentationTheory.Irreducible
import Mathlib.Algebra.Category.ModuleCat.Free
import Mathlib.Algebra.Category.ModuleCat.Projective
import Mathlib.RepresentationTheory.Maschke
import Mathlib.RingTheory.SimpleModule.InjectiveProjective
import Mathlib.RepresentationTheory.Rep.Iso
import TauCeti.RepresentationTheory.Irreducible
import TauCeti.RepresentationTheory.AsModule
import TauCeti.RepresentationTheory.Intertwining
import TauCeti.RepresentationTheory.OfModule
import TauCeti.RepresentationTheory.Rep.ChangeOfGroup

/-!
# Invariants of group representations

Mathlib names the group sum `∑ g, ρ g` of a finite-group representation `Representation.norm`,
builds the averaging projection `Representation.averageMap` separately out of the group-algebra
element `GroupAlgebra.average`, and records that the latter projects onto the invariants
(`Representation.isProj_averageMap`). What it does not record is how the two operators relate.
The group sum is the shape a symmetrization operator actually takes at a use site, where the
normalizing factor `⅟(#G)` is usually left implicit, and reinstating it by hand is the step that
gets rewritten.

This file supplies the bridge. Unfolding the group algebra once identifies `averageMap` with
`norm` scaled by `⅟(#G)`, and since scaling by a unit changes no image, `norm` has the same range
as the projection: the invariants.

There is a different integral reason for the norm to map onto the invariants. The norm does so on
the regular representation over any commutative ring, hence on every projective group-algebra
module by passage to a free module and a direct summand. As a consequence, taking invariants
preserves a surjection onto a projective representation. This exactness property is the input
needed to lift modular invariant vectors to an integral projective lattice.

The file also records the companion description of the invariants available when `G` is cyclic.
Invariance is a condition on every group element, but a vector fixed by a generator is fixed by all
of its powers, so testing a single generator `g` suffices and the invariants are cut out by the one
linear map `ρ(g) - 1`. Mathlib states this elementwise, in
`Representation.mem_invariants_iff_of_forall_mem_zpowers`; the submodule-level equality with
`ker (ρ(g) - 1)` is the form used to present the (co)homology of a finite cyclic group as a
subquotient of `M`, where each group is the homology of `ρ(g) - 1` and the norm in one order or
the other.

Finally, a nontrivial irreducible representation has no nonzero invariant vector. This is what makes
the Haar integral of a nontrivial irreducible character vanish. A dimension-based corollary handles
the common case where nontriviality follows from the dimension being other than one.

Taking invariants under a normal subgroup `S`, Mathlib's `Rep.quotientToInvariantsFunctor`, is an
additive functor from representations of `G` to representations of `G ⧸ S`.

When `G` is finite and `#G` is invertible in a field `k`, Maschke's theorem makes every
representation projective over `k[G]`, so the surjectivity result above makes taking invariants
exact. In particular the dimension of the invariants is additive in short exact sequences of
finite-dimensional representations.

## Main results

* `Representation.averageMap_eq_invOf_card_smul_norm`: the averaging projection is the group sum
  `Representation.norm` scaled by the inverse of the group order.
* `Representation.averageMap_comp_ρ`: the averaging projection does not see the action.
* `Representation.range_norm_eq_invariants`: the group sum `Representation.norm ρ` has the
  invariants as its range.
* `Representation.range_norm_eq_invariants_of_projective`: the same conclusion without
  inverting the group order, when the underlying group-algebra module is projective.
* `Representation.range_norm_trivial`: for trivial coefficients, the range of the norm is the ideal
  generated by the group order.
* `Representation.exists_invariant_preimage_of_surjective_of_projective`: a surjective
  equivariant additive map, possibly between representations over different coefficient rings,
  lifts invariant vectors when its target is projective over the target group algebra.
* `Representation.Equiv.invariantsLinearEquiv`: equivalent representations have isomorphic
  invariants.
* `Representation.invariants_comp_of_surjective`: restriction along a surjective homomorphism
  does not change the invariants.
* `Representation.finrank_invariants_tprod_of_comp`: invariant dimensions of tensor products may
  be compared along a surjective homomorphism of groups.
* `Rep.invariantsFunctor_map_surjective_of_surjective_of_projective`: taking invariants preserves
  a surjective morphism of representations whose target is projective over the group algebra.
* `Rep.trivialHomEquivInvariants`: the intertwiners out of the trivial line are the invariant
  vectors.
* `Rep.FiniteCyclicGroup.invariants_eq_ker_apply_sub`: for a cyclic group, the invariants are the
  kernel of the action of a generator minus the identity.
* `Representation.IsIrreducible.invariants_eq_bot`: a nontrivial irreducible representation has no
  nonzero invariant vector.
* `Representation.IsIrreducible.invariants_eq_bot_of_finrank_ne_one`: the dimension-based
  specialization.
* `Representation.IsIrreducible.eq_trivial_of_invariants_ne_bot` and
  `Representation.IsIrreducible.finrank_eq_one_of_invariants_ne_bot`: the two contrapositives, which
  turn a nonzero invariant vector of an irreducible representation into triviality and into
  dimension one.
* `Rep.quotientToInvariantsFunctor` is additive.
* `TauCeti.Rep.shortExact_map_invariantsFunctor`: under Maschke's hypothesis, taking invariants
  preserves short exact sequences.
* `TauCeti.FDRep.finrank_invariants_add_of_shortExact`: under Maschke's hypothesis, the dimension
  of the invariants is additive in short exact sequences of finite-dimensional representations.
-/
public section

namespace Representation

variable {k G V : Type*} [CommRing k] [Group G] [AddCommGroup V] [Module k V]
variable (ρ : Representation k G V) [Fintype G] [Invertible (Fintype.card G : k)]

/-- **The averaging projection is the normalized group sum.** Mathlib defines
`Representation.averageMap` through the group algebra; this unfolds that definition to the group sum
`Representation.norm`, scaled by the inverse of the group order. -/
theorem averageMap_eq_invOf_card_smul_norm :
    ρ.averageMap = ⅟(Fintype.card G : k) • ρ.norm := by
  simp only [averageMap, GroupAlgebra.average, map_smul, map_sum, MonoidAlgebra.of_apply,
    asAlgebraHom_single_one, norm]

/-- **Averaging does not see the action**: `avg ∘ ρ g = avg`, as `average k G * g = average k G`
in the group algebra (`GroupAlgebra.mul_average_right`). -/
theorem averageMap_comp_ρ (g : G) : ρ.averageMap ∘ₗ ρ g = ρ.averageMap := by
  rw [averageMap, ← asAlgebraHom_single_one, ← Module.End.mul_eq_comp, ← map_mul,
    GroupAlgebra.mul_average_right]

/-- **The group sum has the invariants as its range.** When `#G` is invertible in `k`, the operator
`Representation.norm ρ = ∑ g, ρ g` maps onto the invariants of `ρ`: it agrees with the averaging
projection up to the unit `#G`, so the two have the same image. -/
@[simp]
theorem range_norm_eq_invariants : LinearMap.range ρ.norm = ρ.invariants := by
  rw [← ρ.isProj_averageMap.range, averageMap_eq_invOf_card_smul_norm]
  refine le_antisymm ?_ (LinearMap.range_smul_le_range _ _)
  convert LinearMap.range_smul_le_range (⅟(Fintype.card G : k) • ρ.norm) (Fintype.card G : k)
  rw [smul_smul, mul_invOf_self, one_smul]

end Representation

namespace Representation

-- Stated over `Representation.trivial k H k`, the form to which `simp` reduces
-- `(Rep.trivial k H k).ρ`, so that it fires.
/-- For trivial coefficients, the range of the norm is the ideal generated by the group order. -/
@[simp]
theorem range_norm_trivial (k H : Type*) [CommSemiring k] [Group H] [Fintype H] :
    LinearMap.range (Representation.trivial k H k).norm = Ideal.span {(Nat.card H : k)} := by
  ext x
  simp [Representation.norm, Ideal.mem_span_singleton', mul_comm]

end Representation

namespace Representation

/-- **Restriction along a surjective homomorphism does not change the invariants**: a vector is
fixed by every `f g` exactly when it is fixed by every element of `H`. -/
theorem invariants_comp_of_surjective {k G H V : Type*} [CommRing k] [Group G] [Group H]
    [AddCommGroup V] [Module k V] (ρ : Representation k H V) (f : G →* H)
    (hf : Function.Surjective f) : invariants (ρ.comp f) = ρ.invariants := by
  ext v
  simp only [mem_invariants, MonoidHom.comp_apply]
  exact ⟨fun h g ↦ by obtain ⟨g, rfl⟩ := hf g; exact h g, fun h g ↦ h (f g)⟩

end Representation

namespace Representation

open scoped MonoidAlgebra

variable {k G V : Type*} [CommRing k] [Group G] [AddCommGroup V] [Module k V]

section Finite

variable [Fintype G]

/-- An invariant element of the group algebra is the norm of its coefficient at the identity,
over an arbitrary commutative ring. -/
private theorem norm_leftRegular_single_coeff_one {x : MonoidAlgebra k G}
    (hx : x ∈ (leftRegular k G).invariants) :
    (leftRegular k G).norm (MonoidAlgebra.single 1 (x.coeff 1)) = x := by
  ext g
  have hcoeff : x.coeff g = x.coeff 1 := by
    have h := congrArg (fun z : MonoidAlgebra k G => z.coeff g) (hx g)
    simpa using h.symm
  simp [norm, hcoeff]

/-- The norm maps onto the invariants of a direct sum of left regular representations. -/
private theorem range_norm_free_eq_invariants (ι : Type*) :
    LinearMap.range (ofModule' (k := k) (G := G) (ι →₀ MonoidAlgebra k G)).norm =
      (ofModule' (k := k) (G := G) (ι →₀ MonoidAlgebra k G)).invariants := by
  apply le_antisymm
  · rintro _ ⟨x, rfl⟩
    exact fun g => self_norm_apply _ g x
  · rintro x hx
    have hxi (i : ι) : x i ∈ (leftRegular k G).invariants := fun g => by
      have h := DFunLike.congr_fun (hx g) i
      rwa [TauCeti.Representation.ofModule'_apply, Finsupp.smul_apply, smul_eq_mul,
        ← asAlgebraHom_ofMulAction_smul_eq_mul, asAlgebraHom_single_one] at h
    refine ⟨Finsupp.mapRange (fun a => MonoidAlgebra.single 1 (a.coeff 1)) (by simp) x, ?_⟩
    ext i : 1
    rw [← norm_leftRegular_single_coeff_one (hxi i)]
    simp only [norm, LinearMap.sum_apply, Finsupp.finsetSum_apply,
      TauCeti.Representation.ofModule'_apply, Finsupp.smul_apply, Finsupp.mapRange_apply,
      smul_eq_mul, ← asAlgebraHom_ofMulAction_smul_eq_mul, asAlgebraHom_single_one]

/-- **The norm maps onto the invariants of a projective representation.** Let `G` be finite over
an arbitrary commutative ring `k`. If the `k[G]`-module underlying `ρ` is projective, then every
invariant vector is the norm of a vector.

This is the integral replacement for `Representation.range_norm_eq_invariants`, which assumes
that the order of `G` is invertible in `k`. -/
@[simp]
theorem range_norm_eq_invariants_of_projective (ρ : Representation k G V)
    [Module.Projective k[G] ρ.asModule] :
    LinearMap.range ρ.norm = ρ.invariants := by
  apply le_antisymm
  · rintro _ ⟨x, rfl⟩
    exact fun g => self_norm_apply _ g x
  · rintro x hx
    obtain ⟨s, hs⟩ := Module.projective_def.mp ‹Module.Projective k[G] ρ.asModule›
    let τ := ofModule' (k := k) (G := G) (ρ.asModule →₀ MonoidAlgebra k G)
    let E : τ.asModule ≃ₗ[k[G]] (ρ.asModule →₀ MonoidAlgebra k G) :=
      TauCeti.Representation.ofModule'AsModuleEquiv _
    let F : IntertwiningMap τ ρ := (IntertwiningMap.equivLinearMapAsModule τ ρ).symm
      (Finsupp.linearCombination k[G] id ∘ₗ E.toLinearMap)
    let S : IntertwiningMap ρ τ :=
      (IntertwiningMap.equivLinearMapAsModule ρ τ).symm (E.symm.toLinearMap ∘ₗ s)
    have hSx : S x ∈ τ.invariants := fun g => by
      rw [← IntertwiningMap.isIntertwining ρ τ S g x, hx g]
    obtain ⟨y, hy⟩ : S x ∈ LinearMap.range τ.norm := by
      rw [range_norm_free_eq_invariants]
      exact hSx
    -- `comp_norm` is stated along a group isomorphism (so that the two carriers may live in
    -- different universes); here it is used along the identity of `G`.
    have hF : τ.IsIntertwiningMap (ρ.comp ((MulEquiv.refl G : G ≃* G) : G →* G))
        F.toLinearMap := ⟨IntertwiningMap.isIntertwining τ ρ F⟩
    have hN : F (τ.norm y) = ρ.norm (F y) := LinearMap.congr_fun hF.comp_norm y
    have hF_apply (z : ρ.asModule →₀ MonoidAlgebra k G) :
        F z = ρ.asModuleEquiv
          (Finsupp.linearCombination k[G] id (E (τ.asModuleEquiv.symm z))) := by
      simp only [F, IntertwiningMap.equivLinearMapAsModule_symm_apply, LinearMap.comp_apply,
        LinearEquiv.coe_coe]
    have hS_apply (z : V) :
        S z = τ.asModuleEquiv (E.symm (s (ρ.asModuleEquiv.symm z))) := by
      simp only [S, IntertwiningMap.equivLinearMapAsModule_symm_apply, LinearMap.comp_apply,
        LinearEquiv.coe_coe]
    -- `S` is a section of `F`, because `s` is a section of `Finsupp.linearCombination`.
    have hFS : F (S x) = x := by
      simpa only [hF_apply, hS_apply, LinearEquiv.symm_apply_apply, E.apply_symm_apply,
        LinearEquiv.apply_symm_apply] using congrArg ρ.asModuleEquiv (hs (ρ.asModuleEquiv.symm x))
    exact ⟨F y, by rw [← hN, hy, hFS]⟩

end Finite

section ChangeRings

variable {l : Type*} [CommRing l] [Finite G]
variable {X : Type*} [AddCommGroup X] [Module l X]

/-- **Equivariant surjections lift invariants when the target is projective.** Let `ρ` and `σ` be
representations of the same finite group, possibly over different commutative rings. If an
equivariant additive map `f : V →+ X` is surjective and `σ.asModule` is projective over `l[G]`,
then every invariant vector of `σ` has an invariant preimage under `f`.

Allowing the coefficient rings to differ is essential for reduction of an integral projective
lattice modulo a prime. -/
-- The target invariant is a group norm; lift a preimage before taking the norm, and use
-- equivariance to commute `f` with the two norms.
theorem exists_invariant_preimage_of_surjective_of_projective
    (ρ : Representation k G V) (σ : Representation l G X)
    (f : V →+ X) (hf : Function.Surjective f)
    (hfg : ∀ g x, f (ρ g x) = σ g (f x))
    [Module.Projective l[G] σ.asModule]
    (y : σ.invariants) : ∃ x : ρ.invariants, f x = y := by
  let _ := Fintype.ofFinite G
  have hy : (y : X) ∈ LinearMap.range σ.norm := by
    rw [range_norm_eq_invariants_of_projective]
    exact y.2
  obtain ⟨z, hz⟩ := hy
  obtain ⟨x, rfl⟩ := hf z
  refine ⟨⟨ρ.norm x, fun g => self_norm_apply ρ g x⟩, ?_⟩
  rw [← hz]
  simp only [norm, LinearMap.sum_apply, map_sum]
  exact Finset.sum_congr rfl fun g _ => hfg g x

end ChangeRings

end Representation

namespace Representation.Equiv

variable {k G V W : Type*} [CommRing k] [Group G] [AddCommGroup V] [Module k V]
  [AddCommGroup W] [Module k W] {ρ : Representation k G V} {σ : Representation k G W}

/-- **Equivalent representations have isomorphic invariants.** An equivalence of
representations maps invariant vectors to invariant vectors, and so does its inverse. -/
def invariantsLinearEquiv (φ : ρ.Equiv σ) : ρ.invariants ≃ₗ[k] σ.invariants where
  toFun x := ⟨φ x, fun g ↦
    (IntertwiningMap.isIntertwining ρ σ φ.toIntertwiningMap g x).symm.trans
      (congrArg φ (x.property g))⟩
  invFun x := ⟨φ.symm x, fun g ↦
    (IntertwiningMap.isIntertwining σ ρ φ.symm.toIntertwiningMap g x).symm.trans
      (congrArg φ.symm (x.property g))⟩
  map_add' x y := Subtype.ext (map_add φ (x : V) y)
  map_smul' r x := Subtype.ext (map_smul φ r (x : V))
  left_inv x := Subtype.ext (φ.symm_apply_apply (x : V))
  right_inv x := Subtype.ext (φ.apply_symm_apply (x : W))

@[simp]
theorem coe_invariantsLinearEquiv_apply (φ : ρ.Equiv σ) (x : ρ.invariants) :
    (φ.invariantsLinearEquiv x : W) = φ (x : V) :=
  (rfl)

end Representation.Equiv

namespace Representation

variable {k G H V V' W W' : Type*} [CommRing k] [Group G] [Group H]
  [AddCommGroup V] [Module k V] [AddCommGroup V'] [Module k V']
  [AddCommGroup W] [Module k W] [AddCommGroup W'] [Module k W']

/-- **Invariant dimensions of tensor products along a surjective homomorphism of groups.** If the
restrictions of `X` and `Y` along a surjective `f : G →* H` are equivalent to `X'` and `Y'`, then
`X ⊗ Y` and `X' ⊗ Y'` have invariants of the same dimension: restriction along `f` does not change
the invariants (`Representation.invariants_comp_of_surjective`), and it commutes with tensor
products. -/
theorem finrank_invariants_tprod_of_comp {f : G →* H} (hf : Function.Surjective f)
    {X : Representation k H V} {Y : Representation k H W} {X' : Representation k G V'}
    {Y' : Representation k G W'} (e₁ : Equiv (X.comp f) X') (e₂ : Equiv (Y.comp f) Y') :
    Module.finrank k (X.tprod Y).invariants = Module.finrank k (X'.tprod Y').invariants := by
  rw [← invariants_comp_of_surjective (X.tprod Y) f hf]
  exact (e₁.tprod e₂).invariantsLinearEquiv.finrank_eq

end Representation

namespace Rep

open CategoryTheory
open scoped MonoidAlgebra

variable {k G : Type*} [CommRing k] [Group G]

/-- **Invariants preserve surjections onto projective representations.** If `f : A ⟶ B` is
surjective and the `k[G]`-module underlying `B` is projective, then every invariant of `B` lifts
to an invariant of `A`. -/
theorem invariantsFunctor_map_surjective_of_surjective_of_projective {A B : Rep k G} (f : A ⟶ B)
    (hf : Function.Surjective f.hom) [Module.Projective k[G] B.ρ.asModule] :
    Function.Surjective ((invariantsFunctor k G).map f).hom := by
  have : Projective B := by
    rw [← equivalenceModuleMonoidAlgebra.map_projective_iff]
    exact ModuleCat.projective_of_categoryTheory_projective (ModuleCat.of k[G] B.ρ.asModule)
  have : Epi f := (epi_iff_surjective f).2 hf
  have : IsSplitEpi f := ⟨⟨Projective.factorThru (𝟙 B) f, Projective.factorThru_comp _ _⟩⟩
  exact (ModuleCat.epi_iff_surjective _).1 inferInstance

/-- **Intertwiners out of the trivial line are the invariant vectors.** A morphism
`Rep.trivial k G k ⟶ A` is determined by the image of `1`, which is invariant, and an invariant
vector `x` is the image of `1` under `r ↦ r • x`. -/
noncomputable def trivialHomEquivInvariants (A : Rep k G) :
    (Rep.trivial k G k ⟶ A) ≃ₗ[k] A.ρ.invariants where
  toFun f := ⟨f.hom 1, fun g ↦ by simpa using (hom_comm_apply f g 1).symm⟩
  invFun x := ConcreteCategory.ofHom
    ⟨LinearMap.toSpanSingleton k A x, fun g ↦ LinearMap.ext fun r ↦ by simp [x.2 g]⟩
  map_add' _ _ := rfl
  map_smul' _ _ := rfl
  left_inv f := hom_ext <| Representation.IntertwiningMap.ext <| LinearMap.ext_ring <| one_smul k _
  right_inv x := Subtype.ext (one_smul k (x : A))

@[simp]
theorem coe_trivialHomEquivInvariants_apply (A : Rep k G) (f : Rep.trivial k G k ⟶ A) :
    (trivialHomEquivInvariants A f : A) = f.hom 1 :=
  (rfl)

@[simp]
theorem trivialHomEquivInvariants_symm_apply_hom (A : Rep k G) (x : A.ρ.invariants) (r : k) :
    ((trivialHomEquivInvariants A).symm x).hom r = r • (x : A) :=
  (rfl)

end Rep

namespace Representation.IsIrreducible

variable {k G V : Type*} [Field k] [Group G] [AddCommGroup V] [Module k V]

/-- **A nontrivial irreducible representation has no nonzero invariant vector.** -/
theorem invariants_eq_bot {ρ : Representation k G V} (h : ρ.IsIrreducible)
    (hρ : ρ ≠ trivial k G V) : ρ.invariants = ⊥ := by
  refine (Submodule.eq_bot_iff _).2 fun v hv => by_contra fun hv0 => hρ ?_
  let f : IntertwiningMap (trivial k G k) ρ :=
    (LinearMap.toSpanSingleton k V v).intertwiningMap_of_isIntertwiningMap _ _ fun g c => by
      rw [trivial_apply, LinearMap.toSpanSingleton_apply, map_smul]
      exact congrArg (c • ·) (hv g).symm
  have hf_one : f.toLinearMap 1 = v := by
    simp [f]
  have hsurj : Function.Surjective f.toLinearMap :=
    (IsIrreducible.surjective_or_eq_zero f).resolve_right fun hf =>
      hv0 <| calc
        v = f.toLinearMap 1 := hf_one.symm
        _ = (0 : IntertwiningMap (trivial k G k) ρ).toLinearMap 1 :=
          congrArg (fun φ : IntertwiningMap (trivial k G k) ρ => φ.toLinearMap 1) hf
        _ = 0 := rfl
  ext g x
  obtain ⟨c, rfl⟩ := hsurj x
  simpa using (IntertwiningMap.isIntertwining (trivial k G k) ρ f g c).symm

/-- **An irreducible representation of dimension other than one has no nonzero invariant
vector.** -/
theorem invariants_eq_bot_of_finrank_ne_one {ρ : Representation k G V} (h : ρ.IsIrreducible)
    (hV : Module.finrank k V ≠ 1) : ρ.invariants = ⊥ := by
  refine h.invariants_eq_bot fun hρ => hV ?_
  subst ρ
  let _ := h.nontrivial
  obtain ⟨v, hv⟩ := exists_ne (0 : V)
  let f : IntertwiningMap (trivial k G k) (trivial k G V) :=
    (LinearMap.toSpanSingleton k V v).intertwiningMap_of_isIntertwiningMap _ _ fun g c => by
      simp only [trivial_apply, LinearMap.toSpanSingleton_apply, map_smul]
  have hsurj : Function.Surjective f.toLinearMap :=
    (IsIrreducible.surjective_or_eq_zero f).resolve_right fun hf =>
      hv <| calc
        v = f.toLinearMap 1 := by simp [f]
        _ = (0 : IntertwiningMap (trivial k G k) (trivial k G V)).toLinearMap 1 :=
          congrArg (fun φ : IntertwiningMap (trivial k G k) (trivial k G V) =>
            φ.toLinearMap 1) hf
        _ = 0 := rfl
  apply finrank_eq_one v hv
  intro w
  obtain ⟨c, hc⟩ := hsurj w
  exact ⟨c, by simpa only [f, LinearMap.intertwiningMap_of_isIntertwiningMap,
    LinearMap.toSpanSingleton_apply] using hc⟩

/-- **An irreducible representation with a nonzero invariant vector is the trivial
representation**, the contrapositive of `Representation.IsIrreducible.invariants_eq_bot`. -/
theorem eq_trivial_of_invariants_ne_bot {ρ : Representation k G V} (h : ρ.IsIrreducible)
    (hne : ρ.invariants ≠ ⊥) : ρ = trivial k G V :=
  not_not.1 (mt h.invariants_eq_bot hne)

/-- **An irreducible representation with a nonzero invariant vector is a line**, the contrapositive
of `Representation.IsIrreducible.invariants_eq_bot_of_finrank_ne_one`. -/
theorem finrank_eq_one_of_invariants_ne_bot {ρ : Representation k G V} (h : ρ.IsIrreducible)
    (hne : ρ.invariants ≠ ⊥) : Module.finrank k V = 1 :=
  not_not.1 (mt h.invariants_eq_bot_of_finrank_ne_one hne)

end Representation.IsIrreducible

namespace Rep.FiniteCyclicGroup

variable {R G : Type*} [CommRing R] [Group G] (M : Rep R G) (g : G)

/-- If `g` generates `G`, the invariants of a representation are the kernel of `ρ(g) - 1`. -/
theorem invariants_eq_ker_apply_sub (hg : ∀ x, x ∈ Subgroup.zpowers g) :
    M.ρ.invariants = LinearMap.ker (M.ρ g - LinearMap.id) := by
  ext x
  simpa [sub_eq_zero] using
    Representation.mem_invariants_iff_of_forall_mem_zpowers M.ρ g hg x

end Rep.FiniteCyclicGroup

namespace TauCeti

variable {k G : Type*} [CommRing k] [Group G] (S : Subgroup G) [S.Normal]

/-- Taking `S`-invariants is additive, so it maps short complexes of representations of `G` to
short complexes of representations of `G ⧸ S`. -/
instance : (Rep.quotientToInvariantsFunctor k S).Additive where

end TauCeti

namespace TauCeti

open CategoryTheory CategoryTheory.Limits
open scoped MonoidAlgebra

universe u v w

variable {k : Type u} {G : Type v} [Field k] [Group G] [Finite G] [NeZero (Nat.card G : k)]

/-- Under Maschke's hypothesis, taking invariants preserves short exact sequences of
representations. -/
theorem Rep.shortExact_map_invariantsFunctor {S : ShortComplex (Rep.{w} k G)} (hS : S.ShortExact) :
    (S.map (Rep.invariantsFunctor k G)).ShortExact := by
  have : (Rep.invariantsFunctor k G).PreservesEpimorphisms := ⟨fun {X Y} f hf ↦ by
      have : Module.Projective k[G] Y.ρ.asModule :=
        Module.projective_of_isSemisimpleRing k[G] Y.ρ.asModule
      exact (ModuleCat.epi_iff_surjective _).2
        (Rep.invariantsFunctor_map_surjective_of_surjective_of_projective f
          ((Rep.epi_iff_surjective f).1 hf))⟩
  have : (Rep.invariantsFunctor k G).PreservesHomology :=
    Functor.preservesHomology_of_preservesEpis_and_kernels _
  have : Mono S.f := hS.mono_f
  have : Epi S.g := hS.epi_g
  exact hS.map _

/-- Invariant dimension is additive on short exact sequences of finite-dimensional
representations when the group order is invertible in the coefficient field. -/
theorem FDRep.finrank_invariants_add_of_shortExact {S : ShortComplex (FDRep k G)}
    (hS : S.ShortExact) :
    Module.finrank k (Representation.invariants S.X₂.ρ) =
      Module.finrank k (Representation.invariants S.X₁.ρ) +
        Module.finrank k (Representation.invariants S.X₃.ρ) := by
  have hInv := Rep.shortExact_map_invariantsFunctor
    (hS.map_of_exact (forget₂ (FDRep k G) (Rep k G)))
  -- `Rep.invariantsFunctor` sends `forget₂ V` to the invariant subspace of `V.ρ`
  -- (`Rep.invariantsFunctor_obj_carrier`, `FDRep.forget₂_ρ`).
  have hfinrank (V : FDRep k G) :
      Module.finrank k ((Rep.invariantsFunctor k G).obj ((forget₂ (FDRep k G) (Rep k G)).obj V)) =
        Module.finrank k (Representation.invariants V.ρ) :=
    rfl
  have hfinite (V : FDRep k G) :
      Module.Finite k ((Rep.invariantsFunctor k G).obj ((forget₂ (FDRep k G) (Rep k G)).obj V)) :=
    Module.Finite.of_injective (Representation.invariants V.ρ).subtype Subtype.coe_injective
  have : Module.Finite k ((S.map (forget₂ (FDRep k G) (Rep k G))).map
      (Rep.invariantsFunctor k G)).X₁ := hfinite S.X₁
  have : Module.Finite k ((S.map (forget₂ (FDRep k G) (Rep k G))).map
      (Rep.invariantsFunctor k G)).X₃ := hfinite S.X₃
  simpa only [ShortComplex.map_X₁, ShortComplex.map_X₂, ShortComplex.map_X₃, hfinrank] using
    ModuleCat.free_shortExact_finrank_add hInv rfl rfl

end TauCeti
