/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Topology.Constructions
public import Mathlib.Topology.UnitInterval

/-!
# Mapping tori and fibering over the circle

This file provides the topological interface for a space fibering over the circle.  Given a
homeomorphism `f : F ≃ₜ F`, its mapping torus is the quotient of `F × [0, 1]` obtained by
identifying `(x, 1)` with `(f x, 0)`.  The predicate `FibersOverCircle X` says that `X` is
homeomorphic to one of these mapping tori.

The construction is deliberately topological and does not impose a manifold structure on the
fiber or total space.  This is the reusable base for the geometric-topology roadmap's fibering
predicate; later manifold and hyperbolic developments can add their own hypotheses without
changing the quotient or its invariance API.

## Main definitions

* `MappingTorus.Carrier F f` is the quotient space associated to a self-homeomorphism `f`.
* `FibersOverCircle X` is the existence of a fiber and monodromy whose mapping torus is `X`.

## Main results

* `MappingTorus.top_eq_bot` records the defining endpoint identification.
* `MappingTorus.isQuotientMap_mk` and `MappingTorus.continuous_mk` expose the quotient map.
* `fibersOverCircle_mappingTorus` gives the canonical witness for every mapping torus.
* `FibersOverCircle.homeo` transports fibering across a homeomorphism of total spaces.
-/

public section

universe u

namespace TauCeti

namespace MappingTorus

/- The endpoints are named so that the quotient relation reads directly as the usual mapping-torus
identification. -/
/-- The bottom endpoint of the unit interval used in the mapping-torus cylinder. -/
def bottom : unitInterval := ⟨0, unitInterval.zero_mem⟩

/-- The top endpoint of the unit interval used in the mapping-torus cylinder. -/
def top : unitInterval := ⟨1, unitInterval.one_mem⟩

/-- The elementary endpoint relation used to form a mapping torus. -/
def step {F : Type u} [TopologicalSpace F] (f : F ≃ₜ F) (p q : F × unitInterval) : Prop :=
  p.2 = top ∧ q.2 = bottom ∧ f p.1 = q.1

/-- The equivalence relation generated by the endpoint identifications of `f`. -/
def setoid (F : Type u) [TopologicalSpace F] (f : F ≃ₜ F) : Setoid (F × unitInterval) where
  r := Relation.EqvGen (step f)
  iseqv := {
    refl := fun x ↦ Relation.EqvGen.refl x
    symm := fun {x y} h ↦ Relation.EqvGen.symm x y h
    trans := fun {x y z} h₁ h₂ ↦ Relation.EqvGen.trans x y z h₁ h₂ }

/-- The quotient topology on the mapping torus. -/
abbrev Carrier (F : Type u) [TopologicalSpace F] (f : F ≃ₜ F) := Quotient (setoid F f)

instance instTopologicalSpaceCarrier (F : Type u) [TopologicalSpace F] (f : F ≃ₜ F) :
    TopologicalSpace (Carrier F f) :=
  @instTopologicalSpaceQuotient (F × unitInterval) (setoid F f) inferInstance

/-- The quotient map into the mapping torus. -/
def mk {F : Type u} [TopologicalSpace F] (f : F ≃ₜ F) (p : F × unitInterval) : Carrier F f :=
  Quotient.mk (setoid F f) p

/-- The cylinder-to-mapping-torus quotient map is a quotient map. -/
theorem isQuotientMap_mk {F : Type u} [TopologicalSpace F] (f : F ≃ₜ F) :
    Topology.IsQuotientMap (mk f) :=
  isQuotientMap_quot_mk

/-- The quotient map from the cylinder into the mapping torus is continuous. -/
theorem continuous_mk {F : Type u} [TopologicalSpace F] (f : F ≃ₜ F) :
    Continuous (mk f) :=
  (isQuotientMap_mk f).continuous

/-- The top of each mapping-torus cylinder is identified with the image of its bottom. -/
theorem top_eq_bot (F : Type u) [TopologicalSpace F] (f : F ≃ₜ F) (x : F) :
    mk f (x, top) = mk f (f x, bottom) := by
  apply Quotient.sound
  exact Relation.EqvGen.rel _ _ ⟨rfl, rfl, rfl⟩

end MappingTorus

/-- A topological space fibers over the circle when it is a mapping torus of a self-homeomorphism.

The fiber and its topology are existential data.  In particular, this predicate does not choose a
preferred fiber or monodromy; a later theorem may compare different presentations by a
homeomorphism. -/
def FibersOverCircle (X : Type u) [TopologicalSpace X] : Prop :=
  ∃ (F : Type u) (_ : TopologicalSpace F) (f : F ≃ₜ F),
    Nonempty (X ≃ₜ MappingTorus.Carrier F f)

/-- Every mapping torus fibers over the circle by its defining presentation. -/
theorem fibersOverCircle_mappingTorus (F : Type u) [TopologicalSpace F] (f : F ≃ₜ F) :
    FibersOverCircle (MappingTorus.Carrier F f) := by
  exact ⟨F, inferInstance, f, ⟨Homeomorph.refl _⟩⟩

/-- Fibering over the circle is preserved by a homeomorphism of total spaces. -/
theorem FibersOverCircle.homeo {X Y : Type u} [TopologicalSpace X] [TopologicalSpace Y]
    (hX : FibersOverCircle X) (e : X ≃ₜ Y) : FibersOverCircle Y := by
  obtain ⟨F, _, f, ⟨h⟩⟩ := hX
  exact ⟨F, inferInstance, f, ⟨e.symm.trans h⟩⟩

/-- The fibering predicate is invariant under homeomorphism. -/
theorem fibersOverCircle_iff_of_homeomorph {X Y : Type u} [TopologicalSpace X] [TopologicalSpace Y]
    (e : X ≃ₜ Y) : FibersOverCircle X ↔ FibersOverCircle Y := by
  exact ⟨fun h ↦ h.homeo e, fun h ↦ h.homeo e.symm⟩

end TauCeti

end
