/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors, Wentao Li
-/
module

public import TauCeti.LinearAlgebra.FiniteBilinearModule.Dyadic.RankTwo.Basic

import TauCeti.Data.ZMod.BinaryQuadraticForm
import TauCeti.Data.ZMod.Two

/-!
# Rank-two dyadic blocks are `u^{(2)}(2^k)` or `v^{(2)}(2^k)`

Let `A` be a finite quadratic module and `K ≥ 1`. Suppose `x, y ∈ A` are killed by `2^K`, their
quadratic values `q(x)` and `q(y)` are killed by `2^K`, and their pairing `b(x, y)` has exact order
`2^K`. Then the subgroup `⟨x, y⟩` they generate, with the restricted form, is isometric to one of
Nikulin's rank-two dyadic generators `u^{(2)}(2^K)` or `v^{(2)}(2^K)`. In particular it is
nondegenerate, so it splits off orthogonally from `A`. This is the rank-two summand in Nikulin's
decomposition of a nondegenerate `2`-primary finite quadratic module: an element `x` of maximal
order `2^K` either generates a nondegenerate cyclic summand `q_θ^{(2)}(2^K)`, or `2^{K-1} b(x, x)`
vanishes, and then an element `y` of `2`-power order with `2^{K-1} b(x, y) ≠ 0` either generates
a cyclic summand or, together with `x`, satisfies the hypotheses above.

Write `q(x) = a / 2^K`, `q(y) = b / 2^K` and `b(x, y) = u / 2^K` with `a, b, u ∈ ℤ/2^K` and `u` odd,
so that

```text
q(m x + n y) = (a m² + u m n + b n²) / 2^K.
```

The classification is then the normal form of the binary form `a m² + u m n + b n²` over
`ℤ/2^K`, and it is decided by the parities of `a` and `b`.

* If `a` is even, the form has an isotropic vector `(m₀, 1)`, and completing it to a hyperbolic
  pair gives `u^{(2)}(2^K)`, where `q(m, n) = mn / 2^K`. The case of even `b` is symmetric.
* If `a` and `b` are both odd, the form represents `1` at a vector `(2j, 1)`, and a second vector
  can be adjusted to value `1` and pairing `1` with it, giving `v^{(2)}(2^K)`, where
  `q(m, n) = (m² + mn + n²) / 2^K`.

Each equation to be solved is reduced to a value of `s ↦ 2cs² + us` with `u` odd. That map is a
bijection of `ℤ/2^K`, because `(2cs² + us) - (2ct² + ut) = (s - t)(2c(s + t) + u)` and
`2c(s + t) + u` is a unit, `2` being nilpotent in `ℤ/2^K`; this replaces Hensel's lemma.

For `K = 1` the hypotheses say that `x` and `y` are `2`-torsion with `b(x, x) = b(y, y) = 0` and
`b(x, y) = 1/2`, and the conclusion recovers, for the subgroup `⟨x, y⟩`, the classification of
nondegenerate alternating forms on a Klein four-group in
`TauCeti.LinearAlgebra.FiniteBilinearModule.Dyadic.KleinFour`.

## Main results

* `TauCeti.FiniteQuadraticModule.nonempty_isometry_dyadicU_or_dyadicV_restrict_zmultiples_sup`:
  the subgroup generated by such `x` and `y` is isometric to `u^{(2)}(2^K)` or `v^{(2)}(2^K)`.
* `TauCeti.FiniteQuadraticModule.isNondegenerate_restrict_zmultiples_sup`: that subgroup is
  nondegenerate.

## References

* V. V. Nikulin, *Integral symmetric bilinear forms and some of their applications*,
  Proposition 1.8.1.
* C. T. C. Wall, *Quadratic forms on finite groups, and related topics*, Topology 2 (1963),
  281–298.
-/

public section

open AddSubgroup ZMod

namespace TauCeti.FiniteQuadraticModule

variable {k : ℕ}

/-! ## Transport to a finite quadratic module -/

variable {A : FiniteQuadraticModule}

/-- The homomorphism `ℤ/2^{k+1} → A` sending `1` to an element killed by `2^{k+1}`. -/
private def zmodHom {x : A} (hx : 2 ^ (k + 1) • x = 0) : ZMod (2 ^ (k + 1)) →+ A :=
  ZMod.lift _ ⟨zmultiplesHom A x, by rw [zmultiplesHom_apply, natCast_zsmul, hx]⟩

private theorem zmodHom_intCast {x : A} (hx : 2 ^ (k + 1) • x = 0) (m : ℤ) :
    zmodHom hx (m : ZMod (2 ^ (k + 1))) = m • x := by
  simp [zmodHom]

private theorem zmodHom_one {x : A} (hx : 2 ^ (k + 1) • x = 0) : zmodHom hx 1 = x := by
  simpa using zmodHom_intCast hx 1

private theorem zmodHom_mem_zmultiples {x : A} (hx : 2 ^ (k + 1) • x = 0)
    (m : ZMod (2 ^ (k + 1))) : zmodHom hx m ∈ zmultiples x := by
  obtain ⟨m, rfl⟩ := ZMod.intCast_surjective m
  rw [zmodHom_intCast]
  exact zsmul_mem_zmultiples x m

/-- With `q(x) = a / 2^{k+1}`, `q(y) = b / 2^{k+1}` and `b(x, y) = u / 2^{k+1}`, the value of `q`
at `mx + ny` is `(am² + umn + bn²) / 2^{k+1}`. -/
private theorem quadratic_zmodHom_add_zmodHom {x y : A} (hx : 2 ^ (k + 1) • x = 0)
    (hy : 2 ^ (k + 1) • y = 0) {a b u : ZMod (2 ^ (k + 1))}
    (ha : A.quadratic x = ZMod.toRatAddCircle _ a) (hb : A.quadratic y = ZMod.toRatAddCircle _ b)
    (hu : A.toFiniteBilinearModule.pairing x y = ZMod.toRatAddCircle _ u)
    (m n : ZMod (2 ^ (k + 1))) :
    A.quadratic (zmodHom hx m + zmodHom hy n) =
      ZMod.toRatAddCircle _ (a * m ^ 2 + u * m * n + b * n ^ 2) := by
  obtain ⟨m, rfl⟩ := ZMod.intCast_surjective m
  obtain ⟨n, rfl⟩ := ZMod.intCast_surjective n
  rw [zmodHom_intCast, zmodHom_intCast, quadratic_zsmul_add_zsmul, ha, hb, hu, ← map_zsmul,
    ← map_zsmul, ← map_zsmul, ← map_add, ← map_add]
  congr 1
  simp only [zsmul_eq_mul]
  push_cast
  ring

/-- A nondegenerate quadratic map `P` on `(ℤ/2^{k+1})²` is isometric to the restriction of `A` to
`⟨x, y⟩` as soon as `(m, n) ↦ (me₁ + nf₁)x + (me₂ + nf₂)y` carries `P` to `q`: that map is then
injective, because `P` is nondegenerate, and `⟨x, y⟩` has at most `2^{2(k+1)}` elements. -/
private theorem nonempty_isometry_ofQuadraticMap_restrict_zmultiples_sup
    (P : QuadraticMap ℤ (ZMod (2 ^ (k + 1)) × ZMod (2 ^ (k + 1))) (AddCircle (1 : ℚ)))
    (hP : (ofQuadraticMap P).IsNondegenerate) {x y : A} (hx : 2 ^ (k + 1) • x = 0)
    (hy : 2 ^ (k + 1) • y = 0) (e₁ e₂ f₁ f₂ : ZMod (2 ^ (k + 1)))
    (hval : ∀ m n, A.quadratic (zmodHom hx (m * e₁ + n * f₁) + zmodHom hy (m * e₂ + n * f₂)) =
      P (m, n)) :
    Nonempty (Isometry (ofQuadraticMap P) (A.restrict (zmultiples x ⊔ zmultiples y))) := by
  set H := zmultiples x ⊔ zmultiples y
  let Ψ : ZMod (2 ^ (k + 1)) × ZMod (2 ^ (k + 1)) →+ A :=
    (zmodHom hx).comp ((AddMonoidHom.mulRight e₁).coprod (AddMonoidHom.mulRight f₁)) +
      (zmodHom hy).comp ((AddMonoidHom.mulRight e₂).coprod (AddMonoidHom.mulRight f₂))
  have hΨ (p : ZMod (2 ^ (k + 1)) × ZMod (2 ^ (k + 1))) :
      Ψ p = zmodHom hx (p.1 * e₁ + p.2 * f₁) + zmodHom hy (p.1 * e₂ + p.2 * f₂) := by
    simp [Ψ]
  have hmem (p) : Ψ p ∈ H := by
    rw [hΨ]
    exact add_mem_sup (zmodHom_mem_zmultiples hx _) (zmodHom_mem_zmultiples hy _)
  -- The map is built on the bare quadratic map `P`, whose carrier is `(ℤ/2^{k+1})²` on the nose,
  -- and then read as a morphism out of `ofQuadraticMap P`.
  let g : P.Isometry (A.restrict H).quadratic :=
    { toLinearMap := (Ψ.codRestrict H hmem).toIntLinearMap
      map_app' := fun p ↦ (restrict_quadratic A H _).trans
        ((congrArg A.quadratic (hΨ p)).trans (hval p.1 p.2)) }
  have hinj : Function.Injective g := Hom.injective (A := ofQuadraticMap P) g hP
  -- `H` is the image of `(m, n) ↦ mx + ny`, so it has at most `2^{2(k+1)}` elements.
  let Φ := (zmodHom hx).coprod (zmodHom hy)
  have hH : H ≤ Φ.range := sup_le (zmultiples_le.2 ⟨(1, 0), by simp [Φ, zmodHom_one]⟩)
    (zmultiples_le.2 ⟨(0, 1), by simp [Φ, zmodHom_one]⟩)
  have hcard : Nat.card H ≤ Nat.card (ZMod (2 ^ (k + 1)) × ZMod (2 ^ (k + 1))) :=
    (card_le_of_le hH).trans (Nat.card_le_card_of_surjective _ Φ.rangeRestrict_surjective)
  exact ⟨Hom.toIsometryOfNondegenerate (A := ofQuadraticMap P) g hP
    (le_antisymm (Nat.card_le_card_of_injective g hinj) hcard)⟩

/-! ## The classification -/

/-- **Rank-two dyadic blocks.** If `x`, `y`, `q(x)`, and `q(y)` are all killed by `2^{k+1}`, and
`2^k b(x, y) ≠ 0`, then the subgroup generated by `x` and `y`, with the restricted form, is
isometric to `u^{(2)}(2^{k+1})` or to `v^{(2)}(2^{k+1})`. -/
theorem nonempty_isometry_dyadicU_or_dyadicV_restrict_zmultiples_sup {x y : A}
    (hx : 2 ^ (k + 1) • x = 0) (hy : 2 ^ (k + 1) • y = 0)
    (hqx : 2 ^ (k + 1) • A.quadratic x = 0) (hqy : 2 ^ (k + 1) • A.quadratic y = 0)
    (hxy : 2 ^ k • A.toFiniteBilinearModule.pairing x y ≠ 0) :
    Nonempty (Isometry (dyadicU (k + 1)) (A.restrict (zmultiples x ⊔ zmultiples y))) ∨
      Nonempty (Isometry (dyadicV (k + 1)) (A.restrict (zmultiples x ⊔ zmultiples y))) := by
  obtain ⟨a, ha⟩ := exists_toRatAddCircle_eq_of_nsmul_eq_zero _ hqx
  obtain ⟨b, hb⟩ := exists_toRatAddCircle_eq_of_nsmul_eq_zero _ hqy
  obtain ⟨u, hu⟩ := exists_toRatAddCircle_eq_of_nsmul_eq_zero _
    (v := A.toFiniteBilinearModule.pairing x y) (by
      rw [A.toFiniteBilinearModule.pairing_comm, ← map_nsmul, hx, map_zero])
  -- The pairing `u / 2^{k+1}` has exact order `2^{k+1}`, so `u` is odd.
  have hunit : IsUnit u := by
    obtain ⟨c, rfl⟩ | ⟨c, rfl⟩ := eq_two_mul_or_eq_two_mul_add_one u
    · refine absurd ?_ hxy
      have htwo_pow : (2 : ZMod (2 ^ (k + 1))) ^ (k + 1) = 0 := by
        exact_mod_cast ZMod.natCast_self (2 ^ (k + 1))
      rw [← hu, ← map_nsmul, nsmul_eq_mul, ← mul_assoc, Nat.cast_pow, Nat.cast_ofNat, ← pow_succ,
        htwo_pow, zero_mul, map_zero]
    · simpa using isUnit_two_mul_add (c := c) isUnit_one
  obtain ⟨e₁, e₂, f₁, f₂, -, h | h⟩ :=
    ZMod.BinaryQuadraticForm.exists_basis a b hunit
  · refine Or.inl (nonempty_isometry_ofQuadraticMap_restrict_zmultiples_sup _
      (isNondegenerate_dyadicU _) hx hy e₁ e₂ f₁ f₂ fun m n ↦ ?_)
    rw [quadratic_zmodHom_add_zmodHom hx hy ha.symm hb.symm hu.symm, h]
    exact (dyadicU_quadratic _ (m, n)).symm
  · refine Or.inr (nonempty_isometry_ofQuadraticMap_restrict_zmultiples_sup _
      (isNondegenerate_dyadicV _) hx hy e₁ e₂ f₁ f₂ fun m n ↦ ?_)
    rw [quadratic_zmodHom_add_zmodHom hx hy ha.symm hb.symm hu.symm, h]
    exact (dyadicV_quadratic _ (m, n)).symm

/-- Under the hypotheses of
`TauCeti.FiniteQuadraticModule.nonempty_isometry_dyadicU_or_dyadicV_restrict_zmultiples_sup`, the
subgroup generated by `x` and `y` is nondegenerate, so
`TauCeti.FiniteQuadraticModule.restrictProdOrthogonalComplementIsometry` splits it off `A`. -/
theorem isNondegenerate_restrict_zmultiples_sup {x y : A}
    (hx : 2 ^ (k + 1) • x = 0) (hy : 2 ^ (k + 1) • y = 0)
    (hqx : 2 ^ (k + 1) • A.quadratic x = 0) (hqy : 2 ^ (k + 1) • A.quadratic y = 0)
    (hxy : 2 ^ k • A.toFiniteBilinearModule.pairing x y ≠ 0) :
    (A.restrict (zmultiples x ⊔ zmultiples y)).IsNondegenerate := by
  rcases nonempty_isometry_dyadicU_or_dyadicV_restrict_zmultiples_sup hx hy hqx hqy hxy
    with ⟨⟨f⟩⟩ | ⟨⟨f⟩⟩
  · exact f.isNondegenerate (isNondegenerate_dyadicU _)
  · exact f.isNondegenerate (isNondegenerate_dyadicV _)

end TauCeti.FiniteQuadraticModule
