/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.LinearAlgebra.QuadraticForm.Radical
import TauCeti.LinearAlgebra.BilinearForm.Orthogonal
public import TauCeti.LinearAlgebra.QuadraticForm.OrthogonalGroup

/-!
# The Cartan--Dieudonne theorem

Every orthogonal automorphism of a finite-dimensional nondegenerate quadratic space over a field
of characteristic not two is generated by reflections in vectors of nonzero norm. The proof grows
a nondegenerate fixed subspace by one dimension at each step.

## Main results

* `TauCeti.QuadraticMap.subgroup_eq_top_of_reflection_mem`: any subgroup containing
  every reflection in a vector of invertible norm is the full orthogonal group.
* `TauCeti.QuadraticMap.exists_reflectionOrthogonal_list_prod_eq`: every orthogonal transformation
  is a product of at most twice the dimension many reflections.

## References

See H. B. Lawson and M.-L. Michelsohn, *Spin Geometry* (1989), Chapter I §2.
-/

public section

open QuadraticMap

namespace TauCeti.QuadraticMap

universe u v

variable {K : Type u} {V : Type v} [Field K] [AddCommGroup V] [Module K V]
  (Q : QuadraticForm K V)

private theorem exists_mem_orthogonal_self_ne_zero
    [FiniteDimensional K V] [Invertible (2 : K)]
    (B : LinearMap.BilinForm K V) (hB : B.Nondegenerate)
    (hBsymm : B.IsSymm) (W : Submodule K V) (hW : (B.restrict W).Nondegenerate)
    (hne : W ≠ ⊤) :
    ∃ x : V, x ∈ B.orthogonal W ∧ B x x ≠ 0 := by
  have horth_ne : B.orthogonal W ≠ ⊥ :=
    mt (B.orthogonal_eq_bot_iff hBsymm.isRefl hW hB).mp hne
  have hcomp : IsCompl W (B.orthogonal W) :=
    B.isCompl_orthogonal_of_restrict_nondegenerate hBsymm.isRefl hW
  have horth_nondegenerate : (B.restrict (B.orthogonal W)).Nondegenerate := by
    rw [B.restrict_nondegenerate_iff_isCompl_orthogonal hBsymm.isRefl,
      B.orthogonal_orthogonal hB hBsymm.isRefl W]
    exact hcomp.symm
  let _ : Nontrivial (B.orthogonal W) := Submodule.nontrivial_iff_ne_bot.mpr horth_ne
  obtain ⟨x, hxx⟩ :=
    LinearMap.BilinForm.exists_bilinForm_self_ne_zero horth_nondegenerate.ne_zero
      (LinearMap.BilinForm.isSymm_iff.mp (hBsymm.restrict _))
  exact ⟨x, x.2, hxx⟩

private theorem exists_reflectionOrthogonal_list_prod_mul_eq_one_of_codim
    [FiniteDimensional K V] [Invertible (2 : K)]
    (Q : QuadraticForm K V) (hQ : Q.Nondegenerate) (n : ℕ)
    (g : QuadraticMap.orthogonalGroup Q) (W : Submodule K V)
    (hW : (LinearMap.BilinForm.restrict (QuadraticMap.associated Q) W).Nondegenerate)
    (hfix : ∀ w ∈ W, ((g : V ≃ₗ[K] V) w) = w)
    (hcodim : Module.finrank K V - Module.finrank K W = n) :
    ∃ l : List (QuadraticMap.orthogonalGroup Q),
      (∀ r ∈ l, ∃ (v : V) (_ : Invertible (Q v)),
        QuadraticMap.reflectionOrthogonal Q v = r) ∧
      l.length ≤ 2 * n ∧ l.prod * g = 1 := by
  induction n using Nat.strong_induction_on generalizing g W with
  | h n ih =>
      by_cases htop : W = ⊤
      · refine ⟨[], by simp, by simp, ?_⟩
        apply Subtype.ext
        apply LinearEquiv.ext
        intro y
        -- Expose the underlying linear equivalence so the pointwise fixed-space hypothesis applies.
        change (g : V ≃ₗ[K] V) y = y
        exact hfix y (by simp [htop])
      · let B : LinearMap.BilinForm K V := QuadraticMap.associated Q
        have hB : B.Nondegenerate :=
          QuadraticMap.nondegenerate_associated_iff.mpr hQ
        have hBsymm : B.IsSymm :=
          LinearMap.BilinForm.isSymm_iff.mpr (QuadraticForm.associated_isSymm K Q)
        obtain ⟨x, hxorth, hxx⟩ :=
          exists_mem_orthogonal_self_ne_zero B hB hBsymm W hW htop
        have hxQ : Q x ≠ 0 := by
          rwa [QuadraticMap.associated_eq_self_apply] at hxx
        let _ : Invertible (Q x) := (isUnit_iff_ne_zero.mpr hxQ).invertible
        let S : Submodule K V := W ⊔ Submodule.span K {x}
        have hxx' : B x x ∈ nonZeroDivisorsRight K := by
          simpa only [nonZeroDivisorsRight_eq_nonZeroDivisors] using
            mem_nonZeroDivisors_of_ne_zero hxx
        have hS : (B.restrict S).Nondegenerate :=
          TauCeti.BilinForm.restrict_nondegenerate_sup_span_singleton
            B hBsymm.isRefl W hW.1 x hxx' hxorth
        have hxQorth : ∀ w ∈ W, Q.IsOrtho x w := by
          intro w hw
          rw [← QuadraticMap.associated_isOrtho]
          exact hBsymm.eq_iff.mpr (hxorth w hw)
        obtain ⟨l₁, hl₁refl, hl₁len, hfix₁⟩ :
            ∃ l₁ : List (QuadraticMap.orthogonalGroup Q),
              (∀ r ∈ l₁, ∃ (v : V) (_ : Invertible (Q v)),
                QuadraticMap.reflectionOrthogonal Q v = r) ∧
              l₁.length ≤ 2 ∧
              ∀ y ∈ S,
                (((l₁.prod * g : QuadraticMap.orthogonalGroup Q) : V ≃ₗ[K] V) y) = y := by
          exact exists_reflectionOrthogonal_list_prod_mul_eqOn_sup_span_singleton
            Q g W hfix x hxQorth
        have hlt : Module.finrank K V - Module.finrank K S < n := by
          have hxW : x ∉ W := fun hxW => hxx (hxorth x hxW)
          have hSfinrank : Module.finrank K S = Module.finrank K W + 1 :=
            Submodule.finrank_sup_span_singleton hxW
          have hWlt : Module.finrank K W < Module.finrank K V := Submodule.finrank_lt htop
          omega
        obtain ⟨l₂, hl₂refl, hl₂len, hprod₂⟩ :=
          ih (Module.finrank K V - Module.finrank K S) hlt (l₁.prod * g) S hS hfix₁ rfl
        refine ⟨l₂ ++ l₁, ?_, ?_, ?_⟩
        · intro r hr
          rw [List.mem_append] at hr
          exact hr.elim (hl₂refl r) (hl₁refl r)
        · rw [List.length_append]
          omega
        · simpa only [List.prod_append, mul_assoc] using hprod₂

/-- Every orthogonal transformation of a nondegenerate quadratic space is a product of at most
twice the dimension many reflections. -/
theorem exists_reflectionOrthogonal_list_prod_eq [FiniteDimensional K V] [NeZero (2 : K)]
    (Q : QuadraticForm K V) (hQ : Q.Nondegenerate)
    (g : QuadraticMap.orthogonalGroup Q) :
    ∃ l : List (QuadraticMap.orthogonalGroup Q),
      (∀ r ∈ l, ∃ (v : V) (_ : Invertible (Q v)),
        QuadraticMap.reflectionOrthogonal Q v = r) ∧
      l.length ≤ 2 * Module.finrank K V ∧ l.prod = g := by
  let _ : Invertible (2 : K) := invertibleOfNonzero (NeZero.ne (2 : K))
  obtain ⟨l, hlrefl, hllen, hprod⟩ :=
    exists_reflectionOrthogonal_list_prod_mul_eq_one_of_codim Q hQ
      (Module.finrank K V) g⁻¹ ⊥
      (by constructor <;> intro x _ <;> exact Subsingleton.elim x 0) (by simp) (by simp)
  refine ⟨l, hlrefl, hllen, ?_⟩
  calc
    l.prod = l.prod * g⁻¹ * g := by simp
    _ = g := by rw [hprod, one_mul]

/-- **Cartan--Dieudonné generation.** Any subgroup of the orthogonal group that contains every
reflection in a vector of invertible norm is the whole orthogonal group. -/
theorem subgroup_eq_top_of_reflection_mem
    [FiniteDimensional K V] [NeZero (2 : K)]
    (Q : QuadraticForm K V) (hQ : Q.Nondegenerate)
    (H : Subgroup (QuadraticMap.orthogonalGroup Q))
    (hreflection : ∀ (v : V) [Invertible (Q v)],
      QuadraticMap.reflectionOrthogonal Q v ∈ H) :
    H = ⊤ := by
  rw [Subgroup.eq_top_iff']
  intro g
  obtain ⟨l, hlrefl, _, rfl⟩ := exists_reflectionOrthogonal_list_prod_eq Q hQ g
  exact H.list_prod_mem fun r hr => by
    obtain ⟨v, _, rfl⟩ := hlrefl r hr
    exact hreflection v

end TauCeti.QuadraticMap
