/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.LinearAlgebra.Eigenspace.Pi
public import TauCeti.Algebra.Lie.Presentation.Serre
public import TauCeti.Algebra.Lie.Weights.Eigenvector

/-!
# The adjoint representation of a Serre system is integrable

Let `(H, E, F)` be a Serre system for a matrix of integers `CM` in a Lie algebra `L`
(`TauCeti.IsSerreSystem`), and suppose the raising and lowering families `E` and `F` generate `L`.
The motivating example is the Lie algebra `Matrix.ToLieAlgebra R CM` presented by Serre's
relations, with its own generators. This file proves that the adjoint representation of `L` is
**integrable** in the sense of Kac: the `Hᵢ` act diagonalizably with integral eigenvalues, and
the `Eᵢ` and `Fᵢ` act locally nilpotently.

* **Local nilpotence.** Each `ad Eᵢ` kills every element of `L` after finitely many steps; that
  is, the Engel subalgebra `LieSubalgebra.engel R (E i)` is all of `L`. The Engel subalgebra is a
  Lie subalgebra, so it suffices to check the generators. On `Eⱼ` this is the higher Serre
  relation `(ad Eᵢ) ^ (-CMᵢⱼ).toNat ⁅Eᵢ, Eⱼ⁆ = 0`, one step later. On `Fⱼ` with `j ≠ i` a single
  step suffices, since `⁅Eᵢ, Fⱼ⁆ = 0`; and `Fᵢ` is carried to `Hᵢ`, then to a multiple of `Eᵢ`,
  then to `0`. The statement for `ad Fᵢ` follows by the symmetry of Serre's relations exchanging
  the two families (`TauCeti.IsSerreSystem.neg_swap`), since `ad (-Fᵢ)` and `ad Fᵢ` have the same
  Engel subalgebra (`LieSubalgebra.engel_neg`).
* **Integral weights.** Write `L_χ` for the simultaneous eigenspace
  `⨅ i, (ad R L (H i)).eigenspace (χ i)` of the `ad Hᵢ` with integral eigenvalues `χ : B → ℤ`.
  The bracket carries `L_χ × L_ψ` into `L_{χ + ψ}` by the Leibniz rule, so the sum of the `L_χ` is
  a Lie subalgebra; it contains `Eⱼ` and `Fⱼ`, whose eigenvalues are the `j`-th column of `CM` and
  its negative, so it is all of `L`. Over an integral domain of characteristic zero on which `L` is
  torsion-free, the eigenspaces of the commuting operators `ad Hᵢ` for distinct integral
  eigenvalues are independent, and `L` is the internal direct sum of the `L_χ`.

Nothing here assumes that `CM` is a Cartan matrix. Integrability of the adjoint representation is
the first step of Serre's theorem identifying `Matrix.ToLieAlgebra K CM`, for a Cartan matrix `CM`
over a field `K` of characteristic zero, with the finite-dimensional split semisimple Lie algebra
of that Cartan matrix: local nilpotence is what makes `exp (ad Eᵢ)` and `exp (ad Fᵢ)` defined on
the presented algebra. Suitable composites of these exponentials implement simple reflections and
permute the weight spaces.

## Main results

* `TauCeti.IsSerreSystem.engel_E_eq_top` and `TauCeti.IsSerreSystem.engel_F_eq_top`: in a Lie
  algebra generated by a Serre system, `ad Eᵢ` and `ad Fᵢ` are locally nilpotent.
* `TauCeti.IsSerreSystem.iSup_iInf_eigenspace_ad_eq_top`: the `ad Hᵢ` are simultaneously
  diagonalizable with integral eigenvalues.
* `TauCeti.IsSerreSystem.iSupIndep_iInf_eigenspace_ad` and
  `TauCeti.IsSerreSystem.isInternal_iInf_eigenspace_ad`: over a characteristic-zero domain, the
  integral simultaneous eigenspaces are independent, and the Lie algebra is their internal direct
  sum.
* `TauCeti.engel_serreE_eq_top`, `TauCeti.engel_serreF_eq_top`,
  `TauCeti.iSup_iInf_eigenspace_ad_serreH_eq_top` and
  `TauCeti.isInternal_iInf_eigenspace_ad_serreH`: the same statements for the generators of
  `Matrix.ToLieAlgebra R CM`.

## References

* [J.P. Serre, *Complex Semisimple Lie Algebras*][serre1965], chapter VI, appendix
* [J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*][humphreys1972],
  §18
* V. G. Kac, *Infinite Dimensional Lie Algebras*, 3rd ed., §1.3 and Lemma 3.5.
-/

public section

open LieAlgebra

namespace TauCeti

variable {B R L : Type*} [CommRing R] [LieRing L] [LieAlgebra R L] {CM : Matrix B B ℤ}
  {H E F : B → L}

namespace IsSerreSystem

/-! ## Local nilpotence of the raising and lowering generators -/

section Engel

variable (h : IsSerreSystem R CM H E F)
include h

/-- `ad Eᵢ` kills each `Hⱼ` in two steps: `⁅Eᵢ, Hⱼ⁆` is a multiple of `Eᵢ`. -/
private theorem H_mem_engel_E (i j : B) : H j ∈ LieSubalgebra.engel R (E i) := by
  refine (LieSubalgebra.mem_engel_iff R _ _).2 ⟨2, ?_⟩
  rw [ad_pow_succ_apply, pow_one, ad_apply, ← lie_skew (E i) (H j), h.lie_H_E j i]
  simp

/-- The higher Serre relation, one step later: `ad Eᵢ` kills each `Eⱼ`. -/
private theorem E_mem_engel_E (i j : B) : E j ∈ LieSubalgebra.engel R (E i) :=
  (LieSubalgebra.mem_engel_iff R _ _).2
    ⟨(-CM i j).toNat + 1, by rw [ad_pow_succ_apply, h.ad_pow_lie_E_E i j]⟩

/-- `ad Eᵢ` kills `Fⱼ` in one step for `j ≠ i`, and carries `Fᵢ` to `Hᵢ`. -/
private theorem F_mem_engel_E (i j : B) : F j ∈ LieSubalgebra.engel R (E i) := by
  rcases eq_or_ne j i with rfl | hji
  · obtain ⟨n, hn⟩ := (LieSubalgebra.mem_engel_iff R _ _).1 (h.H_mem_engel_E j j)
    refine (LieSubalgebra.mem_engel_iff R _ _).2 ⟨n + 1, ?_⟩
    rw [ad_pow_succ_apply, h.lie_E_F_self j, hn]
  · exact (LieSubalgebra.mem_engel_iff R _ _).2
      ⟨1, by rw [pow_one, ad_apply, h.lie_E_F_of_ne i j hji.symm]⟩

/-- **The raising generators act locally nilpotently.** In a Lie algebra generated by the raising
and lowering families of a Serre system, every element is killed by some power of `ad Eᵢ`. -/
theorem engel_E_eq_top (hspan : LieSubalgebra.lieSpan R L (Set.range E ∪ Set.range F) = ⊤)
    (i : B) : LieSubalgebra.engel R (E i) = ⊤ := by
  rw [eq_top_iff, ← hspan, LieSubalgebra.lieSpan_le]
  rintro _ (⟨j, rfl⟩ | ⟨j, rfl⟩)
  · exact h.E_mem_engel_E i j
  · exact h.F_mem_engel_E i j

/-- **The lowering generators act locally nilpotently.** In a Lie algebra generated by the raising
and lowering families of a Serre system, every element is killed by some power of `ad Fᵢ`. -/
theorem engel_F_eq_top (hspan : LieSubalgebra.lieSpan R L (Set.range E ∪ Set.range F) = ⊤)
    (i : B) : LieSubalgebra.engel R (F i) = ⊤ := by
  -- The signed exchange of the two families is again a Serre system, generating the same algebra.
  have hspan' : LieSubalgebra.lieSpan R L
      (Set.range (fun j => -F j) ∪ Set.range (fun j => -E j)) = ⊤ := by
    rw [eq_top_iff, ← hspan, LieSubalgebra.lieSpan_le]
    rintro _ (⟨j, rfl⟩ | ⟨j, rfl⟩)
    · simpa using neg_mem (LieSubalgebra.subset_lieSpan (Or.inr ⟨j, rfl⟩) :
        -E j ∈ LieSubalgebra.lieSpan R L (Set.range (fun j => -F j) ∪ Set.range (fun j => -E j)))
    · simpa using neg_mem (LieSubalgebra.subset_lieSpan (Or.inl ⟨j, rfl⟩) :
        -F j ∈ LieSubalgebra.lieSpan R L (Set.range (fun j => -F j) ∪ Set.range (fun j => -E j)))
  simpa using h.neg_swap.engel_E_eq_top hspan' i

end Engel

/-! ## The integral weight decomposition -/

section Weights

variable (R H) in
/-- The sum of the simultaneous eigenspaces of the `ad Hᵢ` with integral eigenvalues, as a Lie
subalgebra. -/
private def iSupEigenspace : LieSubalgebra R L where
  toSubmodule := ⨆ χ : B → ℤ, ⨅ i, (ad R L (H i)).eigenspace (χ i : R)
  lie_mem' hx hy := lie_mem_iSup_iInf_eigenspace_ad hx hy

variable (h : IsSerreSystem R CM H E F)
include h

/-- **The Cartan generators act diagonalizably with integral eigenvalues.** In a Lie algebra
generated by the raising and lowering families of a Serre system, every element is a sum of
simultaneous eigenvectors of the `ad Hᵢ` whose eigenvalues are integers. -/
theorem iSup_iInf_eigenspace_ad_eq_top
    (hspan : LieSubalgebra.lieSpan R L (Set.range E ∪ Set.range F) = ⊤) :
    ⨆ χ : B → ℤ, ⨅ i, (ad R L (H i)).eigenspace (χ i : R) = ⊤ := by
  suffices h' : iSupEigenspace R H = ⊤ by
    rw [eq_top_iff]
    intro x _
    have hx : x ∈ iSupEigenspace R H := h' ▸ LieSubalgebra.mem_top x
    exact hx
  rw [eq_top_iff, ← hspan, LieSubalgebra.lieSpan_le]
  rintro _ (⟨j, rfl⟩ | ⟨j, rfl⟩)
  · refine Submodule.mem_iSup_of_mem (fun i => CM i j) ?_
    simp [h.lie_H_E, Int.cast_smul_eq_zsmul]
  · refine Submodule.mem_iSup_of_mem (fun i => -CM i j) ?_
    simp [h.lie_H_F, Int.cast_smul_eq_zsmul]

/-- Over a characteristic-zero domain on which `L` is torsion-free, the simultaneous eigenspaces
of the `ad Hᵢ` for distinct integral eigenvalues are independent: the `ad Hᵢ` commute. -/
theorem iSupIndep_iInf_eigenspace_ad [IsDomain R] [CharZero R] [Module.IsTorsionFree R L] :
    iSupIndep fun χ : B → ℤ => ⨅ i, (ad R L (H i)).eigenspace (χ i : R) := by
  have hcomm : ∀ i j, Commute (ad R L (H i)) (ad R L (H j)) := fun i j =>
    (commute_iff_eq _ _).2 <| LinearMap.ext fun z => by
      simp only [Module.End.mul_apply, ad_apply]
      rw [leibniz_lie, h.lie_H_H i j, zero_lie, zero_add]
  have hindep := Module.End.independent_iInf_maxGenEigenspace_of_forall_mapsTo
    (fun i => ad R L (H i)) fun i j φ => Module.End.mapsTo_maxGenEigenspace_of_comm (hcomm j i) φ
  refine (hindep.comp (f := fun χ : B → ℤ => fun i => (χ i : R)) fun χ ψ hχψ => ?_).mono
    fun χ => iInf_mono fun i => Module.End.eigenspace_le_maxGenEigenspace
  funext i
  exact Int.cast_injective (congr_fun hχψ i)

/-- **The integral weight decomposition.** Over a characteristic-zero domain on which `L` is
torsion-free, a Lie algebra generated by the raising and lowering families of a Serre system is
the internal direct sum of the simultaneous eigenspaces of the `ad Hᵢ` with integral eigenvalues.
-/
theorem isInternal_iInf_eigenspace_ad [IsDomain R] [CharZero R] [Module.IsTorsionFree R L]
    [DecidableEq (B → ℤ)] (hspan : LieSubalgebra.lieSpan R L (Set.range E ∪ Set.range F) = ⊤) :
    DirectSum.IsInternal fun χ : B → ℤ => ⨅ i, (ad R L (H i)).eigenspace (χ i : R) :=
  DirectSum.isInternal_submodule_of_iSupIndep_of_iSup_eq_top h.iSupIndep_iInf_eigenspace_ad
    (h.iSup_iInf_eigenspace_ad_eq_top hspan)

end Weights

end IsSerreSystem

/-! ## The presented algebra -/

section Presented

variable [DecidableEq B] (R CM)

/-- In the Lie algebra presented by Serre's relations, `ad Eᵢ` is locally nilpotent. -/
theorem engel_serreE_eq_top (i : B) : LieSubalgebra.engel R (serreE R CM i) = ⊤ :=
  (isSerreSystem_serre R CM).engel_E_eq_top (lieSpan_serreE_union_serreF_eq_top R CM) i

/-- In the Lie algebra presented by Serre's relations, `ad Fᵢ` is locally nilpotent. -/
theorem engel_serreF_eq_top (i : B) : LieSubalgebra.engel R (serreF R CM i) = ⊤ :=
  (isSerreSystem_serre R CM).engel_F_eq_top (lieSpan_serreE_union_serreF_eq_top R CM) i

/-- The Lie algebra presented by Serre's relations is spanned by simultaneous eigenvectors of the
`ad Hᵢ` with integral eigenvalues. -/
theorem iSup_iInf_eigenspace_ad_serreH_eq_top :
    ⨆ χ : B → ℤ, ⨅ i, (ad R (Matrix.ToLieAlgebra R CM) (serreH R CM i)).eigenspace (χ i : R) =
      ⊤ :=
  (isSerreSystem_serre R CM).iSup_iInf_eigenspace_ad_eq_top
    (lieSpan_serreE_union_serreF_eq_top R CM)

/-- Over a field of characteristic zero, the Lie algebra presented by Serre's relations is the
internal direct sum of the simultaneous eigenspaces of the `ad Hᵢ` with integral eigenvalues. -/
theorem isInternal_iInf_eigenspace_ad_serreH (K : Type*) [Field K] [CharZero K]
    [DecidableEq (B → ℤ)] :
    DirectSum.IsInternal fun χ : B → ℤ =>
      ⨅ i, (ad K (Matrix.ToLieAlgebra K CM) (serreH K CM i)).eigenspace (χ i : K) :=
  (isSerreSystem_serre K CM).isInternal_iInf_eigenspace_ad
    (lieSpan_serreE_union_serreF_eq_top K CM)

end Presented

end TauCeti
