/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.AlgebraicTopology.Singular.Contractible
public import TauCeti.AlgebraicTopology.Singular.Empty
public import TauCeti.AlgebraicTopology.Singular.Excision
public import TauCeti.AlgebraicTopology.Singular.Homotopy.Invariance
public import TauCeti.AlgebraicTopology.Singular.Sphere
public import TauCeti.Topology.Homotopy.StarConvexComplement

/-!
# Local homology at a point with a Euclidean chart

Let `M` be a `T₁` space and `x : M` a point in the source of an open partial homeomorphism
`φ : M → E` to a real normed space, such as a chart of a topological manifold modelled on `E`.
The **local homology** of `M` at `x` is the relative singular homology `Hₖ(M, M ∖ {x})`.  This
file computes it: it is the homology of `(E, E ∖ {φ x})`, so it vanishes in degree zero when
`E ≠ 0`, and in degree `k + 1` it is the degree-`k` reduced homology of the unit sphere `S` of `E`.
When `E` has dimension `n`, `Hₖ(M, M ∖ {x})` therefore vanishes for `k ≠ n`, and it is one copy of
the coefficients in degree `n`.

Local homology is the input to local orientations of manifolds: a local orientation of an
`n`-manifold at `x` is a generator of `Hₙ(M, M ∖ {x}; ℤ)`, and the orientation local system and
fundamental classes are assembled from these groups.

The computation has three steps.

* **Excision.**  For an open set `U` containing a closed set `K`, the inclusion
  `(U, U ∖ K) ⟶ (X, X ∖ K)` induces isomorphisms on relative homology
  (`TopPair.isIso_singularHomologyMap_excisionMap_of_isClosed_subset`), because the interiors of
  `U` and `X ∖ K` cover `X`.  Applied to the source of `φ` in `M` and to its target in `E`, and
  combined with the homeomorphism of source and target, this identifies `Hₖ(M, M ∖ {x})` with
  `Hₖ(E, E ∖ {φ x})` (`TauCeti.singularHomologyComplSingletonIsoOfChart`).
* **The connecting morphism.**  Since `E` is contractible, the reduced connecting morphism
  from `Hₖ₊₁(E, E ∖ {y})` to the degree-`k` reduced homology of `E ∖ {y}` is an isomorphism.
* **Radial retraction.**  `E ∖ {y}` is homotopy equivalent to the unit sphere of `E`
  (`TauCeti.complSingletonHomotopyEquivSphere`), by radial projection about `y` followed by
  translation.

## Main definitions and results

* `TauCeti.singularHomologyComplSingletonIsoOfChart`: `Hₖ(M, M ∖ {x}) ≅ Hₖ(E, E ∖ {φ x})`.
* `TauCeti.singularHomologyComplSingletonIso`: `Hₖ₊₁(M, M ∖ {x})` is isomorphic to the
  degree-`k` reduced homology of `S`.
* `TauCeti.isZero_singularHomology_complSingleton_zero`: `H₀(M, M ∖ {x}) = 0` when `E ≠ 0`.
* `TauCeti.isZero_singularHomology_complSingleton_of_ne`: `Hₖ(M, M ∖ {x}) = 0` for
  `k ≠ dim E`, for finite-dimensional `E`.
* `TauCeti.singularHomologyComplSingletonIsoOfFinrankEq`: `Hₙ₊₁(M, M ∖ {x}) ≅ R` when
  `dim E = n + 1`.
* `TauCeti.singularHomologyComplSingletonIsoOfFinrankEqZero`: `H₀(M, M ∖ {x}) ≅ R` when
  `dim E = 0`, generated by the class of the point.

## Local homology along star-convex sets

Local homology is locally constant: if `K ⊆ φ.target` is closed, bounded and star-convex about
`φ x`, and `φ.symm '' K` is closed in `M` (as when `K` is compact and `M` is Hausdorff), then the
inclusion `(M, M ∖ φ.symm '' K) ⟶ (M, M ∖ {x})` induces isomorphisms on relative homology. For
convex `K` this holds at every point of `φ.symm '' K`, so the local homology groups at nearby
points are identified through `Hₖ(M, M ∖ φ.symm '' K)`; this is how local orientations at nearby
points are compared. In `E`, both `E ∖ K` and `E ∖ {φ x}`
deformation retract onto a large sphere about `φ x` (`StarConvex.complSphereHomotopyEquiv`), and
the five lemma `TopPair.isIso_singularHomologyMap_of_isIso` compares the two pairs; excision
(`TopPair.isIso_singularHomologyMap_ofSubsetMap_compl_iff`) transports the comparison along `φ`.

* `TauCeti.isIso_singularHomologyMap_compl_of_starConvex`: `(E, E ∖ K) ⟶ (E, E ∖ {y})` induces
  isomorphisms for bounded `K` star-convex about `y ∈ K`.
* `TauCeti.isIso_singularHomologyMap_compl_of_chart`: `(M, M ∖ φ.symm '' K) ⟶ (M, M ∖ {x})`
  induces isomorphisms for such `K` star-convex about `φ x ∈ K`.
* `TauCeti.isZero_singularHomology_compl_symm_image_of_ne`,
  `TauCeti.singularHomologyComplSymmImageIsoOfFinrankEq` and
  `TauCeti.singularHomologyComplSymmImageIsoOfFinrankEqZero`: hence `Hₖ(M, M ∖ φ.symm '' K)`
  vanishes for `k ≠ dim E`, and is one copy of the coefficients when `k = dim E`.

## References

* A. Hatcher, *Algebraic Topology*, Section 3.3, the local homology groups `Hₙ(M, M ∖ {x})` and
  local orientations, where the comparison through `Hₙ(M, M ∖ B)` for a ball `B` defines the
  topology of the orientation cover, and Section 2.1, Theorem 2.20 (excision).
-/

public section

noncomputable section

open CategoryTheory Limits Metric Module

universe w v u

namespace TauCeti

variable {A : Type u} [Category.{v} A] [HasCoproducts.{w} A] [Abelian A] (R : A)

section Chart

variable {M : Type w} [TopologicalSpace M] [T1Space M] {E : Type w} [TopologicalSpace E]
  [T1Space E] (φ : OpenPartialHomeomorph M E) {x : M} (hx : x ∈ φ.source)

/-- The local homology of `M` at a point `x` in the source of an open partial homeomorphism
`φ : M → E` is that of `E` at `φ x`: excision onto the source of `φ`, the homeomorphism of the
source with the target, and excision onto the target give `Hₖ(M, M ∖ {x}) ≅ Hₖ(E, E ∖ {φ x})`
(`TauCeti.singularHomologyMap_excisionMap_comp_singularHomologyComplSingletonIsoOfChart_hom`). -/
def singularHomologyComplSingletonIsoOfChart (k : ℕ) :
    (TopPair.ofSubset ({x}ᶜ : Set (TopCat.of M))).singularHomology R k ≅
      (TopPair.ofSubset ({φ x}ᶜ : Set (TopCat.of E))).singularHomology R k :=
  haveI := TopPair.isIso_singularHomologyMap_excisionMap_of_isClosed_subset R
    (X := TopCat.of M) φ.open_source isClosed_singleton (Set.singleton_subset_iff.2 hx) k
  haveI := TopPair.isIso_singularHomologyMap_excisionMap_of_isClosed_subset R
    (X := TopCat.of E) φ.open_target isClosed_singleton
    (Set.singleton_subset_iff.2 (φ.map_source hx)) k
  (asIso (TopPair.singularHomologyMap
      (TopPair.excisionMap (X := TopCat.of M) φ.source {x}ᶜ) R k)).symm ≪≫
    asIso (TopPair.singularHomologyMap (TopPair.ofSubsetIso
      (X := TopCat.of φ.source) (Y := TopCat.of φ.target) φ.toHomeomorphSourceTarget
      (B := Subtype.val ⁻¹' {x}ᶜ) (B' := Subtype.val ⁻¹' {φ x}ᶜ)
      fun z ↦ (φ.injOn.eq_iff z.2 hx).not.symm).hom R k) ≪≫
    asIso (TopPair.singularHomologyMap
      (TopPair.excisionMap (X := TopCat.of E) φ.target {φ x}ᶜ) R k)

/-- The isomorphism `TauCeti.singularHomologyComplSingletonIsoOfChart` commutes with the
excision maps from the source and target of `φ` and the homeomorphism between them. -/
@[reassoc]
lemma singularHomologyMap_excisionMap_comp_singularHomologyComplSingletonIsoOfChart_hom
    (k : ℕ) :
    TopPair.singularHomologyMap (TopPair.excisionMap (X := TopCat.of M) φ.source {x}ᶜ) R k ≫
        (singularHomologyComplSingletonIsoOfChart R φ hx k).hom =
      TopPair.singularHomologyMap (TopPair.ofSubsetIso
          (X := TopCat.of φ.source) (Y := TopCat.of φ.target) φ.toHomeomorphSourceTarget
          (B := Subtype.val ⁻¹' {x}ᶜ) (B' := Subtype.val ⁻¹' {φ x}ᶜ)
          fun z ↦ (φ.injOn.eq_iff z.2 hx).not.symm).hom R k ≫
        TopPair.singularHomologyMap
          (TopPair.excisionMap (X := TopCat.of E) φ.target {φ x}ᶜ) R k := by
  simp [singularHomologyComplSingletonIsoOfChart]

/-- The inverse of `TauCeti.singularHomologyComplSingletonIsoOfChart` commutes with the excision
maps from the target and source of `φ` and the inverse homeomorphism between them. -/
@[reassoc]
lemma singularHomologyMap_excisionMap_comp_singularHomologyComplSingletonIsoOfChart_inv
    (k : ℕ) :
    TopPair.singularHomologyMap (TopPair.excisionMap (X := TopCat.of E) φ.target {φ x}ᶜ) R k ≫
        (singularHomologyComplSingletonIsoOfChart R φ hx k).inv =
      TopPair.singularHomologyMap (TopPair.ofSubsetIso
          (X := TopCat.of φ.source) (Y := TopCat.of φ.target) φ.toHomeomorphSourceTarget
          (B := Subtype.val ⁻¹' {x}ᶜ) (B' := Subtype.val ⁻¹' {φ x}ᶜ)
          fun z ↦ (φ.injOn.eq_iff z.2 hx).not.symm).inv R k ≫
        TopPair.singularHomologyMap
          (TopPair.excisionMap (X := TopCat.of M) φ.source {x}ᶜ) R k := by
  rw [← cancel_mono (singularHomologyComplSingletonIsoOfChart R φ hx k).hom, Category.assoc,
    Iso.inv_hom_id, Category.comp_id, Category.assoc,
    singularHomologyMap_excisionMap_comp_singularHomologyComplSingletonIsoOfChart_hom,
    ← Category.assoc, ← TopPair.singularHomologyMap_comp, Iso.inv_hom_id,
    TopPair.singularHomologyMap_id, Category.id_comp]

end Chart

variable {M : Type w} [TopologicalSpace M] [T1Space M] {E : Type w} [NormedAddCommGroup E]
  [NormedSpace ℝ E] (φ : OpenPartialHomeomorph M E) {x : M} (hx : x ∈ φ.source)

/-- **Local homology at a point with a Euclidean chart.** For `x` in the source of an open
partial homeomorphism `φ : M → E`, the local homology `Hₖ₊₁(M, M ∖ {x})` is the degree-`k`
reduced homology of the unit sphere of `E`.  It is
`TauCeti.singularHomologyComplSingletonIsoOfChart`, followed by the reduced connecting morphism
of the pair `(E, E ∖ {φ x})`, an isomorphism since `E` is contractible, and by
`TauCeti.complSingletonHomotopyEquivSphere`. -/
def singularHomologyComplSingletonIso (k : ℕ) :
    (TopPair.ofSubset ({x}ᶜ : Set (TopCat.of M))).singularHomology R (k + 1) ≅
      (reducedSingularHomologyFunctor R k).obj (TopCat.of (sphere (0 : E) 1)) :=
  haveI : ContractibleSpace (TopPair.ofSubset ({φ x}ᶜ : Set (TopCat.of E))).fst :=
    inferInstanceAs (ContractibleSpace E)
  singularHomologyComplSingletonIsoOfChart R φ hx (k + 1) ≪≫
    asIso ((TopPair.ofSubset ({φ x}ᶜ : Set (TopCat.of E))).reducedSingularHomologyδ R k) ≪≫
    (complSingletonHomotopyEquivSphere (φ x)).reducedSingularHomologyIso R k

/-- `TauCeti.singularHomologyComplSingletonIso` is the chart isomorphism followed by the reduced
connecting morphism of `(E, E ∖ {φ x})` and the map induced by
`TauCeti.complSingletonHomotopyEquivSphere`. -/
@[simp]
lemma singularHomologyComplSingletonIso_hom (k : ℕ) :
    (singularHomologyComplSingletonIso R φ hx k).hom =
      (singularHomologyComplSingletonIsoOfChart R φ hx (k + 1)).hom ≫
        (TopPair.ofSubset ({φ x}ᶜ : Set (TopCat.of E))).reducedSingularHomologyδ R k ≫
          (reducedSingularHomologyFunctor R k).map
            (TopCat.ofHom (complSingletonHomotopyEquivSphere (φ x)).toFun) := by
  -- The subspace of the pair `(E, E ∖ {φ x})` and the source of the homotopy equivalence are the
  -- same space presented through `TopCat.of E` and through `E`, so the inner composite is only
  -- type-correct up to unfolding and is rewritten by `Iso.trans_hom` as a term.
  have : ContractibleSpace (TopPair.ofSubset ({φ x}ᶜ : Set (TopCat.of E))).fst :=
    inferInstanceAs (ContractibleSpace E)
  rw [singularHomologyComplSingletonIso, Iso.trans_hom]
  exact congrArg (_ ≫ ·) ((Iso.trans_hom _ _).trans (congrArg₂ (· ≫ ·) (asIso_hom _)
    (ContinuousMap.HomotopyEquiv.reducedSingularHomologyIso_hom R _ k)))

/-- The inverse of `TauCeti.singularHomologyComplSingletonIso` is the map induced by the homotopy
inverse of `TauCeti.complSingletonHomotopyEquivSphere`, followed by the inverse of the reduced
connecting morphism of `(E, E ∖ {φ x})` and the inverse of the chart isomorphism. -/
@[simp]
lemma singularHomologyComplSingletonIso_inv (k : ℕ) :
    (singularHomologyComplSingletonIso R φ hx k).inv =
      (reducedSingularHomologyFunctor R k).map
          (TopCat.ofHom (complSingletonHomotopyEquivSphere (φ x)).invFun) ≫
        -- The ambient space of `(E, E ∖ {φ x})` is `E` only up to unfolding `TopPair.ofSubset`,
        -- so the instance making the reduced connecting morphism invertible is supplied by hand.
        inv ((TopPair.ofSubset ({φ x}ᶜ : Set (TopCat.of E))).reducedSingularHomologyδ R k)
            (I := @TopPair.isIso_reducedSingularHomologyδ_of_contractibleSpace _ _ _ _ _ R
              (inferInstanceAs (ContractibleSpace E)) k) ≫
          (singularHomologyComplSingletonIsoOfChart R φ hx (k + 1)).inv := by
  have : ContractibleSpace (TopPair.ofSubset ({φ x}ᶜ : Set (TopCat.of E))).fst :=
    inferInstanceAs (ContractibleSpace E)
  rw [singularHomologyComplSingletonIso, Iso.trans_inv]
  exact (congrArg (· ≫ _) ((Iso.trans_inv _ _).trans (congrArg₂ (· ≫ ·)
    (ContinuousMap.HomotopyEquiv.reducedSingularHomologyIso_inv R
      (complSingletonHomotopyEquivSphere (φ x)) k)
    (asIso_inv
      ((TopPair.ofSubset ({φ x}ᶜ : Set (TopCat.of E))).reducedSingularHomologyδ R k))))).trans
    (Category.assoc _ _ _)

include hx in
/-- **Local homology vanishes in degree zero** at a point with a chart to a nonzero real normed
space: `E` is path connected and `E ∖ {φ x}` is nonempty. -/
theorem isZero_singularHomology_complSingleton_zero [Nontrivial E] :
    IsZero ((TopPair.ofSubset ({x}ᶜ : Set (TopCat.of M))).singularHomology R 0) := by
  have : PathConnectedSpace (TopPair.ofSubset ({φ x}ᶜ : Set (TopCat.of E))).fst :=
    inferInstanceAs (PathConnectedSpace E)
  have : Nonempty (TopPair.ofSubset ({φ x}ᶜ : Set (TopCat.of E))).snd :=
    let ⟨z, hz⟩ := exists_ne (φ x)
    ⟨⟨z, hz⟩⟩
  exact (TopPair.isZero_singularHomology_zero _ R).of_iso
    (singularHomologyComplSingletonIsoOfChart R φ hx 0)

include hx in
/-- **Local homology vanishes outside the dimension**: at a point with a chart to a real normed
space `E` of finite dimension `n`, the local homology `Hₖ(M, M ∖ {x})` vanishes for `k ≠ n`. -/
theorem isZero_singularHomology_complSingleton_of_ne [FiniteDimensional ℝ E] {n k : ℕ}
    (h : finrank ℝ E = n) (hk : k ≠ n) :
    IsZero ((TopPair.ofSubset ({x}ᶜ : Set (TopCat.of M))).singularHomology R k) := by
  cases k with
  | zero =>
    have : Nontrivial E := Module.nontrivial_of_finrank_pos (h ▸ Nat.pos_of_ne_zero hk.symm)
    exact isZero_singularHomology_complSingleton_zero R φ hx
  | succ k =>
    refine IsZero.of_iso ?_ (singularHomologyComplSingletonIso R φ hx k)
    cases n with
    | zero =>
      -- A zero-dimensional space is a point, so its unit sphere is empty.
      have : Subsingleton E := Module.finrank_zero_iff.1 h
      have : IsEmpty (sphere (0 : E) 1) :=
        ⟨fun z ↦ by simpa [Subsingleton.elim (z : E) 0] using z.2⟩
      exact isZero_reducedSingularHomologyFunctor_of_isEmpty R _ k
    | succ n =>
      exact (isZero_reducedSingularHomologyFunctor_sphere_of_ne R
        (finrank_euclideanSpace_ulift_fin.{w} (n + 1)) (by lia)).of_iso
        (reducedSingularHomologySphereIsoOfFinrankEq R
          (h.trans (finrank_euclideanSpace_ulift_fin (n + 1)).symm) k)

/-- **Local homology of a zero-dimensional chart**: at a point with a chart to a zero-dimensional
real normed space, the local homology `H₀(M, M ∖ {x})` is one copy of the coefficients.  Since `E`
is a point, `E ∖ {φ x}` is empty, so it is `TauCeti.singularHomologyComplSingletonIsoOfChart`
followed by the inverse of the quotient map from `H₀(E)` and by the augmentation of `H₀(E)`. -/
def singularHomologyComplSingletonIsoOfFinrankEqZero [FiniteDimensional ℝ E]
    (h : finrank ℝ E = 0) :
    (TopPair.ofSubset ({x}ᶜ : Set (TopCat.of M))).singularHomology R 0 ≅ R :=
  haveI : IsEmpty (TopPair.ofSubset ({φ x}ᶜ : Set (TopCat.of E))).snd :=
    have : Subsingleton E := Module.finrank_zero_iff.1 h
    ⟨fun z ↦ z.2 (Subsingleton.elim _ _)⟩
  -- The quotient map starts at the homology of the singular simplicial set of `E`, so the
  -- augmentation is taken there; it is `TopCat.singularHomology₀ε` by definition.
  haveI : IsIso ((TopPair.toSSetPair.obj
      (TopPair.ofSubset ({φ x}ᶜ : Set (TopCat.of E)))).right.homology₀ε R) :=
    haveI : PathConnectedSpace (TopPair.ofSubset ({φ x}ᶜ : Set (TopCat.of E))).fst :=
      inferInstanceAs (PathConnectedSpace E)
    inferInstanceAs
      (IsIso ((TopPair.ofSubset ({φ x}ᶜ : Set (TopCat.of E))).fst.singularHomology₀ε R))
  singularHomologyComplSingletonIsoOfChart R φ hx 0 ≪≫
    (asIso ((TopPair.ofSubset ({φ x}ᶜ : Set (TopCat.of E))).singularHomologyπ R 0)).symm ≪≫
    asIso ((TopPair.toSSetPair.obj
      (TopPair.ofSubset ({φ x}ᶜ : Set (TopCat.of E)))).right.homology₀ε R)

/-- `TauCeti.singularHomologyComplSingletonIsoOfFinrankEqZero` sends the image of a class of
`H₀(E)` under the quotient map and the inverse of the chart isomorphism to its augmentation. -/
@[reassoc]
lemma singularHomologyπ_comp_singularHomologyComplSingletonIsoOfFinrankEqZero_hom
    [FiniteDimensional ℝ E] (h : finrank ℝ E = 0) :
    (TopPair.ofSubset ({φ x}ᶜ : Set (TopCat.of E))).singularHomologyπ R 0 ≫
        (singularHomologyComplSingletonIsoOfChart R φ hx 0).inv ≫
          (singularHomologyComplSingletonIsoOfFinrankEqZero R φ hx h).hom =
      (TopPair.ofSubset ({φ x}ᶜ : Set (TopCat.of E))).fst.singularHomology₀ε R := by
  have : IsEmpty (TopPair.ofSubset ({φ x}ᶜ : Set (TopCat.of E))).snd :=
    have : Subsingleton E := Module.finrank_zero_iff.1 h
    ⟨fun z ↦ z.2 (Subsingleton.elim _ _)⟩
  simp only [singularHomologyComplSingletonIsoOfFinrankEqZero, Iso.trans_hom, Iso.symm_hom,
    asIso_hom, asIso_inv, Iso.inv_hom_id_assoc, IsIso.hom_inv_id_assoc]
  -- The augmentation of the singular simplicial set of `E` is `TopCat.singularHomology₀ε`.
  rfl

/-- The generator of the local homology `H₀(M, M ∖ {x})` of a zero-dimensional chart is the class
of the point `φ x` of `E`, carried by the quotient map and the inverse of the chart isomorphism. -/
@[simp]
lemma singularHomologyComplSingletonIsoOfFinrankEqZero_inv [FiniteDimensional ℝ E]
    (h : finrank ℝ E = 0) :
    (singularHomologyComplSingletonIsoOfFinrankEqZero R φ hx h).inv =
      singularHomology₀Section R (X := (TopPair.ofSubset ({φ x}ᶜ : Set (TopCat.of E))).fst) (φ x) ≫
        (TopPair.ofSubset ({φ x}ᶜ : Set (TopCat.of E))).singularHomologyπ R 0 ≫
          (singularHomologyComplSingletonIsoOfChart R φ hx 0).inv := by
  simp only [singularHomologyComplSingletonIsoOfFinrankEqZero, Iso.trans_inv, Iso.symm_inv,
    asIso_hom, asIso_inv, Category.assoc]
  have : PathConnectedSpace (TopPair.ofSubset ({φ x}ᶜ : Set (TopCat.of E))).fst :=
    inferInstanceAs (PathConnectedSpace E)
  have : IsIso ((TopPair.toSSetPair.obj
      (TopPair.ofSubset ({φ x}ᶜ : Set (TopCat.of E)))).right.homology₀ε R) :=
    inferInstanceAs
      (IsIso ((TopPair.ofSubset ({φ x}ᶜ : Set (TopCat.of E))).fst.singularHomology₀ε R))
  congr 1
  exact IsIso.inv_eq_of_inv_hom_id (singularHomology₀Section_singularHomology₀ε R _)

/-- **Local homology in the top degree**: at a point with a chart to a real normed space of
dimension `n + 1`, the local homology `Hₙ₊₁(M, M ∖ {x})` is one copy of the coefficients.  It is
`TauCeti.singularHomologyComplSingletonIso` followed by the map on reduced homology induced by the
homeomorphism of the unit sphere of `E` with `TopCat.sphere n`
(`TauCeti.sphereHomeomorphOfFinrankEq` and `TauCeti.diskBoundaryHomeomorph`), and by
`TauCeti.reducedSingularHomologyTopCatSphereIso`. -/
def singularHomologyComplSingletonIsoOfFinrankEq {n : ℕ} (h : finrank ℝ E = n + 1) :
    (TopPair.ofSubset ({x}ᶜ : Set (TopCat.of M))).singularHomology R (n + 1) ≅ R :=
  haveI := Module.finite_of_finrank_eq_succ h
  singularHomologyComplSingletonIso R φ hx n ≪≫
    (reducedSingularHomologyFunctor R n).mapIso (TopCat.isoOfHomeo
      ((sphereHomeomorphOfFinrankEq
          (h.trans (finrank_euclideanSpace_ulift_fin.{w} (n + 1)).symm)).trans
        (diskBoundaryHomeomorph (n + 1)).symm : sphere (0 : E) 1 ≃ₜ TopCat.sphere.{w} n)) ≪≫
    reducedSingularHomologyTopCatSphereIso R n

/-- `TauCeti.singularHomologyComplSingletonIsoOfFinrankEq` is
`TauCeti.singularHomologyComplSingletonIso`, followed by the map on reduced homology induced by the
homeomorphism of the unit sphere of `E` with `TopCat.sphere n`, and by
`TauCeti.reducedSingularHomologyTopCatSphereIso`. -/
@[simp]
lemma singularHomologyComplSingletonIsoOfFinrankEq_hom {n : ℕ} (h : finrank ℝ E = n + 1) :
    haveI := Module.finite_of_finrank_eq_succ h
    (singularHomologyComplSingletonIsoOfFinrankEq R φ hx h).hom =
      (singularHomologyComplSingletonIso R φ hx n).hom ≫
        (reducedSingularHomologyFunctor R n).map (TopCat.ofHom
          (((sphereHomeomorphOfFinrankEq
              (h.trans (finrank_euclideanSpace_ulift_fin.{w} (n + 1)).symm)).trans
            (diskBoundaryHomeomorph (n + 1)).symm : sphere (0 : E) 1 ≃ₜ TopCat.sphere.{w} n) :
            C(sphere (0 : E) 1, TopCat.sphere.{w} n))) ≫
          (reducedSingularHomologyTopCatSphereIso R n).hom :=
  (rfl)

/-- The inverse of `TauCeti.singularHomologyComplSingletonIsoOfFinrankEq` is the inverse of
`TauCeti.reducedSingularHomologyTopCatSphereIso`, followed by the map on reduced homology induced
by the homeomorphism of `TopCat.sphere n` with the unit sphere of `E`, and by the inverse of
`TauCeti.singularHomologyComplSingletonIso`. -/
@[simp]
lemma singularHomologyComplSingletonIsoOfFinrankEq_inv {n : ℕ} (h : finrank ℝ E = n + 1) :
    haveI := Module.finite_of_finrank_eq_succ h
    (singularHomologyComplSingletonIsoOfFinrankEq R φ hx h).inv =
      (reducedSingularHomologyTopCatSphereIso R n).inv ≫
        (reducedSingularHomologyFunctor R n).map (TopCat.ofHom
          (((sphereHomeomorphOfFinrankEq
              (h.trans (finrank_euclideanSpace_ulift_fin.{w} (n + 1)).symm)).trans
            (diskBoundaryHomeomorph (n + 1)).symm : sphere (0 : E) 1 ≃ₜ TopCat.sphere.{w} n).symm :
            C(TopCat.sphere.{w} n, sphere (0 : E) 1))) ≫
          (singularHomologyComplSingletonIso R φ hx n).inv := by
  simp [singularHomologyComplSingletonIsoOfFinrankEq]
  -- `simp` leaves two coercions of the inverse homeomorphism to a continuous map.
  rfl

section StarConvex

/-! ### Local homology is constant along star-convex sets -/

variable {E : Type w} [NormedAddCommGroup E] [NormedSpace ℝ E] {K : Set E} {y : E}

/-- **Removing a bounded star-convex set does not change homology.** If `K` contains `y`, is
star-convex about `y` and is bounded, then the inclusion `(E, E ∖ K) ⟶ (E, E ∖ {y})` induces
isomorphisms on relative singular homology. Both `E ∖ K` and `E ∖ {y}` deformation retract onto a
sphere about `y` containing `K` in its interior (`StarConvex.complSphereHomotopyEquiv`), so the
inclusion induces isomorphisms on the homology of the subspaces, and the five lemma
`TopPair.isIso_singularHomologyMap_of_isIso` applies. -/
theorem isIso_singularHomologyMap_compl_of_starConvex (hK : StarConvex ℝ y K) (hy : y ∈ K)
    (hKb : Bornology.IsBounded K) (k : ℕ) :
    IsIso (TopPair.singularHomologyMap (TopPair.ofSubsetMap (𝟙 (TopCat.of E))
      (B := Kᶜ) (B' := {y}ᶜ) (Set.compl_subset_compl.2 (Set.singleton_subset_iff.2 hy))) R k) := by
  obtain ⟨r, hKr⟩ := (isBounded_iff_subset_ball y).1 hKb
  let e₁ := hK.complSphereHomotopyEquiv hy hKr
  let e₂ := (starConvex_singleton y).complSphereHomotopyEquiv rfl
    (Set.singleton_subset_iff.2 (hKr hy))
  set f := TopPair.ofSubsetMap (𝟙 (TopCat.of E)) (B := Kᶜ) (B' := {y}ᶜ)
    (Set.compl_subset_compl.2 (Set.singleton_subset_iff.2 hy))
  have hfst (n : ℕ) : IsIso (SSet.homologyMap (TopCat.toSSet.map (TopPair.Hom.fst f)) R n) := by
    have hf : TopPair.Hom.fst f = 𝟙 (TopCat.of E) := TopPair.ofSubsetMap_fst _ _
    have : IsIso (TopPair.Hom.fst f) := by
      rw [hf]
      exact IsIso.id (TopCat.of E)
    infer_instance
  have hsnd (n : ℕ) : IsIso (SSet.homologyMap (TopCat.toSSet.map (TopPair.Hom.snd f)) R n) := by
    -- The inclusion of the sphere into `E ∖ K`, followed by the inclusion into `E ∖ {y}`, is the
    -- inclusion of the sphere into `E ∖ {y}`; both sphere inclusions are homotopy equivalences.
    let g₁ : TopCat.of (sphere y r) ⟶ (TopPair.ofSubset (Kᶜ : Set (TopCat.of E))).snd :=
      TopCat.ofHom e₁.toFun
    let g₂ : TopCat.of (sphere y r) ⟶ (TopPair.ofSubset ({y}ᶜ : Set (TopCat.of E))).snd :=
      TopCat.ofHom e₂.toFun
    have hfac : g₁ ≫ TopPair.Hom.snd f = g₂ := by
      ext z
      rw [ConcreteCategory.comp_apply]
      exact Subtype.ext <| (TopPair.ofSubsetMap_snd_apply _ _ _).trans <|
        (hK.coe_complSphereHomotopyEquiv_apply hy hKr z).trans
          ((starConvex_singleton y).coe_complSphereHomotopyEquiv_apply rfl _ z).symm
    -- `((singularHomologyFunctor A n).obj R).map g` is `SSet.homologyMap (TopCat.toSSet.map g) R n`
    -- by definition of `singularChainComplexFunctor`, so the homotopy equivalences give
    -- isomorphisms in the latter form.
    have h₁ : IsIso (SSet.homologyMap (TopCat.toSSet.map g₁) R n) := by
      have := (e₁.singularHomologyIso R n).isIso_hom
      rw [ContinuousMap.HomotopyEquiv.singularHomologyIso_hom] at this
      exact this
    have h₂ : IsIso (SSet.homologyMap (TopCat.toSSet.map g₁) R n ≫
        SSet.homologyMap (TopCat.toSSet.map (TopPair.Hom.snd f)) R n) := by
      rw [← SSet.homologyMap_comp, ← Functor.map_comp, hfac]
      have := (e₂.singularHomologyIso R n).isIso_hom
      rw [ContinuousMap.HomotopyEquiv.singularHomologyIso_hom] at this
      exact this
    exact IsIso.of_isIso_comp_left (SSet.homologyMap (TopCat.toSSet.map g₁) R n) _
  exact TopPair.isIso_singularHomologyMap_of_isIso R f k (hfst k) (hsnd k) (fun m _ ↦ hfst m)
    fun m _ ↦ hsnd m

variable {M : Type w} [TopologicalSpace M] [T1Space M] (φ : OpenPartialHomeomorph M E) {x : M}

omit [NormedSpace ℝ E] [T1Space M] in
/-- The point `x` lies in `φ.symm '' K` when `φ x ∈ K`, so the identity of `M` maps
`M ∖ φ.symm '' K` into `M ∖ {x}`. -/
lemma _root_.OpenPartialHomeomorph.mapsTo_id_compl_symm_image (hx : x ∈ φ.source)
    (hxK : φ x ∈ K) : Set.MapsTo (𝟙 (TopCat.of M)) (φ.symm '' K)ᶜ {x}ᶜ :=
  Set.compl_subset_compl.2 (Set.singleton_subset_iff.2 ⟨φ x, hxK, φ.left_inv hx⟩)

/-- **Local homology is constant along a closed bounded star-convex set in a chart.** Let
`φ : M → E` be an open partial homeomorphism from a T₁ space to a real normed space, such as a
chart of a topological manifold, and let `K ⊆ φ.target` be closed, bounded and star-convex about
`φ x`, where `x ∈ φ.source` and `φ x ∈ K`, such that `φ.symm '' K` is closed in `M`. Then the
inclusion `(M, M ∖ φ.symm '' K) ⟶ (M, M ∖ {x})` induces isomorphisms on relative singular
homology. By excision onto the source and the target of `φ`, this reduces to the inclusion
`(E, E ∖ K) ⟶ (E, E ∖ {φ x})` (`TauCeti.isIso_singularHomologyMap_compl_of_starConvex`).

When `K` is compact, it is closed and bounded, and if `M` is moreover Hausdorff then its image
`φ.symm '' K` is compact and hence closed; star-convexity and `K ⊆ φ.target` remain separate
hypotheses. For instance, all hypotheses hold for a closed ball about `φ x` contained in the
target of a chart of a finite-dimensional Hausdorff manifold. -/
theorem isIso_singularHomologyMap_compl_of_chart (hx : x ∈ φ.source) (hK : StarConvex ℝ (φ x) K)
    (hxK : φ x ∈ K) (hKb : Bornology.IsBounded K) (hKc : IsClosed K)
    (hLc : IsClosed (φ.symm '' K)) (hKφ : K ⊆ φ.target) (k : ℕ) :
    IsIso (TopPair.singularHomologyMap (TopPair.ofSubsetMap (𝟙 (TopCat.of M))
      (φ.mapsTo_id_compl_symm_image hx hxK)) R k) := by
  have hLs : φ.symm '' K ⊆ φ.source := fun _ ⟨z, hz, h⟩ ↦ h ▸ φ.map_target (hKφ hz)
  have hL : ∀ z : TopCat.of φ.source, z ∈ (Subtype.val ⁻¹' (φ.symm '' K)ᶜ : Set φ.source) ↔
      φ.toHomeomorphSourceTarget z ∈ (Subtype.val ⁻¹' Kᶜ : Set φ.target) := fun z ↦ by
    rw [Set.mem_preimage, Set.mem_preimage, φ.symm_image_eq_source_inter_preimage hKφ]
    simp [z.2]
  have hy : ∀ z : TopCat.of φ.source, z ∈ (Subtype.val ⁻¹' {x}ᶜ : Set φ.source) ↔
      φ.toHomeomorphSourceTarget z ∈ (Subtype.val ⁻¹' {φ x}ᶜ : Set φ.target) :=
    fun z ↦ (φ.injOn.eq_iff z.2 hx).not.symm
  -- By excision, it suffices to treat the inclusions of complements in the source of `φ`; these
  -- are carried to the inclusions in the target by the homeomorphism of source and target, and
  -- those are invertible by excision in `E`.
  have hxL : x ∈ φ.symm '' K := ⟨φ x, hxK, φ.left_inv hx⟩
  rw [← TopPair.isIso_singularHomologyMap_ofSubsetMap_compl_iff R (X := TopCat.of M)
    φ.open_source hLc isClosed_singleton hLs (Set.singleton_subset_iff.2 hxL)]
  let fT := TopPair.ofSubsetMap (𝟙 (TopCat.of φ.target)) (B := Subtype.val ⁻¹' Kᶜ)
    (B' := Subtype.val ⁻¹' {φ x}ᶜ)
    fun _ hz ↦ Set.compl_subset_compl.2 (Set.singleton_subset_iff.2 hxK) hz
  have hT : IsIso (TopPair.singularHomologyMap fT R k) :=
    (TopPair.isIso_singularHomologyMap_ofSubsetMap_compl_iff R (X := TopCat.of E) φ.open_target
    hKc isClosed_singleton hKφ (Set.singleton_subset_iff.2 hxK) k).2
    (isIso_singularHomologyMap_compl_of_starConvex R hK hxK hKb k)
  refine IsIso.of_isIso_fac_right (f := TopPair.singularHomologyMap
    (TopPair.ofSubsetIso (X := TopCat.of φ.source) (Y := TopCat.of φ.target)
      φ.toHomeomorphSourceTarget hy).hom R k)
    (h := TopPair.singularHomologyMap (TopPair.ofSubsetIso (X := TopCat.of φ.source)
      (Y := TopCat.of φ.target) φ.toHomeomorphSourceTarget hL).hom R k ≫
        TopPair.singularHomologyMap fT R k) ?_
  rw [← TopPair.singularHomologyMap_comp, ← TopPair.singularHomologyMap_comp]
  congr 1
  rw [TopPair.ofSubsetIso_hom, TopPair.ofSubsetIso_hom]
  -- Both composites are `ofSubsetMap` of the homeomorphism of the source of `φ` with its target:
  -- `𝟙 ≫ g` and `g ≫ 𝟙` agree definitionally in `TopCat`, which the middle of `Eq.trans` uses.
  -- Rewriting with `Category.id_comp` is blocked because the `MapsTo` proofs depend on the map.
  have h : Set.MapsTo φ.toHomeomorphSourceTarget (Subtype.val ⁻¹' (φ.symm '' K)ᶜ : Set φ.source)
      (Subtype.val ⁻¹' {φ x}ᶜ) := fun z hz ↦ (hy z).1 (φ.mapsTo_id_compl_symm_image hx hxK hz)
  exact (TopPair.ofSubsetMap_comp (𝟙 (TopCat.of φ.source))
    (TopCat.ofHom (φ.toHomeomorphSourceTarget : C(φ.source, φ.target))) _ _ h).symm.trans
      (TopPair.ofSubsetMap_comp (TopCat.ofHom (φ.toHomeomorphSourceTarget : C(φ.source, φ.target)))
        (𝟙 (TopCat.of φ.target)) _ _ h)

/-- **Local homology along a closed bounded star-convex set vanishes outside the dimension**:
for `K` as in `TauCeti.isIso_singularHomologyMap_compl_of_chart` and `E` of finite dimension `n`,
the relative homology `Hₖ(M, M ∖ φ.symm '' K)` vanishes for `k ≠ n`. -/
theorem isZero_singularHomology_compl_symm_image_of_ne [FiniteDimensional ℝ E] {n k : ℕ}
    (hx : x ∈ φ.source) (hK : StarConvex ℝ (φ x) K) (hxK : φ x ∈ K)
    (hKb : Bornology.IsBounded K) (hKc : IsClosed K) (hLc : IsClosed (φ.symm '' K))
    (hKφ : K ⊆ φ.target) (h : finrank ℝ E = n) (hk : k ≠ n) :
    IsZero ((TopPair.ofSubset ((φ.symm '' K)ᶜ : Set (TopCat.of M))).singularHomology R k) :=
  have := isIso_singularHomologyMap_compl_of_chart R φ hx hK hxK hKb hKc hLc hKφ k
  (isZero_singularHomology_complSingleton_of_ne R φ hx h hk).of_iso
    (asIso (TopPair.singularHomologyMap (TopPair.ofSubsetMap (𝟙 (TopCat.of M))
      (φ.mapsTo_id_compl_symm_image hx hxK)) R k))

/-- **Local homology along a closed bounded star-convex set in the top degree**: for `K` as in
`TauCeti.isIso_singularHomologyMap_compl_of_chart` and `E` of dimension `n + 1`, the relative
homology `Hₙ₊₁(M, M ∖ φ.symm '' K)` is one copy of the coefficients. It is the map to the local
homology `Hₙ₊₁(M, M ∖ {x})` induced by the inclusion, followed by
`TauCeti.singularHomologyComplSingletonIsoOfFinrankEq`. -/
def singularHomologyComplSymmImageIsoOfFinrankEq {n : ℕ} (hx : x ∈ φ.source)
    (hK : StarConvex ℝ (φ x) K) (hxK : φ x ∈ K) (hKb : Bornology.IsBounded K) (hKc : IsClosed K)
    (hLc : IsClosed (φ.symm '' K)) (hKφ : K ⊆ φ.target) (h : finrank ℝ E = n + 1) :
    (TopPair.ofSubset ((φ.symm '' K)ᶜ : Set (TopCat.of M))).singularHomology R (n + 1) ≅ R :=
  have := isIso_singularHomologyMap_compl_of_chart R φ hx hK hxK hKb hKc hLc hKφ (n + 1)
  asIso (TopPair.singularHomologyMap (TopPair.ofSubsetMap (𝟙 (TopCat.of M))
      (φ.mapsTo_id_compl_symm_image hx hxK)) R (n + 1)) ≪≫
    singularHomologyComplSingletonIsoOfFinrankEq R φ hx h

/-- `TauCeti.singularHomologyComplSymmImageIsoOfFinrankEq` is the map induced by the inclusion
`(M, M ∖ φ.symm '' K) ⟶ (M, M ∖ {x})`, followed by
`TauCeti.singularHomologyComplSingletonIsoOfFinrankEq`. -/
@[simp]
lemma singularHomologyComplSymmImageIsoOfFinrankEq_hom {n : ℕ} (hx : x ∈ φ.source)
    (hK : StarConvex ℝ (φ x) K) (hxK : φ x ∈ K) (hKb : Bornology.IsBounded K) (hKc : IsClosed K)
    (hLc : IsClosed (φ.symm '' K)) (hKφ : K ⊆ φ.target) (h : finrank ℝ E = n + 1) :
    (singularHomologyComplSymmImageIsoOfFinrankEq R φ hx hK hxK hKb hKc hLc hKφ h).hom =
      TopPair.singularHomologyMap (TopPair.ofSubsetMap (𝟙 (TopCat.of M))
          (φ.mapsTo_id_compl_symm_image hx hxK)) R (n + 1) ≫
        (singularHomologyComplSingletonIsoOfFinrankEq R φ hx h).hom :=
  (rfl)

/-- The inverse of `TauCeti.singularHomologyComplSymmImageIsoOfFinrankEq` is the inverse of
`TauCeti.singularHomologyComplSingletonIsoOfFinrankEq`, followed by the inverse of the map induced
by the inclusion `(M, M ∖ φ.symm '' K) ⟶ (M, M ∖ {x})`. -/
@[simp]
lemma singularHomologyComplSymmImageIsoOfFinrankEq_inv {n : ℕ} (hx : x ∈ φ.source)
    (hK : StarConvex ℝ (φ x) K) (hxK : φ x ∈ K) (hKb : Bornology.IsBounded K) (hKc : IsClosed K)
    (hLc : IsClosed (φ.symm '' K)) (hKφ : K ⊆ φ.target) (h : finrank ℝ E = n + 1) :
    haveI := isIso_singularHomologyMap_compl_of_chart R φ hx hK hxK hKb hKc hLc hKφ (n + 1)
    (singularHomologyComplSymmImageIsoOfFinrankEq R φ hx hK hxK hKb hKc hLc hKφ h).inv =
      (singularHomologyComplSingletonIsoOfFinrankEq R φ hx h).inv ≫
        inv (TopPair.singularHomologyMap (TopPair.ofSubsetMap (𝟙 (TopCat.of M))
          (φ.mapsTo_id_compl_symm_image hx hxK)) R (n + 1)) :=
  (rfl)

/-- **Local homology along a closed bounded star-convex set in degree zero**: for `K` as in
`TauCeti.isIso_singularHomologyMap_compl_of_chart` and `E` of dimension `0`, the relative homology
`H₀(M, M ∖ φ.symm '' K)` is one copy of the coefficients. It is the map to the local homology
`H₀(M, M ∖ {x})` induced by the inclusion, followed by
`TauCeti.singularHomologyComplSingletonIsoOfFinrankEqZero`. -/
def singularHomologyComplSymmImageIsoOfFinrankEqZero [FiniteDimensional ℝ E] (hx : x ∈ φ.source)
    (hK : StarConvex ℝ (φ x) K) (hxK : φ x ∈ K) (hKb : Bornology.IsBounded K) (hKc : IsClosed K)
    (hLc : IsClosed (φ.symm '' K)) (hKφ : K ⊆ φ.target) (h : finrank ℝ E = 0) :
    (TopPair.ofSubset ((φ.symm '' K)ᶜ : Set (TopCat.of M))).singularHomology R 0 ≅ R :=
  have := isIso_singularHomologyMap_compl_of_chart R φ hx hK hxK hKb hKc hLc hKφ 0
  asIso (TopPair.singularHomologyMap (TopPair.ofSubsetMap (𝟙 (TopCat.of M))
      (φ.mapsTo_id_compl_symm_image hx hxK)) R 0) ≪≫
    singularHomologyComplSingletonIsoOfFinrankEqZero R φ hx h

/-- `TauCeti.singularHomologyComplSymmImageIsoOfFinrankEqZero` is the map induced by the inclusion
`(M, M ∖ φ.symm '' K) ⟶ (M, M ∖ {x})`, followed by
`TauCeti.singularHomologyComplSingletonIsoOfFinrankEqZero`. -/
@[simp]
lemma singularHomologyComplSymmImageIsoOfFinrankEqZero_hom [FiniteDimensional ℝ E]
    (hx : x ∈ φ.source) (hK : StarConvex ℝ (φ x) K) (hxK : φ x ∈ K)
    (hKb : Bornology.IsBounded K) (hKc : IsClosed K) (hLc : IsClosed (φ.symm '' K))
    (hKφ : K ⊆ φ.target) (h : finrank ℝ E = 0) :
    (singularHomologyComplSymmImageIsoOfFinrankEqZero R φ hx hK hxK hKb hKc hLc hKφ h).hom =
      TopPair.singularHomologyMap (TopPair.ofSubsetMap (𝟙 (TopCat.of M))
          (φ.mapsTo_id_compl_symm_image hx hxK)) R 0 ≫
        (singularHomologyComplSingletonIsoOfFinrankEqZero R φ hx h).hom :=
  (rfl)

/-- The inverse of `TauCeti.singularHomologyComplSymmImageIsoOfFinrankEqZero` is the inverse of
`TauCeti.singularHomologyComplSingletonIsoOfFinrankEqZero`, followed by the inverse of the map
induced by the inclusion `(M, M ∖ φ.symm '' K) ⟶ (M, M ∖ {x})`. -/
@[simp]
lemma singularHomologyComplSymmImageIsoOfFinrankEqZero_inv [FiniteDimensional ℝ E]
    (hx : x ∈ φ.source) (hK : StarConvex ℝ (φ x) K) (hxK : φ x ∈ K)
    (hKb : Bornology.IsBounded K) (hKc : IsClosed K) (hLc : IsClosed (φ.symm '' K))
    (hKφ : K ⊆ φ.target) (h : finrank ℝ E = 0) :
    haveI := isIso_singularHomologyMap_compl_of_chart R φ hx hK hxK hKb hKc hLc hKφ 0
    (singularHomologyComplSymmImageIsoOfFinrankEqZero R φ hx hK hxK hKb hKc hLc hKφ h).inv =
      (singularHomologyComplSingletonIsoOfFinrankEqZero R φ hx h).inv ≫
        inv (TopPair.singularHomologyMap (TopPair.ofSubsetMap (𝟙 (TopCat.of M))
          (φ.mapsTo_id_compl_symm_image hx hxK)) R 0) :=
  (rfl)

end StarConvex

end TauCeti
