/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.FieldTheory.KummerExtension
public import TauCeti.Algebra.Polynomial.XPowSubC
public import TauCeti.FieldTheory.Kummer.Character

/-!
# Radical extensions over a field with enough roots of unity

Let `K` be a field containing a primitive `n`-th root of unity `ζ`, and let `L = K(s)` with
`sⁿ = b` for some nonzero `b ∈ K`. The binomial `Xⁿ - b` need not be irreducible, so Mathlib's
`autEquivRootsOfUnity`, which identifies `Gal(L/K)` with `μₙ(K)` for an irreducible binomial,
does not apply. This file records what remains true in general: `L/K` is the splitting field of
`Xⁿ - b`, hence Galois, the degree `d = [L : K]` divides `n`, and `Gal(L/K)` is cyclic of order
`d`, generated by the automorphism `s ↦ ζ ^ (n / d) • s`.

This explicit generator is the one for which the Kummer character of `b`, read through `ζ`,
sends `g ^ i` to `(n / d) · i` for `0 ≤ i < d`; it is how the carry cocycle of a cyclic extension
is compared with the cup product of Kummer classes.

## Main results

* `TauCeti.isSplittingField_X_pow_sub_C_of_adjoin_eq_top`: `L = K(s)` is a splitting field of
  `Xⁿ - b`.
* `TauCeti.isGalois_of_pow_eq_of_adjoin_eq_top`: `L/K` is Galois.
* `TauCeti.exists_forall_mem_zpowers_apply_eq`: `[L : K]` divides `n`, and some `g` generating
  `Gal(L/K)` satisfies `g s = ζ ^ (n / [L : K]) • s`.

## References

* S. Lang, *Algebra*, Graduate Texts in Mathematics 211, Springer (2002), Chapter VI, §6.
-/

public section

open Polynomial IntermediateField Module

namespace TauCeti

variable {K L : Type*} [Field K] [Field L] [Algebra K L] {n : ℕ} [NeZero n] {ζ : K}
  (hζ : IsPrimitiveRoot ζ n) {b : K} {s : L}

include hζ in
/-- **A root of `Xⁿ - b` generating `L` makes `L` a splitting field of `Xⁿ - b`**, when `K`
contains a primitive `n`-th root of unity: the other roots are `ζ ^ i • s`. Mathlib's
`isSplittingField_X_pow_sub_C_of_root_adjoin_eq_top` is the case `n = [L : K]`. -/
theorem isSplittingField_X_pow_sub_C_of_adjoin_eq_top (hs : s ^ n = algebraMap K L b)
    (hgen : K⟮s⟯ = ⊤) : IsSplittingField K L (X ^ n - C b) := by
  constructor
  · rw [Polynomial.map_sub, Polynomial.map_pow, Polynomial.map_C, Polynomial.map_X]
    exact X_pow_sub_C_splits_of_isPrimitiveRoot (hζ.map_of_injective (algebraMap K L).injective) hs
  · rw [eq_top_iff, ← IntermediateField.top_toSubalgebra, ← hgen,
      IntermediateField.adjoin_simple_toSubalgebra_of_isAlgebraic
        (isAlgebraic_iff_isIntegral.2 ⟨_, monic_X_pow_sub_C b (NeZero.ne n), by
          rw [eval₂_sub, eval₂_X_pow, eval₂_C, hs, sub_self]⟩)]
    exact Algebra.adjoin_mono (Set.singleton_subset_iff.2
      ((Polynomial.mem_rootSet_X_pow_sub_C (NeZero.ne n)).2 hs))

include hζ in
/-- **A radical extension `K(ⁿ√b)` is Galois** when `K` contains a primitive `n`-th root of unity
and `b ≠ 0`: it is the splitting field of the separable binomial `Xⁿ - b`. -/
theorem isGalois_of_pow_eq_of_adjoin_eq_top (hb : b ≠ 0) (hs : s ^ n = algebraMap K L b)
    (hgen : K⟮s⟯ = ⊤) : IsGalois K L :=
  haveI := isSplittingField_X_pow_sub_C_of_adjoin_eq_top hζ hs hgen
  IsGalois.of_separable_splitting_field (separable_X_pow_sub_C b hζ.neZero'.out hb)

include hζ in
/-- **The canonical generator of a radical extension.** Let `L = K(s)` with `sⁿ = b ≠ 0`, and let
`ζ ∈ K` be a primitive `n`-th root of unity. Then `[L : K]` divides `n`, and `Gal(L/K)` is
generated by an automorphism `g` with `g s = ζ ^ (n / [L : K]) · s`. -/
theorem exists_forall_mem_zpowers_apply_eq [FiniteDimensional K L] (hb : b ≠ 0)
    (hs : s ^ n = algebraMap K L b) (hgen : K⟮s⟯ = ⊤) :
    ∃ g : L ≃ₐ[K] L, (∀ σ, σ ∈ Subgroup.zpowers g) ∧ finrank K L ∣ n ∧
      g s = algebraMap K L (ζ ^ (n / finrank K L)) * s := by
  have := isGalois_of_pow_eq_of_adjoin_eq_top hζ hb hs hgen
  have hs0 : s ≠ 0 := by
    rintro rfl
    rw [zero_pow (NeZero.ne n), eq_comm, map_eq_zero] at hs
    exact hb hs
  have hζL := hζ.map_of_injective (algebraMap K L).injective
  -- every automorphism moves `s` by an `n`-th root of unity, which lies in `K`
  have hroot (σ : L ≃ₐ[K] L) : ∃ i < n, algebraMap K L (ζ ^ i) = σ s / s := by
    obtain ⟨i, hi, h⟩ := hζL.eq_pow_of_pow_eq_one (ξ := σ s / s)
      (apply_div_pow_eq_one hs0 (by rw [hs, AlgEquiv.commutes]))
    exact ⟨i, hi, by rw [map_pow, h]⟩
  have hfix (σ τ : L ≃ₐ[K] L) : σ (τ s / s) = τ s / s := by
    obtain ⟨i, -, h⟩ := hroot τ
    rw [← h, AlgEquiv.commutes]
  let ψ : (L ≃ₐ[K] L) →* Lˣ :=
    { toFun := fun σ ↦ Units.mk0 (σ s / s) (div_ne_zero ((map_ne_zero σ).2 hs0) hs0)
      map_one' := Units.ext (by simp [hs0])
      map_mul' := fun σ τ ↦ Units.ext <| by
        have h : σ (τ s) = σ (τ s / s) * σ s := by rw [← map_mul, div_mul_cancel₀ _ hs0]
        simp only [AlgEquiv.mul_apply, Units.val_mk0, Units.val_mul, h, hfix]
        field_simp }
  have hψ (σ : L ≃ₐ[K] L) : (ψ σ : L) = σ s / s := rfl
  have hinj : Function.Injective ψ := fun σ τ h ↦ by
    have h' : σ s = τ s := by
      have := congrArg Units.val h
      rwa [hψ, hψ, div_left_inj' hs0] at this
    have htop : Algebra.adjoin K {s} = ⊤ := by
      rw [← IntermediateField.adjoin_simple_toSubalgebra_of_isAlgebraic
        (Algebra.IsAlgebraic.isAlgebraic s), hgen, IntermediateField.top_toSubalgebra]
    exact AlgEquiv.coe_toAlgHom_injective (AlgHom.ext_of_adjoin_eq_top htop
      (Set.eqOn_singleton.2 h'))
  set d := finrank K L
  have hG : Nat.card (L ≃ₐ[K] L) = d := IsGalois.card_aut_eq_finrank K L
  have hcard : Nat.card ψ.range = d :=
    (Nat.card_congr (MonoidHom.ofInjective hinj).toEquiv).symm.trans hG
  -- the image of `ψ` is the group of `d`-th roots of unity
  have hle (m : ℕ) (hm : d ∣ m) : ψ.range ≤ rootsOfUnity m L := by
    rintro _ ⟨σ, rfl⟩
    obtain ⟨k, rfl⟩ := hm
    rw [mem_rootsOfUnity, ← map_pow, pow_mul, ← hG, pow_card_eq_one', one_pow, map_one]
  have hd0 : d ≠ 0 := finrank_pos.ne'
  have hdn : d ∣ n := by
    have hlen : ψ.range ≤ rootsOfUnity n L := by
      rintro _ ⟨σ, rfl⟩
      rw [mem_rootsOfUnity, Units.ext_iff, Units.val_pow_eq_pow_val, hψ, Units.val_one]
      exact apply_div_pow_eq_one hs0 (by rw [hs, AlgEquiv.commutes])
    rw [← hcard, ← hζL.card_rootsOfUnity]
    exact Subgroup.card_dvd_of_le hlen
  have : NeZero d := ⟨hd0⟩
  have hrange : ψ.range = rootsOfUnity d L :=
    Subgroup.eq_of_le_of_card_ge (hle d dvd_rfl) (hcard ▸ card_rootsOfUnity L d)
  -- `ζ ^ (n / d)` is a primitive `d`-th root of unity
  have hω : IsPrimitiveRoot (algebraMap K L (ζ ^ (n / d))) d := by
    have h := hζL.pow_of_dvd (Nat.div_ne_zero_iff_of_dvd hdn |>.2 ⟨NeZero.ne n, hd0⟩)
      (Nat.div_dvd_of_dvd hdn)
    rwa [Nat.div_div_self hdn (NeZero.ne n), ← map_pow] at h
  obtain ⟨u, hu⟩ := hω.isUnit (NeZero.ne d)
  have hu' : u ∈ ψ.range := by
    rw [hrange, mem_rootsOfUnity, Units.ext_iff, Units.val_pow_eq_pow_val, hu, Units.val_one]
    exact hω.pow_eq_one
  obtain ⟨g, hg⟩ := hu'
  have hgs : g s / s = algebraMap K L (ζ ^ (n / d)) := by rw [← hψ, hg, hu]
  have hord : orderOf g = d := by
    rw [← orderOf_injective ψ hinj, hg, ← orderOf_units, hu, ← hω.eq_orderOf]
  refine ⟨g, fun σ ↦ ?_, hdn, (div_eq_iff hs0).1 hgs⟩
  rw [Subgroup.eq_top_of_card_eq (Subgroup.zpowers g) (by rw [Nat.card_zpowers, hord, hG])]
  exact Subgroup.mem_top σ

end TauCeti
