/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.FieldTheory.IntermediateField.Adjoin.Basic
public import Mathlib.FieldTheory.KummerPolynomial
public import Mathlib.RingTheory.Valuation.Discrete.IsDiscreteValuationRing
public import TauCeti.Algebra.Polynomial.XPowSubC
public import TauCeti.RingTheory.Valuation.Discrete.Order

/-!
# Binomial extensions and valuative irreducibility

Mathlib's Kummer theory of `X ^ n - C a` (in `Mathlib/FieldTheory/KummerExtension.lean`) runs
through a primitive `n`-th root of unity, which is unavailable for `n = 2` in characteristic `2`.
For `n = 2`, a single square root `δ` of `a` generates the root-set adjunction, because the only
other root is `-δ`. Discrete valuations give irreducibility and degree criteria for general
binomial extensions. Elementary root-set and splitting facts are in
`TauCeti.Algebra.Polynomial.XPowSubC`.

## Main results

* `IntermediateField.adjoin_rootSet_X_pow_two_sub_C`: a square root of `a` generates the root-set
  adjunction of `X ^ 2 - C a`.
* `Valuation.X_pow_sub_C_irreducible_of_gcd_ord_eq_one`: `X ^ n - C a` is irreducible when `n`
  is coprime to the order of `a` at a discrete valuation.
* `Valuation.finrank_eq_of_pow_eq_of_gcd_ord_eq_one`: a radical extension generated by a root
  of `X ^ n - C a` has degree `n` under the same coprimality condition.
* `TauCeti.X_pow_sub_C_irreducible_of_irreducible`: for a uniformizer `ϖ` of a discrete
  valuation ring, `X ^ n - C ϖ` is irreducible over the fraction field for every `n ≠ 0`.

## References

* H. Stichtenoth, *Algebraic Function Fields and Codes*, 2nd ed., GTM 254, Springer, 2009,
  Proposition 3.7.3.
-/

public section

open Polynomial

open scoped IntermediateField WithZero

namespace TauCeti

universe u v

section Adjoin

variable {F : Type u} [Field F] {E : Type v} [Field E] [Algebra F E] {a : F} {δ : E}

/-- Over a field, a square root `δ` of `a` generates the whole splitting field of `X ^ 2 - C a`,
because the only other root is `-δ`. -/
theorem _root_.IntermediateField.adjoin_rootSet_X_pow_two_sub_C
    (hδ : δ ^ 2 = algebraMap F E a) :
    IntermediateField.adjoin F (((X : F[X]) ^ 2 - C a).rootSet E) = F⟮δ⟯ := by
  have hmem : δ ∈ ((X : F[X]) ^ 2 - C a).rootSet E :=
    (Polynomial.mem_rootSet_X_pow_sub_C two_ne_zero).mpr hδ
  refine le_antisymm (IntermediateField.adjoin_le_iff.mpr fun x hx ↦ ?_)
    (IntermediateField.adjoin_simple_le_iff.mpr (IntermediateField.subset_adjoin F _ hmem))
  have hx' : x ^ 2 = algebraMap F E a := (Polynomial.mem_rootSet_X_pow_sub_C two_ne_zero).mp hx
  rcases sq_eq_sq_iff_eq_or_eq_neg.mp (hx'.trans hδ.symm) with h | h
  · exact h ▸ IntermediateField.mem_adjoin_simple_self F δ
  · exact h ▸ neg_mem (IntermediateField.mem_adjoin_simple_self F δ)

end Adjoin

section Valuation

variable {F : Type u} [Field F]

/-- **A valuative irreducibility criterion for `X ^ n - C a`**: if `n ≠ 0` is coprime to the
order of `a` at a discrete valuation `v`, then `X ^ n - C a` is irreducible. No root of unity and
no hypothesis on the characteristic is needed. For `a = 0` the order is the junk value `0`, so the
hypothesis forces `n = 1`, where the statement holds trivially. See Andrew Yang's
`X_pow_sub_C_irreducible_of_prime` in `Mathlib/FieldTheory/KummerPolynomial.lean`. -/
theorem _root_.Valuation.X_pow_sub_C_irreducible_of_gcd_ord_eq_one (v : Valuation F ℤᵐ⁰)
    {n : ℕ} (hn : n ≠ 0) {a : F} (h : Int.gcd n (v.ord a) = 1) :
    Irreducible (X ^ n - C a) := by
  have hpos : 0 < n := Nat.pos_of_ne_zero hn
  have hne : X ^ n - C a ≠ 0 := X_pow_sub_C_ne_zero hpos a
  have hnu : ¬IsUnit (X ^ n - C a) := by
    rw [Polynomial.isUnit_iff_degree_eq_zero, degree_X_pow_sub_C hpos, Nat.cast_eq_zero]
    exact hn
  obtain ⟨g, hg, hg'⟩ := WfDvdMonoid.exists_irreducible_factor hnu hne
  suffices natDegree g = n from (associated_of_dvd_of_natDegree_le hg' hne
    (this.trans natDegree_X_pow_sub_C.symm).ge).irreducible hg
  -- The norm `N` of a root of `g` satisfies `N ^ n = a ^ deg g`.
  have key : (Algebra.norm F (AdjoinRoot.root g)) ^ n = a ^ g.natDegree := by
    have := eval₂_eq_zero_of_dvd_of_eval₂_eq_zero _ _ hg' (AdjoinRoot.eval₂_root g)
    rw [eval₂_sub, eval₂_pow, eval₂_C, eval₂_X, sub_eq_zero] at this
    rw [← map_pow, this, ← AdjoinRoot.algebraMap_eq, Algebra.norm_algebraMap,
      (AdjoinRoot.powerBasis hg.ne_zero).finrank, AdjoinRoot.powerBasis_dim hg.ne_zero]
  -- Taking orders, `n` divides `deg g · ord_v a`, hence `deg g`.
  have hord : (n : ℤ) * v.ord (Algebra.norm F (AdjoinRoot.root g)) =
      g.natDegree * v.ord a := by
    rw [← Valuation.ord_pow, key, Valuation.ord_pow]
  have hdvd : (n : ℤ) ∣ g.natDegree :=
    Int.dvd_of_dvd_mul_left_of_gcd_one ⟨_, hord.symm⟩ h
  have hle : g.natDegree ≤ n :=
    (natDegree_le_of_dvd hg' hne).trans_eq natDegree_X_pow_sub_C
  have hdeg : 0 < g.natDegree := natDegree_pos_iff_degree_pos.mpr (degree_pos_of_irreducible hg)
  exact hle.antisymm (Nat.le_of_dvd hdeg (Int.natCast_dvd_natCast.mp hdvd))

/-- **The degree of a radical extension**: if `y` generates `E` over `F` with `y ^ n = a`,
and `n` is coprime to the order of `a` at a discrete valuation, then `[E : F] = n`.
This is the degree criterion used in Stichtenoth, Proposition 3.7.3. -/
theorem _root_.Valuation.finrank_eq_of_pow_eq_of_gcd_ord_eq_one
    {E : Type v} [Field E] [Algebra F E] (w : Valuation F ℤᵐ⁰)
    {y : E} {n : ℕ} {a : F} (htop : F⟮y⟯ = ⊤)
    (hy : y ^ n = algebraMap F E a) (hn : n ≠ 0)
    (h : Int.gcd n (w.ord a) = 1) : Module.finrank F E = n := by
  have hirr : Irreducible (X ^ n - C a) :=
    w.X_pow_sub_C_irreducible_of_gcd_ord_eq_one hn h
  have hroot : aeval y (X ^ n - C a) = 0 := by rw [map_sub, aeval_X_pow, aeval_C, hy, sub_self]
  have hint : IsIntegral F y := ⟨X ^ n - C a, monic_X_pow_sub_C a hn, by rwa [← aeval_def]⟩
  have hmin : X ^ n - C a = minpoly F y :=
    minpoly.eq_of_irreducible_of_monic hirr hroot (monic_X_pow_sub_C a hn)
  rw [← IntermediateField.finrank_top', ← htop, IntermediateField.adjoin.finrank hint, ← hmin,
    natDegree_X_pow_sub_C]

/-- **A uniformizer has no nontrivial root in the fraction field**: for a uniformizer `ϖ` of a
discrete valuation ring `R` and `n ≠ 0`, the polynomial `X ^ n - C ϖ` is irreducible over the
fraction field of `R`, as `ϖ` has order `1` at the valuation of the maximal ideal. -/
theorem X_pow_sub_C_irreducible_of_irreducible {R K : Type*} [CommRing R] [IsDomain R]
    [IsDiscreteValuationRing R] [Field K] [Algebra R K] [IsFractionRing R K] {ϖ : R}
    (hϖ : Irreducible ϖ) {n : ℕ} (hn : n ≠ 0) : Irreducible (X ^ n - C (algebraMap R K ϖ)) := by
  set v := IsDiscreteValuationRing.maximalIdeal R
  have hord : (v.valuation K).ord (algebraMap R K ϖ) = 1 := by
    rw [Valuation.ord_eq_iff_valuation_eq_exp_neg _ (by simpa using hϖ.ne_zero),
      IsDedekindDomain.HeightOneSpectrum.valuation_of_algebraMap,
      v.intValuation_singleton hϖ.ne_zero hϖ.maximalIdeal_eq]
  exact (v.valuation K).X_pow_sub_C_irreducible_of_gcd_ord_eq_one hn
    (by rw [hord, Int.gcd_one_right])

end Valuation

end TauCeti
