/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.FieldTheory.FunctionField.RiemannRoch.Genus

/-!
# Holomorphy rings of an algebraic function field

A set `S` of places of an algebraic function field `F / k` cuts out the ring

`𝒪_S = ⋂_{P ∈ S} 𝒪_P`

of functions regular at every place of `S` — its **holomorphy ring**.  Two extreme cases are
already known: `𝒪_∅ = F`, and `𝒪_{ℙ_F}` is the constant field `algebraicClosure k F`, which is
Stichtenoth's Corollary 1.1.20.  This file constructs `𝒪_S` in general and proves the two
theorems that make the construction a dictionary: `𝒪_S` is integrally closed in `F`, and
*every* `k`-subalgebra of `F` integrally closed in `F` arises this way, from the set of places
at which its functions are regular.  The two constructions are mutually inverse, since `S` is
recovered from `𝒪_S` as the set of places at which every function of `𝒪_S` is regular.

Whenever some place lies outside `S`, the field `F` is the field of fractions of `𝒪_S`, so a
holomorphy ring of a proper set of places is a `k`-subalgebra of `F` with the same function field
— the shape the affine models of `TauCeti/FieldTheory/FunctionField/AffineModel/` are built on.

When `S` is *finite*, `𝒪_S` is moreover a principal ideal domain, and so a Dedekind domain: a
nonzero ideal is generated by any of its functions of least order at every place of `S` at once,
and weak approximation manufactures such a function out of the functions of least order at the
separate places.  A finite `S` that omits some place is therefore the finite chart of the affine
model `𝒪_S`, whose height one primes are exactly the places of `S`; that identification is
`TauCeti.holomorphyRingHeightOneSpectrumEquiv`, in
`TauCeti/FieldTheory/FunctionField/AffineModel/Prime.lean` with the rest of the affine-model
dictionary.

The mathematics is Stichtenoth, *Algebraic Function Fields and Codes*, 2nd ed., Section III.2.
None of it needs an exactness hypothesis on the constant field.

## Main definitions

* `TauCeti.holomorphyRing`: the holomorphy ring `𝒪_S` of a set of places, as a `k`-subalgebra
  of `F`.

## Main results

* `TauCeti.isIntegrallyClosedIn_holomorphyRing`: a holomorphy ring is integrally closed in `F`.
* `TauCeti.holomorphyRing_setOf_subset_integers`: **Stichtenoth, Theorem 3.2.6** — a
  `k`-subalgebra of `F` integrally closed in `F` is the holomorphy ring of the set of places at
  which its functions are regular.
* `TauCeti.restrictScalars_integralClosure_eq_holomorphyRing`: the same theorem for an arbitrary
  `k`-subalgebra `R` of `F` — the integral closure of `R` in `F` is the holomorphy ring of the set
  of places at which the functions of `R` are regular.
* `TauCeti.coe_holomorphyRing_subset_integers_iff`: **Stichtenoth, Corollary 3.2.8** — the
  functions of `𝒪_S` are all regular at `P` exactly when `P ∈ S`, so `S` is recovered from
  `𝒪_S` and the two constructions are mutually inverse.
* `TauCeti.isFractionRing_holomorphyRing`: `F` is the field of fractions of `𝒪_S` as soon as
  some place lies outside `S`; in particular (`TauCeti.isFractionRing_holomorphyRing_setOf_mem`)
  of the ring of functions regular wherever a transcendental `x` is.
* `TauCeti.exists_pow_mul_mem_holomorphyRing`: a function regular at every place of `S` at which
  `x⁻¹` is regular, for some `x ∈ 𝒪_S`, is made regular on all of `S` by a power of `x`.
* `TauCeti.dvd_holomorphyRing_iff_forall_ord_le`: divisibility in `𝒪_S` is the pointwise
  comparison of orders along `S`.
* `TauCeti.isPrincipalIdealRing_holomorphyRing`: **Stichtenoth, Proposition 3.2.10** — the
  holomorphy ring of a finite set of places is a principal ideal domain.
* `TauCeti.forall_algebraMap_mem_integers_holomorphyRing_iff`: a place is finite on `𝒪_S`
  exactly when it belongs to `S`, in the form the affine-model dictionary consumes.

## Implementation notes

`𝒪_S` is a `Subalgebra k F` rather than a bare `Subring F`: the constants are regular at every
place (`TauCeti.Place.algebraMap_mem_integers`), so the `k`-algebra structure is free, and it is
what the affine-model API consumes.  Mathlib's `Set.integer`, the `S`-integers of the fraction
field of a Dedekind domain, is the same shape for the places of a fixed affine model and with the
complementary indexing convention (integrality is imposed *away* from `S`); it is not general
enough here, where the index is the whole place set of `F / k` and the place at infinity of a
model is a citizen like any other.

Theorem 3.2.6 does not repeat Stichtenoth's Zorn argument.  Mathlib's
`Subring.exists_le_valuationSubring_of_isIntegrallyClosedIn` (Stacks 090P) already separates an
element from a subring integrally closed in a field by a valuation subring; what is specific to
function fields is that the valuation subring so produced is a *place*, and that is
`TauCeti.Place.ofValuationSubring`.

## References

* H. Stichtenoth, *Algebraic Function Fields and Codes*, 2nd ed., GTM 254, Springer, 2009,
  Section III.2 (Definition 3.2.2, Theorem 3.2.6, Corollary 3.2.8, Proposition 3.2.10).
-/

public section

namespace TauCeti

open AlgebraicGeometry

universe u v

variable {k : Type u} {F : Type v} [Field k] [Field F] [Algebra k F]

/-! ### The holomorphy ring of a set of places -/

/-- The **holomorphy ring** `𝒪_S = ⋂_{P ∈ S} 𝒪_P` of a set `S` of places of `F / k`
(Stichtenoth, Definition 3.2.2): the functions regular at every place of `S`. -/
def holomorphyRing (S : Set (Place k F)) : Subalgebra k F where
  carrier := {z : F | ∀ P ∈ S, z ∈ P.integers}
  mul_mem' ha hb P hP := mul_mem (ha P hP) (hb P hP)
  one_mem' _ _ := one_mem _
  add_mem' ha hb P hP := add_mem (ha P hP) (hb P hP)
  zero_mem' _ _ := zero_mem _
  algebraMap_mem' c P _ := P.algebraMap_mem_integers c

@[simp]
theorem mem_holomorphyRing_iff {S : Set (Place k F)} {z : F} :
    z ∈ holomorphyRing S ↔ ∀ P ∈ S, z ∈ P.integers :=
  (Iff.rfl)

/-- Membership in `𝒪_S` in additive form: `z` has no pole on `S`. -/
theorem mem_holomorphyRing_iff_forall_ord_nonneg {S : Set (Place k F)} {z : F} :
    z ∈ holomorphyRing S ↔ ∀ P ∈ S, 0 ≤ P.ord z :=
  forall₂_congr fun P _ ↦ P.mem_integers_iff_ord_nonneg

/-- Every function of `𝒪_S` is regular at every place of `S`. -/
theorem coe_holomorphyRing_subset_integers {S : Set (Place k F)} {P : Place k F} (hP : P ∈ S) :
    (holomorphyRing S : Set F) ⊆ P.integers :=
  fun _ hz ↦ hz P hP

/-- Asking for regularity at more places gives a smaller ring. -/
theorem holomorphyRing_antitone :
    Antitone (holomorphyRing : Set (Place k F) → Subalgebra k F) :=
  fun _ _ hST _ hz P hP ↦ hz P (hST hP)

@[simp]
theorem holomorphyRing_empty : holomorphyRing (∅ : Set (Place k F)) = ⊤ := by
  ext z
  simp

/-- **The holomorphy ring of all the places is the constant field** (Stichtenoth,
Corollary 1.1.20): a function regular everywhere is algebraic over `k`. -/
@[simp]
theorem holomorphyRing_univ (hF : IsFunctionField k F) :
    holomorphyRing (Set.univ : Set (Place k F)) = (algebraicClosure k F).toSubalgebra := by
  ext z
  rw [mem_holomorphyRing_iff, IntermediateField.mem_toSubalgebra,
    Place.mem_algebraicClosure_iff_forall_mem_integers hF]
  simp

/-- **A holomorphy ring is integrally closed in `F`**: a function integral over `𝒪_S` is integral
over each `𝒪_P` with `P ∈ S`, and a valuation ring is integrally closed
(`TauCeti.Place.mem_integers_of_isIntegral`). -/
instance isIntegrallyClosedIn_holomorphyRing (S : Set (Place k F)) :
    IsIntegrallyClosedIn ↥(holomorphyRing S) F :=
  Subring.isIntegrallyClosedIn_iff.mpr fun {_} hz P hP ↦
    P.mem_integers_of_isIntegral (fun r ↦ r.2 P hP) hz

/-! ### The field of fractions -/

/-- **Denominators regular on `S`**: if some place `Q` lies outside `S`, every function of `F` is
`(y * z) / y` for a nonzero `y` with `y` and `y * z` both regular on `S`.  Riemann's theorem
supplies `y` inside `L(n·Q - (z)_∞)` for `n` large: such a `y` vanishes on the poles of `z` to at
least their order, and its own only pole is `Q`, which lies outside `S`. -/
theorem exists_ne_zero_mem_holomorphyRing_and_mul_mem (hF : IsFunctionField k F)
    {S : Set (Place k F)} {Q : Place k F} (hQ : Q ∉ S) (z : F) :
    ∃ y : F, y ≠ 0 ∧ y ∈ holomorphyRing S ∧ y * z ∈ holomorphyRing S := by
  rcases eq_or_ne z 0 with rfl | hz
  · exact ⟨1, one_ne_zero, one_mem _, by rw [mul_zero]; exact zero_mem _⟩
  set A : Divisor k F := Divisor.poles hF (Units.mk0 z hz) with hA
  have hAcoeff : ∀ P : Place k F, A.coeff P = -P.ord z ⊔ 0 := fun P ↦ by
    rw [hA, Divisor.coeff_poles, Units.val_mk0]
  obtain ⟨n, hn⟩ : ∃ n : ℕ, Divisor.degree A + genus k F ≤ (n : ℤ) :=
    ⟨(Divisor.degree A + genus k F).toNat, Int.self_le_toNat _⟩
  set D : Divisor k F := Finsupp.single Q (n : ℤ) - A with hD
  have hQdeg : (1 : ℤ) ≤ Q.degree := by
    exact_mod_cast Q.one_le_degree_of_isFunctionField hF
  have hsingle : ∀ P : Place k F, P ≠ Q →
      WeilDivisor.coeff (Finsupp.single Q (n : ℤ) : Divisor k F) P = 0 :=
    fun _ hPQ ↦ Finsupp.single_eq_of_ne hPQ
  have hDcoeff : ∀ P : Place k F, P ≠ Q → D.coeff P = -A.coeff P := fun P hPQ ↦ by
    rw [hD, WeilDivisor.coeff_sub, hsingle P hPQ, zero_sub]
  have hdim : 1 ≤ Divisor.dim D := by
    have hR := Divisor.degree_add_one_sub_genus_le_dim hF D
    rw [hD, Divisor.degree_sub, Divisor.degree_single] at hR
    have hmul : (n : ℤ) ≤ n * Q.degree :=
      le_mul_of_one_le_right (Int.natCast_nonneg n) hQdeg
    have h1 : (1 : ℤ) ≤ (Divisor.dim D : ℤ) := by linarith
    exact_mod_cast h1
  obtain ⟨y, hyD, hy0⟩ := Submodule.ne_bot_iff _ |>.1
    ((Divisor.one_le_dim_iff_riemannRochSpace_ne_bot hF D).mp hdim)
  have hyord : ∀ P : Place k F, P ∈ S → A.coeff P ≤ P.ord y := fun P hP ↦ by
    have hPQ : P ≠ Q := fun hPQ ↦ hQ (hPQ ▸ hP)
    have h := (mem_riemannRochSpace_iff_neg_le_ord hy0).mp hyD P
    rwa [hDcoeff P hPQ, neg_neg] at h
  refine ⟨y, hy0, mem_holomorphyRing_iff_forall_ord_nonneg.mpr fun P hP ↦ ?_,
    mem_holomorphyRing_iff_forall_ord_nonneg.mpr fun P hP ↦ ?_⟩
  · have h1 := hyord P hP
    have h2 := hAcoeff P
    omega
  · rw [P.ord_mul hy0 hz]
    have h1 := hyord P hP
    have h2 := hAcoeff P
    omega

/-- **`F` is the field of fractions of `𝒪_S`** whenever some place lies outside `S`
(Stichtenoth, Section III.2). -/
theorem isFractionRing_holomorphyRing (hF : IsFunctionField k F) {S : Set (Place k F)}
    (hS : Sᶜ.Nonempty) : IsFractionRing ↥(holomorphyRing S) F where
  map_units y :=
    (Units.mk0 (y : F) fun h ↦ nonZeroDivisors.ne_zero y.2 (Subtype.ext h)).isUnit
  surj z := by
    obtain ⟨Q, hQ⟩ := hS
    obtain ⟨y, hy0, hyS, hyzS⟩ := exists_ne_zero_mem_holomorphyRing_and_mul_mem hF hQ z
    refine ⟨⟨⟨y * z, hyzS⟩, ⟨⟨y, hyS⟩, mem_nonZeroDivisors_of_ne_zero fun h ↦ hy0 ?_⟩⟩, ?_⟩
    · exact congrArg Subtype.val h
    · exact mul_comm z y
  exists_of_eq h := ⟨1, by simpa using Subtype.ext h⟩

/-- **`F` is the field of fractions of `𝒪_x`**, the ring of functions regular wherever `x` is, for
`x` transcendental over `k`: `x` has a pole, which lies outside the places at which `x` is
regular. -/
theorem isFractionRing_holomorphyRing_setOf_mem (hF : IsFunctionField k F) {x : F}
    (hx : Transcendental k x) :
    IsFractionRing ↥(holomorphyRing {P : Place k F | x ∈ P.integers}) F := by
  obtain ⟨P, hP⟩ := Place.exists_ord_neg hF hx
  exact isFractionRing_holomorphyRing hF
    ⟨P, fun h ↦ (P.mem_integers_iff_ord_nonneg.mp h).not_gt hP⟩

/-! ### Clearing poles by a power of a function -/

/-- A function regular at every place of `S` at which `x⁻¹` is regular is made regular on all of
`S` by a sufficiently high power of `x ∈ 𝒪_S`: its poles on `S` are among the finitely many zeros
of `x`. -/
theorem exists_pow_mul_mem_holomorphyRing (hF : IsFunctionField k F) {S : Set (Place k F)}
    {x : F} (hx : x ∈ holomorphyRing S) {z : F}
    (hz : ∀ P ∈ S, x⁻¹ ∈ P.integers → z ∈ P.integers) :
    ∃ n : ℕ, x ^ n * z ∈ holomorphyRing S := by
  rcases eq_or_ne x 0 with rfl | hx0
  · exact ⟨0, by simpa using fun P hP ↦ hz P hP (by simp)⟩
  rcases eq_or_ne z 0 with rfl | hz0
  · exact ⟨0, by simp⟩
  classical
  have hT : {P : Place k F | P.ord z < 0}.Finite := Place.finite_setOf_ord_neg hF z
  set n : ℕ := hT.toFinset.sup fun P ↦ (-P.ord z).toNat
  refine ⟨n, mem_holomorphyRing_iff_forall_ord_nonneg.mpr fun P hP ↦ ?_⟩
  have hxP : 0 ≤ P.ord x := mem_holomorphyRing_iff_forall_ord_nonneg.mp hx P hP
  rw [P.ord_mul (pow_ne_zero n hx0) hz0, P.ord_pow]
  rcases le_or_gt 0 (P.ord z) with hzP | hzP
  · exact add_nonneg (mul_nonneg (Nat.cast_nonneg n) hxP) hzP
  -- `P` is a pole of `z`, hence a zero of `x`, and `n` was chosen to absorb it.
  have hxpos : 0 < P.ord x := by
    by_contra h
    have hxinv : x⁻¹ ∈ P.integers := by
      rw [P.mem_integers_iff_ord_nonneg, P.ord_inv]
      omega
    have := P.mem_integers_iff_ord_nonneg.mp (hz P hP hxinv)
    omega
  have hle : (-P.ord z).toNat ≤ n :=
    Finset.le_sup (f := fun P : Place k F ↦ (-P.ord z).toNat) (hT.mem_toFinset.mpr hzP)
  have h1 : ((-P.ord z).toNat : ℤ) = -P.ord z := Int.toNat_of_nonneg (by omega)
  have h3 : (n : ℤ) ≤ n * P.ord x := le_mul_of_one_le_right (Nat.cast_nonneg n) hxpos
  linarith

/-! ### Integrally closed subrings are holomorphy rings -/

/-- **Stichtenoth, Theorem 3.2.6.**  A `k`-subalgebra of `F` that is integrally closed in `F` is
the holomorphy ring of the set of places at which all of its functions are regular.  No hypothesis
on the constant field is needed.

A function outside `R` is separated from `R` by a valuation subring of `F`
(`Subring.exists_le_valuationSubring_of_isIntegrallyClosedIn`), which contains the constants and
is proper, hence is the valuation ring of a place. -/
theorem holomorphyRing_setOf_subset_integers (hF : IsFunctionField k F) (R : Subalgebra k F)
    [IsIntegrallyClosedIn ↥R F] :
    holomorphyRing {P : Place k F | (R : Set F) ⊆ P.integers} = R := by
  refine le_antisymm (fun z hz ↦ ?_) fun z hz P hP ↦ hP hz
  by_contra hzR
  have : IsIntegrallyClosedIn ↥R.toSubring F := inferInstanceAs (IsIntegrallyClosedIn ↥R F)
  obtain ⟨V, hRV, hzV⟩ :=
    Subring.exists_le_valuationSubring_of_isIntegrallyClosedIn (R := R.toSubring) hzR
  have hk : ∀ c : k, algebraMap k F c ∈ V := fun c ↦ hRV (R.algebraMap_mem c)
  have hV : V ≠ ⊤ := fun h ↦ hzV (h ▸ ValuationSubring.mem_top _)
  have hmem : (R : Set F) ⊆ (Place.ofValuationSubring hF hk hV).integers := by
    rw [Place.integers_ofValuationSubring]
    exact fun x hx ↦ hRV hx
  exact hzV (Place.integers_ofValuationSubring hF hk hV ▸ hz _ hmem)

/-- **Stichtenoth, Theorem 3.2.6**, for an arbitrary `k`-subalgebra: the integral closure of `R`
in `F` is the holomorphy ring of the set of places at which all the functions of `R` are regular. -/
theorem restrictScalars_integralClosure_eq_holomorphyRing (hF : IsFunctionField k F)
    (R : Subalgebra k F) :
    (integralClosure R F).restrictScalars k =
      holomorphyRing {P : Place k F | (R : Set F) ⊆ P.integers} := by
  have : IsIntegrallyClosedIn ↥((integralClosure R F).restrictScalars k) F :=
    inferInstanceAs (IsIntegrallyClosedIn ↥(integralClosure R F) F)
  rw [← holomorphyRing_setOf_subset_integers hF ((integralClosure R F).restrictScalars k)]
  congr 1
  ext P
  refine ⟨fun h z hz ↦ h ((integralClosure R F).algebraMap_mem ⟨z, hz⟩), fun h z hz ↦ ?_⟩
  exact P.mem_integers_of_isIntegral (fun r ↦ h r.2) hz

/-! ### Recovering the set of places -/

/-- **Stichtenoth, Corollary 3.2.8.**  The functions of `𝒪_S` are all regular at a place `P`
exactly when `P` belongs to `S`, so `S` is recovered from its holomorphy ring: together with
`TauCeti.holomorphyRing_setOf_subset_integers` this makes sets of places and `k`-subalgebras of
`F` integrally closed in `F` correspond antitonely. -/
@[simp]
theorem coe_holomorphyRing_subset_integers_iff (hF : IsFunctionField k F)
    {S : Set (Place k F)} {P : Place k F} :
    (holomorphyRing S : Set F) ⊆ P.integers ↔ P ∈ S := by
  refine ⟨fun h ↦ by_contra fun hP ↦ ?_, coe_holomorphyRing_subset_integers⟩
  obtain ⟨z, hz1, hz2⟩ := Place.exists_ord_neg_and_forall_ne_ord_nonneg hF P
  have hzS : z ∈ holomorphyRing S :=
    mem_holomorphyRing_iff_forall_ord_nonneg.mpr fun Q hQ ↦ hz2 Q fun h ↦ hP (h ▸ hQ)
  have hzP := h hzS
  rw [SetLike.mem_coe, P.mem_integers_iff_ord_nonneg] at hzP
  omega

/-! ### Finitely many places: a principal ideal domain -/

section Principal

variable {S : Set (Place k F)}

/-- The functions of `𝒪_S` have nonnegative order at every place of `S`. -/
theorem ord_nonneg_of_mem_holomorphyRing {P : Place k F} (hP : P ∈ S)
    (z : ↥(holomorphyRing S)) : 0 ≤ P.ord (z : F) :=
  mem_holomorphyRing_iff_forall_ord_nonneg.mp z.2 P hP

/-- **Divisibility in `𝒪_S` is a pointwise comparison of orders**: a nonzero function of `𝒪_S`
divides another exactly when it vanishes to no greater order at every place of `S`.  The
hypotheses exclude the junk value `ord_P 0 = 0`; `0` is of course divisible by everything. -/
theorem dvd_holomorphyRing_iff_forall_ord_le {t z : ↥(holomorphyRing S)} (ht : (t : F) ≠ 0)
    (hz : (z : F) ≠ 0) : t ∣ z ↔ ∀ P ∈ S, P.ord (t : F) ≤ P.ord (z : F) := by
  constructor
  · rintro ⟨w, rfl⟩ P hP
    have hw : (w : F) ≠ 0 := fun h ↦ hz (by rw [Subalgebra.coe_mul, h, mul_zero])
    rw [Subalgebra.coe_mul, P.ord_mul ht hw]
    have := ord_nonneg_of_mem_holomorphyRing hP w
    omega
  · intro h
    have hmem : (z : F) / (t : F) ∈ holomorphyRing S :=
      mem_holomorphyRing_iff_forall_ord_nonneg.mpr fun P hP ↦ by
        rw [P.ord_div hz ht]
        have := h P hP
        omega
    exact ⟨⟨_, hmem⟩, Subtype.ext (by rw [Subalgebra.coe_mul]; field_simp)⟩

/-- **A nonzero ideal of `𝒪_S` contains a function of least order at a given place of `S`**: the
orders of the nonzero functions of the ideal at `P` form a nonempty set of nonnegative integers,
so it has a least element, realized by some function of the ideal.  A step of Stichtenoth's
Proposition 3.2.10, not part of the holomorphy-ring API. -/
private theorem exists_mem_ideal_ord_le {P : Place k F} (hP : P ∈ S)
    {I : Ideal ↥(holomorphyRing S)}
    (hI : I ≠ ⊥) : ∃ z ∈ I, (z : F) ≠ 0 ∧
      ∀ w ∈ I, (w : F) ≠ 0 → P.ord (z : F) ≤ P.ord (w : F) := by
  obtain ⟨z₀, hz₀I, hz₀⟩ := Submodule.ne_bot_iff I |>.mp hI
  have hz₀F : (z₀ : F) ≠ 0 := fun h ↦ hz₀ (Subtype.ext h)
  have hne : {m : ℕ | ∃ z ∈ I, (z : F) ≠ 0 ∧ P.ord (z : F) = m}.Nonempty :=
    ⟨_, z₀, hz₀I, hz₀F, (Int.toNat_of_nonneg (ord_nonneg_of_mem_holomorphyRing hP z₀)).symm⟩
  obtain ⟨z, hzI, hz, hzord⟩ := Nat.sInf_mem hne
  refine ⟨z, hzI, hz, fun w hwI hw ↦ ?_⟩
  have hw' : (P.ord (w : F)).toNat ∈ {m : ℕ | ∃ z ∈ I, (z : F) ≠ 0 ∧ P.ord (z : F) = m} :=
    ⟨w, hwI, hw, (Int.toNat_of_nonneg (ord_nonneg_of_mem_holomorphyRing hP w)).symm⟩
  have hle := Nat.sInf_le hw'
  have := ord_nonneg_of_mem_holomorphyRing hP w
  omega

/-- **A nonzero ideal of the holomorphy ring of a finite set of places contains a function of
least order at every place of `S` at once**, which is the heart of Stichtenoth's
Proposition 3.2.10 and, like the previous lemma, a step of it rather than part of the
holomorphy-ring API.  Weak approximation (`TauCeti.Place.exists_ne_zero_forall_mem_ord_eq`)
combines the functions of least order at the separate places of `S` into a single one, by damping
all but one summand at each place. -/
private theorem exists_mem_ideal_forall_ord_le (hS : S.Finite) {I : Ideal ↥(holomorphyRing S)}
    (hI : I ≠ ⊥) : ∃ t ∈ I, (t : F) ≠ 0 ∧
      ∀ P ∈ S, ∀ z ∈ I, (z : F) ≠ 0 → P.ord (t : F) ≤ P.ord (z : F) := by
  classical
  obtain ⟨z₀, hz₀I, hz₀⟩ := Submodule.ne_bot_iff I |>.mp hI
  have hz₀F : (z₀ : F) ≠ 0 := fun h ↦ hz₀ (Subtype.ext h)
  -- at each place of `S`, a function of `I` of least order there
  have key : ∀ P : Place k F, ∃ z : ↥(holomorphyRing S), z ∈ I ∧ (z : F) ≠ 0 ∧
      (P ∈ S → ∀ w ∈ I, (w : F) ≠ 0 → P.ord (z : F) ≤ P.ord (w : F)) := by
    intro P
    by_cases hP : P ∈ S
    · obtain ⟨z, hzI, hz, hzmin⟩ := exists_mem_ideal_ord_le hP hI
      exact ⟨z, hzI, hz, fun _ ↦ hzmin⟩
    · exact ⟨z₀, hz₀I, hz₀F, fun h ↦ absurd h hP⟩
  choose z hzI hz hzmin using key
  rcases hS.toFinset.eq_empty_or_nonempty with hempty | ⟨Q₀, hQ₀⟩
  · exact ⟨z₀, hz₀I, hz₀F, fun P hP ↦
      absurd (hS.mem_toFinset.mpr hP) (by simp [hempty])⟩
  -- a damping factor: a unit at one place of `S`, a zero at each of the others
  have hdamp : ∀ P : Place k F, ∃ u : F, u ≠ 0 ∧ P.ord u = 0 ∧
      ∀ Q ∈ hS.toFinset, Q ≠ P → Q.ord u = 1 := by
    intro P
    obtain ⟨u, hu0, hu⟩ := Place.exists_ne_zero_forall_mem_ord_eq (insert P hS.toFinset)
      fun Q ↦ if Q = P then 0 else 1
    refine ⟨u, hu0, by simpa using hu P (Finset.mem_insert_self _ _), fun Q hQ hQP ↦ ?_⟩
    simpa [hQP] using hu Q (Finset.mem_insert_of_mem hQ)
  choose u hu0 huP huQ using hdamp
  have huS : ∀ P : Place k F, u P ∈ holomorphyRing S := fun P ↦
    mem_holomorphyRing_iff_forall_ord_nonneg.mpr fun Q hQ ↦ by
      rcases eq_or_ne Q P with rfl | hQP
      · exact (huP Q).ge
      · rw [huQ P Q (hS.mem_toFinset.mpr hQ) hQP]
        norm_num
  have hf0 : ∀ P : Place k F, u P * (z P : F) ≠ 0 := fun P ↦ mul_ne_zero (hu0 P) (hz P)
  -- away from `Q`, every summand is damped below the one indexed by `Q`
  have hlt : ∀ Q ∈ hS.toFinset, ∀ P ∈ hS.toFinset, P ≠ Q →
      Q.ord (u Q * (z Q : F)) < Q.ord (u P * (z P : F)) := by
    intro Q hQ P _ hPQ
    rw [Q.ord_mul (hu0 Q) (hz Q), Q.ord_mul (hu0 P) (hz P), huP Q,
      huQ P Q hQ fun h ↦ hPQ h.symm]
    have := hzmin Q (hS.mem_toFinset.mp hQ) (z P) (hzI P) (hz P)
    omega
  have hord : ∀ Q ∈ hS.toFinset,
      Q.ord (∑ P ∈ hS.toFinset, u P * (z P : F)) = Q.ord (z Q : F) := by
    intro Q hQ
    rw [Q.ord_sum_eq_of_forall_lt (f := fun P ↦ u P * (z P : F)) hQ (hf0 Q) (hlt Q hQ),
      Q.ord_mul (hu0 Q) (hz Q), huP Q, zero_add]
  have hsum : ((∑ P ∈ hS.toFinset, (⟨u P, huS P⟩ * z P : ↥(holomorphyRing S)) : _) : F) =
      ∑ P ∈ hS.toFinset, u P * (z P : F) := by
    rw [AddSubmonoidClass.coe_finsetSum]
    exact Finset.sum_congr rfl fun P _ ↦ Subalgebra.coe_mul _ _ _
  refine ⟨∑ P ∈ hS.toFinset, ⟨u P, huS P⟩ * z P, Ideal.sum_mem _ fun P _ ↦
    Ideal.mul_mem_left _ _ (hzI P), ?_, ?_⟩
  · rw [hsum]
    exact Q₀.sum_ne_zero_of_forall_ord_lt (f := fun P ↦ u P * (z P : F)) hQ₀
      (hf0 Q₀) (hlt Q₀ hQ₀)
  · intro P hP w hwI hw
    rw [hsum, hord P (hS.mem_toFinset.mpr hP)]
    exact hzmin P hP w hwI hw

/-- **Stichtenoth, Proposition 3.2.10**: the holomorphy ring of a *finite* set `S` of places of
`F / k` is a principal ideal domain.  Only the finiteness of `S` is used — weak approximation at
finitely many distinct places needs no hypothesis on `k` or on `F / k` — so this does not ask
`F / k` to be an algebraic function field.  A nonzero ideal is generated by any of its functions
of least order at every place of `S` at once, which weak approximation manufactures out of the
functions of least order at the separate places, since `𝒪_S` is then divided by such a function
(`TauCeti.dvd_holomorphyRing_iff_forall_ord_le`).  In particular `𝒪_S` is a Dedekind domain, by
`IsPrincipalIdealRing.isDedekindDomain`, and so — with `TauCeti.isFractionRing_holomorphyRing` —
an affine model, whose height one primes are the places of `S`; that is
`holomorphyRingHeightOneSpectrumEquiv`, downstream in
`TauCeti/FieldTheory/FunctionField/AffineModel/Prime.lean`. -/
theorem isPrincipalIdealRing_holomorphyRing (hS : S.Finite) :
    IsPrincipalIdealRing ↥(holomorphyRing S) where
  principal I := by
    rcases eq_or_ne I ⊥ with rfl | hI
    · exact ⟨0, by simp⟩
    obtain ⟨t, htI, ht, hmin⟩ := exists_mem_ideal_forall_ord_le hS hI
    refine ⟨t, le_antisymm (fun w hw ↦ ?_) ?_⟩
    · rcases eq_or_ne (w : F) 0 with hw0 | hw0
      · have hw0' : w = 0 := Subtype.ext hw0
        rw [hw0']
        exact zero_mem _
      · exact Ideal.mem_span_singleton.mpr
          ((dvd_holomorphyRing_iff_forall_ord_le ht hw0).mpr fun P hP ↦ hmin P hP w hw hw0)
    · rw [Ideal.span_le, Set.singleton_subset_iff]
      exact htI

end Principal

/-! ### Holomorphy rings as affine models -/

section AffineModel

variable {S : Set (Place k F)}

/-- A place of `F / k` is finite on `𝒪_S` exactly when it belongs to `S`
(`TauCeti.coe_holomorphyRing_subset_integers_iff`, in the form the affine-model dictionary
consumes).  It is deliberately not a `simp` lemma: `simp` unfolds both `TauCeti.holomorphyRing`
membership and `TauCeti.Place.integers` membership into valuation inequalities, so this left-hand
side is not in `simp` normal form. -/
theorem forall_algebraMap_mem_integers_holomorphyRing_iff (hF : IsFunctionField k F)
    {P : Place k F} :
    (∀ r : ↥(holomorphyRing S), algebraMap (↥(holomorphyRing S)) F r ∈ P.integers) ↔ P ∈ S := by
  refine ⟨fun h ↦ (coe_holomorphyRing_subset_integers_iff hF).mp fun z hz ↦ h ⟨z, hz⟩,
    fun h r ↦ ?_⟩
  exact coe_holomorphyRing_subset_integers h r.2

end AffineModel

end TauCeti
