/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Geometry.Toric.Algebraic.Regular

/-!
# The standard affine ray cone and its fan

The positive ray in the standard rank-one lattice is regular. Its primitive generator is the
single standard integral basis vector. Its faces form the standard affine-line fan, used as a
factor of the affine-plane fan.

## Main declarations

* `TauCeti.Toric.affineRayCone`: the positive standard ray.
* `TauCeti.Toric.isRegularCone_affineRayCone`: regularity for the standard integer lattice.
* `TauCeti.Toric.affineRayFan`: the finite fan of faces of the positive ray.

## References

* W. Fulton, *Introduction to Toric Varieties*, §1.2.
* D. Cox, J. Little and H. Schenck, *Toric Varieties*, §1.2.
-/

public section

namespace TauCeti.Toric

/-- The positive ray in the standard rank-one real vector space. -/
def affineRayCone : PointedCone ℝ (Fin 1 → ℝ) := PointedCone.hull ℝ {1}

/-- The affine ray is generated by the positive standard basis vector. -/
theorem affineRayCone_def : affineRayCone = PointedCone.hull ℝ {1} := (rfl)

private theorem standardBasis_apply (j : Fin 1) : Pi.basisFun ℤ (Fin 1) j = 1 := by
  ext k
  simp [Pi.basisFun_apply, Subsingleton.elim k j]

private theorem intCast_one :
    ((Int.castAddHom ℝ).compLeft (Fin 1)) (1 : Fin 1 → ℤ) = 1 := by
  ext j
  simp

/-- The positive rank-one ray is a regular cone for the standard integer lattice. -/
theorem isRegularCone_affineRayCone :
    IsRegularCone ((Int.castAddHom ℝ).compLeft (Fin 1)) affineRayCone := by
  have hv : IsPrimitive (1 : Fin 1 → ℤ) := by
    simpa only [standardBasis_apply] using (Pi.basisFun ℤ (Fin 1)).isPrimitive 0
  simpa only [affineRayCone_def, intCast_one] using
    isRegularCone_hull_singleton (isIntegralLattice_intCast 1) hv

/-- The standard fan of the affine line consists of the faces of the positive ray. -/
abbrev affineRayFan : Fan ((Int.castAddHom ℝ).compLeft (Fin 1)) :=
  Fan.ofCone (isIntegralLattice_intCast 1) isRegularCone_affineRayCone.toIsToricCone

/-- The standard affine-line fan has exactly the faces of the positive ray. -/
theorem mem_affineRayFan_cones {σ : PointedCone ℝ (Fin 1 → ℝ)} :
    σ ∈ affineRayFan.cones ↔ σ.IsFaceOf affineRayCone := by
  exact Fan.mem_ofCone_cones (isIntegralLattice_intCast 1)
    isRegularCone_affineRayCone.toIsToricCone

/-- The support of the affine-line fan is its positive ray. -/
theorem support_affineRayFan : affineRayFan.support = affineRayCone :=
  Fan.support_ofCone (isIntegralLattice_intCast 1) isRegularCone_affineRayCone.toIsToricCone

/-- The maximal cone of the standard affine-line fan. -/
abbrev affineRayFanMaxCone : affineRayFan.cones :=
  ⟨affineRayCone, mem_affineRayFan_cones.mpr (PointedCone.IsFaceOf.refl _)⟩

@[simp]
theorem coe_affineRayFanMaxCone :
    (affineRayFanMaxCone : PointedCone ℝ (Fin 1 → ℝ)) = affineRayCone := (rfl)

/-- The standard affine-line fan is regular. -/
theorem isRegular_affineRayFan : affineRayFan.IsRegular :=
  Fan.isRegular_ofCone (isIntegralLattice_intCast 1) isRegularCone_affineRayCone

end TauCeti.Toric
