/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Geometry.Toric.Algebraic.Examples.AffineRay
public import TauCeti.Geometry.Toric.Algebraic.Fan.Basic

/-!
# The fan of the projective line

The positive and negative rays in the standard rank-one lattice, together with their common
zero face, form a complete regular fan. Its two maximal affine charts are the standard affine
lines used to construct the projective line.

## References

* W. Fulton, *Introduction to Toric Varieties*, §1.4.
* D. Cox, J. Little and H. Schenck, *Toric Varieties*, §3.1.
-/

public section

namespace TauCeti.Toric

/-- The negative ray in the standard rank-one real vector space. -/
def negativeRayCone : PointedCone ℝ (Fin 1 → ℝ) :=
  PointedCone.hull ℝ {-(1 : Fin 1 → ℝ)}

/-- The negative ray is the cone generated by the negative standard basis vector. -/
theorem negativeRayCone_def :
    negativeRayCone = PointedCone.hull ℝ {-(1 : Fin 1 → ℝ)} := (rfl)

/-- Membership in the negative standard ray is nonpositivity of its sole coordinate. -/
@[simp] theorem mem_negativeRayCone_iff (x : Fin 1 → ℝ) :
    x ∈ negativeRayCone ↔ x 0 ≤ 0 := by
  rw [negativeRayCone_def, PointedCone.mem_hull_singleton]
  constructor
  · rintro ⟨r, hr, rfl⟩
    simpa using neg_nonpos.mpr hr
  · intro hx
    refine ⟨-(x 0), neg_nonneg.mpr hx, ?_⟩
    ext j
    simp [Subsingleton.elim j 0]

/-- The negative standard ray is regular. -/
theorem isRegularCone_negativeRayCone :
    IsRegularCone ((Int.castAddHom ℝ).compLeft (Fin 1)) negativeRayCone := by
  have hv : IsPrimitive (-(1 : Fin 1 → ℤ)) := by
    simpa only [basisFun_finOne_eq_one] using
      (Pi.basisFun ℤ (Fin 1)).isPrimitive 0 |>.neg
  have hi : ((Int.castAddHom ℝ).compLeft (Fin 1)) (-(1 : Fin 1 → ℤ)) =
      -(1 : Fin 1 → ℝ) := by
    simp only [map_neg, intCast_finOne_one]
  simpa only [negativeRayCone, hi] using
    isRegularCone_hull_singleton (isIntegralLattice_intCast 1) hv

/-- The positive and negative standard rays meet only at the origin. -/
theorem affineRayCone_inf_negativeRayCone :
    affineRayCone ⊓ negativeRayCone = ⊥ := by
  apply le_antisymm _ bot_le
  intro x hx
  have hx0 : x 0 = 0 := le_antisymm (mem_negativeRayCone_iff x |>.mp hx.2)
    (mem_affineRayCone_iff x |>.mp hx.1)
  have h : x = 0 := by
    ext j
    simpa [Subsingleton.elim j 0] using hx0
  exact h ▸ Submodule.zero_mem _

private theorem inf_eq_bot_of_le_affineRayCone_of_le_negativeRayCone
    {σ τ : PointedCone ℝ (Fin 1 → ℝ)} (hσ : σ ≤ affineRayCone)
    (hτ : τ ≤ negativeRayCone) : σ ⊓ τ = ⊥ := by
  apply le_antisymm _ bot_le
  calc
    σ ⊓ τ ≤ affineRayCone ⊓ negativeRayCone := inf_le_inf hσ hτ
    _ = ⊥ := affineRayCone_inf_negativeRayCone

/-- The complete fan with the positive and negative standard rays. A cone belongs to this fan
exactly when it is a face of one of the two rays. -/
def projectiveLineFan : Fan ((Int.castAddHom ℝ).compLeft (Fin 1)) where
  lattice := isIntegralLattice_intCast 1
  cones := {σ | σ.IsFaceOf affineRayCone ∨ σ.IsFaceOf negativeRayCone}
  finite_cones := by
    have heq : {σ : PointedCone ℝ (Fin 1 → ℝ) |
        σ.IsFaceOf affineRayCone ∨ σ.IsFaceOf negativeRayCone} =
        (Fan.ofCone (isIntegralLattice_intCast 1)
          isRegularCone_affineRayCone.toIsToricCone).cones ∪
        (Fan.ofCone (isIntegralLattice_intCast 1)
          isRegularCone_negativeRayCone.toIsToricCone).cones := by
      ext σ
      simp only [Set.mem_ofPred_eq, Set.mem_union, Fan.mem_ofCone_cones]
    rw [heq]
    exact ((Fan.ofCone (isIntegralLattice_intCast 1)
      isRegularCone_affineRayCone.toIsToricCone).finite_cones.union
      (Fan.ofCone (isIntegralLattice_intCast 1)
        isRegularCone_negativeRayCone.toIsToricCone).finite_cones)
  isToricCone := by
    intro σ hσ
    rcases hσ with hσ | hσ
    · exact isRegularCone_affineRayCone.toIsToricCone.of_isFaceOf hσ
    · exact isRegularCone_negativeRayCone.toIsToricCone.of_isFaceOf hσ
  mem_of_isFaceOf := by
    intro σ τ hσ hτσ
    exact hσ.elim (fun h ↦ Or.inl (hτσ.trans h)) (fun h ↦ Or.inr (hτσ.trans h))
  inf_isFaceOf_left := by
    intro σ τ hσ hτ
    rcases hσ with hσ | hσ
    · rcases hτ with hτ | hτ
      · exact (PointedCone.IsFaceOf.isFaceOf_iff_le (hσ.inf_left hτ) hσ).2 inf_le_left
      · have hbot : σ ⊓ τ = ⊥ := by
          exact inf_eq_bot_of_le_affineRayCone_of_le_negativeRayCone hσ.le hτ.le
        rw [hbot]
        exact (isRegularCone_affineRayCone.toIsToricCone.of_isFaceOf hσ).salient.bot_isFaceOf
    · rcases hτ with hτ | hτ
      · have hbot : σ ⊓ τ = ⊥ := by
          rw [inf_comm]
          exact inf_eq_bot_of_le_affineRayCone_of_le_negativeRayCone hτ.le hσ.le
        rw [hbot]
        exact (isRegularCone_negativeRayCone.toIsToricCone.of_isFaceOf hσ).salient.bot_isFaceOf
      · exact (PointedCone.IsFaceOf.isFaceOf_iff_le (hσ.inf_left hτ) hσ).2 inf_le_left

/-- The only cones of the projective-line fan are the origin and its two rays. -/
@[simp]
theorem mem_projectiveLineFan_cones (σ : PointedCone ℝ (Fin 1 → ℝ)) :
    σ ∈ projectiveLineFan.cones ↔
      σ = ⊥ ∨ σ = affineRayCone ∨ σ = negativeRayCone := by
  simp only [projectiveLineFan, Set.mem_ofPred_eq]
  constructor
  · rintro (h | h)
    · rw [affineRayCone_def] at h
      rcases h.eq_bot_or_eq_of_hull_singleton 1 with h | h
      · exact Or.inl h
      · exact Or.inr (Or.inl (h.trans affineRayCone_def.symm))
    · rw [negativeRayCone_def] at h
      rcases h.eq_bot_or_eq_of_hull_singleton (-(1 : Fin 1 → ℝ)) with h | h
      · exact Or.inl h
      · exact Or.inr (Or.inr (h.trans negativeRayCone_def.symm))
  · rintro (h | h | h)
    · subst σ
      exact Or.inl isRegularCone_affineRayCone.toIsToricCone.salient.bot_isFaceOf
    · subst σ
      exact Or.inl (PointedCone.IsFaceOf.refl _)
    · subst σ
      exact Or.inr (PointedCone.IsFaceOf.refl _)

/-- The positive affine-ray chart belongs to the projective-line fan. -/
theorem affineRayCone_mem_projectiveLineFan : affineRayCone ∈ projectiveLineFan.cones :=
  Or.inl (PointedCone.IsFaceOf.refl _)

/-- The negative affine-ray chart belongs to the projective-line fan. -/
theorem negativeRayCone_mem_projectiveLineFan : negativeRayCone ∈ projectiveLineFan.cones :=
  Or.inr (PointedCone.IsFaceOf.refl _)

/-- The projective-line fan is regular, so its analytic realization is a complex manifold. -/
theorem isRegular_projectiveLineFan : projectiveLineFan.IsRegular := by
  rw [Fan.isRegular_iff]
  intro σ hσ
  rcases hσ with hσ | hσ
  · exact isRegularCone_affineRayCone.of_isFaceOf hσ
  · exact isRegularCone_negativeRayCone.of_isFaceOf hσ

/-- Every real vector lies in one of the two rays of the projective-line fan. -/
theorem isComplete_projectiveLineFan : projectiveLineFan.IsComplete := by
  rw [Fan.isComplete_iff]
  intro x
  by_cases hx : 0 ≤ x 0
  · refine ⟨affineRayCone, affineRayCone_mem_projectiveLineFan, ?_⟩
    exact (mem_affineRayCone_iff x).mpr hx
  · refine ⟨negativeRayCone, negativeRayCone_mem_projectiveLineFan, ?_⟩
    exact (mem_negativeRayCone_iff x).mpr (le_of_lt (lt_of_not_ge hx))

end TauCeti.Toric
